### ISSUE TITLE
[Bug]: Back button in the chips overview does not respond

### ISSUE THREAD

**Issue by MauiR** [piitaya/lovelace-mushroom#1006]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

The chips card "back" cannot always be clicked (only on mobile). This is often the case when the app was previously closed. 
Then only a restart of the app, or reset to the home page helps. Reloading the page does not help. 
Also, sometimes the clickable zone seems to move. Maybe it has something to do with the small display of the iPhone12 mini. 

Devices or entities can be turned on/off or viewed normally. 

### Expected Behavior

The chips card "back" should always be pressed and the activation zone should be large enough. 

### Steps To Reproduce

So far, I have not been able to reproduce it consistently. It is best to leave the app open in the background for some time. 

### Context

So far only occurred on my iPhone 12 mini.

### Environment

```markdown
- Browser: Safari 16.3
- HA Version: 2023.3.0
- Mushroom: 2.6.1
```

**Comment by wimrottiers4** [comment]
Having the exact same issues on an iPhone SE 2021
When tabbing from HASS app to other apps and returning back to the app, the back button is not working.
On top of that, navigate buttons to other pages also don't seem to be working, so perhaps its rather a "navigate" bug instead of purely the back button not working

**Comment by MauiR** [comment]
> Having the exact same issues on an iPhone SE 2021 When tabbing from HASS app to other apps and returning back to the app, the back button is not working. On top of that, navigate buttons to other pages also don't seem to be working, so perhaps its rather a "navigate" bug instead of purely the back button not working

Does the navigation not work on the home page or only in submenus? I can't see any navigation problems on the home page.

**Comment by piitaya** [comment]
The back button just do a history.back action. If you do to other apps and returning back, the history can be lost so the back button will not work.

**Comment by MauiR** [comment]
Thanks for the clarification. I think this issue can be closed. 
I will replace the back function with an action. Since I always want to go to the same page.
