### ISSUE TITLE
[Bug]: Time is not displayed correctly in the mushroom-entity-card

### ISSUE THREAD

**Issue by MauiR** [piitaya/lovelace-mushroom#1015]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

If you display a time in the mushroom-entity-card it will not be displayed in the format (hh:mm:ss) instead it will be displayed in decimal.
E.g: 14:23:24 -> 14,39h

![Unbenannt](https://user-images.githubusercontent.com/86602061/217317269-0361219a-6d78-4e2c-8cc2-d0425c4fadb6.PNG)

### Expected Behavior

A time in the decimal view is difficult to read. There should be an option to display the time in the format (hh:mm:ss). Of course it would be nice to be able to choose how accurate you want the time to be, so it's more minimalistic. 

### Steps To Reproduce

Create a mushroom-entity-card and select a time as entity.

### Environment

```markdown
- Browser: Chrome
- HA Version: 2023.2.2
- Mushroom: 2.5.3
```

**Comment by piitaya** [comment]
How is it displayed with other HA card ? (entity card for example)

**Comment by MauiR** [comment]
![Unbenannt](https://user-images.githubusercontent.com/86602061/217327555-68f7eb9a-5696-42c0-af19-14523b6a4790.PNG)

**Comment by piitaya** [comment]
Thanks ? And what the state and attributes of your entity?

**Comment by MauiR** [comment]
![Unbenannt](https://user-images.githubusercontent.com/86602061/217334605-8f47eb31-79c9-4505-89bb-01ae0f467b3f.PNG)

**Comment by piitaya** [comment]
Hi 😅 It should be fixed with the [`2.6.0` version](https://github.com/piitaya/lovelace-mushroom/releases/tag/v2.6.0). Can you confirm so we can close this issue?

**Comment by MauiR** [comment]
> Hi 👋 It should be fixed with the [`2.6.0` version](https://github.com/piitaya/lovelace-mushroom/releases/tag/v2.6.0). Can you confirm so we can close this issue?

Yes, now the time is displayed correctly. Great work!
