### ISSUE TITLE
[Feature]: Climate card - temperature min and max limits - for example can set between 55 and 60 but no less or more.

### ISSUE THREAD

**Issue by user897943** [piitaya/lovelace-mushroom#1016]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Don't think so

### Describe the solution you'd like

I want to be able to set the thermostat card to certain temp limits so the person using it cannot bypass the lock on the Nest thermostat. In the current card they can set as high as they want making the bill eye-wateringly high in the UK. Even if the Nest is locked!!!!!! I need to be able to limit the card so the individual is not able to set it over 60 F. I currently have my Nest locked to between 55 and 60 so if anyone tries to scroll the screen past 60 or under 55 they simply cannot. I wanna have the same control on the mushroom climate card.

### Describe alternatives you've considered

Stop using the card. Or use the other custom restriction card to set a password but this is irritating because then only I can change the temp. I want anyone in the house to be able to change BUT within certain limits.

### Additional context

This is urgent. Bills are sky-high in the UK so having the ability to offer control within limits to keep bills reasonable is definitely high on the list.

**Comment by piitaya** [comment]
Hi 🙂 Each climate entity expose `target_temp_step` (and the default is 0.5 in Home Assisant).
You can customize this in your `configuration.yaml` if you want :

https://www.home-assistant.io/docs/configuration/customizing-devices/#manual-customization

```yaml
homeassistant:
  customize:
    climate.family_room:
      max_temp: 60
```

**Comment by user897943** [comment]
Although I won't be using this in the interim due to it blocking it for everyone (I have a separate dash for myself to retain full control of all devices as the system admin). I need a solution that's per-card not per-device and this one won't work unfortunately but very good to know it's there, I wasn't aware it could even be done per-device. Thanks. Any idea if this could be implemented on the card itself for situations like mine when there are multiple dashboards covering different user/permission situations and the card itself is restricted?

**Comment by piitaya** [comment]
I don't think it will be implemented because it will add lot of options (and lot of maintenance). Some people will ask to restrict the light brightness slider, the cover etc...

**Comment by user897943** [comment]
Okay but those things won't change your bills by £100's whereas just a 1
degree difference right now in Europe can add a lot to the bill. I don't
think it's fair to compare lights and shades to a boiler/furnace, those are
low power items that can even work on a battery. I'm asking because
sometimes it's not safe to leave the house too cold depending who's in it
and I don't wanna have to edit my config file every time I need an override
as it requires a complete restart of HA which can be risky when done
remotely. I've had everything stop working while on vacation so that was
the locks, lights, shades, all automations. This may not be a popular
request but I'm sure I'm not the only one with the need to restrict the
card only. Can I ask how it will add so much maintenance? Isn't it just a
few lines of code to say if the value is less than, or more than, do not
accept... If I knew how to write code I'd contribute it myself just to help
others in the same situation. Bills for heating in the UK are
stratospheric, lots of people are starving to even kept warm.

**Comment by piitaya** [comment]
Feel free to fork the project to add this feature if you really need it but it will not be merged. 

I do not prefer to add this for the reasons I explained in my previous post.

**Comment by user897943** [comment]
Hm, I thought I made it clear that I would code it myself except I don't
know how to do that.

Fine, no problem, I'll find a way without your help, thanks.
