### ISSUE TITLE
Washer card

### ISSUE THREAD

**Issue by diegomontanaduarte** [piitaya/lovelace-mushroom#102]
I'm very excited about the development of Mushroom. Is it possible to implement a Washer Card like this in the future?

Idle

![image](https://user-images.githubusercontent.com/2682853/153687758-751bb856-6911-4803-a6de-7a50ad1abfb9.png)

Running

![image](https://user-images.githubusercontent.com/2682853/153687796-977a856e-05bc-4581-8db3-bccfe39ff204.png)

Reference: https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/484

**Comment by piitaya** [comment]
Hi!
I don't think will possible to add card like this because there is no washing machine entity in HA. It look like a custom combination of multiple entities and will be difficult create this with an editor.
I think we can only have this design with vaccum or climate card.

**Comment by diegomontanaduarte** [comment]
@piitaya Thanks for answering. I know this is a specific Washer entity but any option to implement this like a custom card for example?

**Comment by mssmison** [comment]
You can replicate this pretty well just not directly with a mushroom card.

Stack in card
A vertical stack that contains two horizontal stacks.
Horizontal 1. Entity card + conditional card with the entity card showing the sensor data
Horizontal 2. Grid card with the 4 or 5 cards you want.

**Comment by apfelflo89** [comment]
![image](https://user-images.githubusercontent.com/48082211/153869991-fb8a58c4-bbec-417f-9fa7-9df74a81fd49.png)


I did it with an input_select and automation in the backend and use a template card to show the relevant informations:

```
type: conditional
conditions:
  - entity: input_select.trockner_status
    state_not: Aus
card:
  type: custom:mushroom-template-card
  primary: "{% if  is_state(\"input_select.trockner_status\", \"Fertig\") %}  Trocker ist {{ states(\"input_select.trockner_status\") }} seit {{as_timestamp(strptime(states('input_datetime.trockner_fertig'), '%Y-%m-%d  %H:%M:%S')) | timestamp_custom(\"%H:%M Uhr\") }} {% elif is_state(\"input_select.trockner_status\", \"in Betrieb\") %} \_ Trocker ist  {{ states(\"input_select.trockner_status\") }} seit {{as_timestamp(strptime(states('input_datetime.trockner_start'), '%Y-%m-%d  %H:%M:%S')) | timestamp_custom(\"%H:%M Uhr\") }} {% else %} Trocker ist {{ states(\"input_select.trockner_status\") }}  {% endif %}"
  secondary: '{{ states("sensor.trockner_laufzeit") }}'
  icon: mdi:tumble-dryer
  icon_color: >-
    {% if 'Fertig' in states("input_select.trockner_status") %} {{"green"}}  {%
    elif 'in Betrieb' in states("input_select.trockner_status")  %} {{"red"}} 
    {% else %} {{"grey"}} {% endif %}

**Comment by diegomontanaduarte** [comment]
@apfelflo89 very interesting! Thanks for sharing!
