### ISSUE TITLE
[Bug]: title_tap_action shows a > in title

### ISSUE THREAD

**Issue by Vansmak** [piitaya/lovelace-mushroom#1030]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Title show just be what is on title: my title
When I add  title_tap_action:
The title then shows My title >
It till works but I can't get rid of the >
![Screenshot_20230219_113852_Home Assistant](https://user-images.githubusercontent.com/16037573/219971343-b406991d-83c5-4c31-bffd-94b35a827d5e.jpg)

### Expected Behavior

Title show just be what is on title: my title

### Steps To Reproduce

Add new card for mushroom-title-card

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: home assistant app
- HA Version:2023.2.5
- Mushroom:v2.5.3
```

**Comment by piitaya** [comment]
It's not a but, it's a feature. Navigable titles must be different than read only titles.
Apple Home do this too.
[image](https://user-images.githubusercontent.com/5878303/219973429-73e92a72-3630-4b7d-bab9-f83d2e39f492.jpeg)

**Comment by Vansmak** [comment]
Well that's unfortunate, I don't like it. I'll have to use custom banner card instead because it doesn't show that. Thanks for letting me know.
