### ISSUE TITLE
Header at the bottom

### ISSUE THREAD

**Issue by cyrilphoenix71** [piitaya/lovelace-mushroom#104]
**Is your feature request related to a problem? Please describe.**
The problem is that chips card + tab header make a big header not ergonomic

**Describe the solution you'd like**
May be chips card can automaticaly and some code to do like this : https://github.com/UI-Lovelace-Minimalist/UI/issues/346

**Comment by pierrecle** [comment]
It's a theme feature, a close one is opened here: https://github.com/piitaya/lovelace-mushroom-themes/issues/1
I set won't fix 'cause it's a won't fix here.
