### ISSUE TITLE
[Bug]: Climate Card buttons overlapping

### ISSUE THREAD

**Issue by ArchidoNL** [piitaya/lovelace-mushroom#1040]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

In version 2.6.0 when using the Climate card with layout: horizontal and show_temperature_control: true, the "+" and "-"-buttons overlap with the button for setting the mode. This is induced when updating from 2.5.3 to 2.6.0.

### Expected Behavior

The buttons not overlapping.

### Steps To Reproduce

type: custom:mushroom-climate-card
show_temperature_control: true
entity: climate.airco_woonkamer
name: Airco
hvac_modes:
  - 'off'
  - cool
  - heat
icon: mdi:air-conditioner
layout: horizontal

### Context

State:
heat

Attributes:
hvac_modes: off, heat, dry, cool, fan_only, heat_cool
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: LOW, LOW_MID, MID, MID_HIGH, HIGH, NATURE
swing_modes: VerticalOff, VerticalTop, VerticalMiddleTop1, VerticalMiddleTop2, VerticalMiddleBottom2, VerticalMiddleBottom1, VerticalBottom, VerticalSwing, VerticalOff, HorizontalOff, HorizontalLeft, HorizontalMiddleLeft, HorizontalCenter, HorizontalMiddleRight, HorizontalRight, HorizontalLeftHalf, HorizontalRightHalf, HorizontalSwing
current_temperature: 20
temperature: 19
fan_mode: NATURE
swing_mode: VerticalOff
swing_mode_horizontal: HorizontalOff
swing_mode_vertical: VerticalOff
friendly_name: Airco Woonkamer
supported_features: 41

### Environment

```markdown
- Browser: Chrome
- Home Assistant 2023.2.5
- Supervisor 2023.01.1
- Operating System 9.5
- Frontend-versie: 20230202.0 - latest
- Mushroom: 2.6.0
```

**Comment by mikedrawback** [comment]
this change squishes the increase and decrease buttons a lot closer together. It was easier to reach and tap the right one with the old layout. Is this intended?

![image](https://user-images.githubusercontent.com/2569501/223934347-f83bd3c4-20cd-4dca-b090-db786be2caf2.png)
