### ISSUE TITLE
Thermostat layout broken since 2.6.0

### ISSUE THREAD

**Issue by lenwar** [piitaya/lovelace-mushroom#1047]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Since 2.6.0 the layout of the ‘horizontal’ climate card is broken. (The mode and the controls are overlapping)
![IMG_7811](https://user-images.githubusercontent.com/3773186/221840331-03ef669f-1ab7-41f2-b70f-287191c39738.jpeg)
 

### Expected Behavior

Have them next to each other :)

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: HA app on iOS 16.4. Also on Safari on iOS
- HA Version: 2023.2.5
- Mushroom:2.6.0
```

**Comment by piitaya** [comment]
Hello 👋
It's a duplicate : https://github.com/piitaya/lovelace-mushroom/issues/1040
It will be fixed in the next upcoming release.

**Comment by lenwar** [comment]
Apologies. I missed that one.
