### ISSUE TITLE
Alarm chip icon color not honored

### ISSUE THREAD

**Issue by brandensilva** [piitaya/lovelace-mushroom#105]
**Describe the bug**

Setting the icon color does nothing for the alarm chip icon

**To Reproduce**

1. Add an alarm chip
2. Set the icon color to any color from the icon color dropdown
3. Click save

**Expected behavior**

Expect to see the color set on the icon

**Screenshots**

<img width="413" alt="image" src="https://user-images.githubusercontent.com/200190/153695929-3b5ac13c-ee16-44db-ba69-66ae92b38cc4.png">

**Comment by piitaya** [comment]
The chip color is only applied when entity state is active (armed for alarm for example). It's the same behaviour than entity card.
Maybe we should edit the label or display this info in the editor.

**Comment by piitaya** [comment]
It's a documenation issue, this should be fixed when https://github.com/piitaya/lovelace-mushroom/issues/73 will be done

**Comment by pierrecle** [comment]
@piitaya maybe we could create an alarm chip, like the light chip?

**Comment by brandensilva** [comment]
@piitaya I see. Why not support both colors? Similar to how we think about "on" and "off" states having two distinct states, it seems like it would be beneficial if the colors could support both of those to cover all the use cases around that.

**Comment by piitaya** [comment]
For entity chip, the rules are :
- entity is inactive (off, disarmed, not_home) : non-colored state
- entity is active (on, playing, armed, home, etc...) : colored state

For entity card, the rules are :
- entity is inactive (off, disarmed, not_home) : disabled state
- entity is active (on, playing, armed, home, etc...) : colored state

I think we must create an alarm chip as proposed by @pierrecle to have the same color rules than the alarm panel card.

**Comment by brandensilva** [comment]
I gotcha. I'm less familiar with the code base at this point but out of curiosity why do entity chips function differently than entity cards regarding their color states?

I'm not opposed to an alarm chip either but it seems like it is always a necessity to make new chips to accommodate the behavior people might be expecting to function similar to entity cards.

**Comment by piitaya** [comment]
It's the same behaviour.
Entity card and chip have only two state and two colors
Alarm card have multiple state and colors :
- triggered : red
- armed : green
- disarmed : blue
- unavailable : grey

If we want chip with these colors, we need to have an alarm chip because entity have only 2 states : colored when active, grey when active (like entity card)
What behaviour do your want with your chip?
