### ISSUE TITLE
Home Assistant Android app error

### ISSUE THREAD

**Issue by vawaver** [piitaya/lovelace-mushroom#106]
Home Assistant 2022.2.6 - server
HA for Android v2022.1.1-full

I added Custom Mushroom Light Card to Lovelace.
When I opened Home Assistant on my Android phone I see this error message only.

![Screenshot_20220212_130831_io homeassistant companion android](https://user-images.githubusercontent.com/52236863/153720403-a82ce3a2-cd16-4380-8707-5967af2a74cb.jpg)

**Comment by piitaya** [comment]
Try reinstall Mushroom. It looks like a cache issue.

**Comment by vawaver** [comment]
I found a solution for that. Because the card was inserted on the new Lovelace.

It is necessary to restart the Home Assistant app on an Android phone, or just restart the phone.
