### ISSUE TITLE
[Bug]: Mushroom cards render OK on local network, but "doesnt exist" via external Cloudflare connection

### ISSUE THREAD

**Issue by icornish72** [piitaya/lovelace-mushroom#1062]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

When connecting via local LAN, card renders perfectly. But when connecting via cloudflare tunnel, only the mushroom cards render as this:-
![image](https://user-images.githubusercontent.com/78433319/223780234-e41b1059-cbaf-4dbd-a91a-2458e2b90264.png)

### Steps To Reproduce

Connecting via local lan, rendering is perfect
connection via Cloudflare tunnel, render is wriong. Only Mushroom cards have this issue - other controls/cards render fine.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:2023.03.1
- Mushroom: 2.6.1
```

**Comment by piitaya** [comment]
Mushroom is like any other custom card. There are closed issues about caching issues or similar things. I suggested you to try to delete mushroom ressources, uninstall and reinstall Mushroom.

**Comment by nraimo1** [comment]
Same issue here, issue since HA update and seems mushroom cards have disappeared even if i try add a new card,  Plugin still downloaded tried redownload same issue suspect it needs a patch

**Comment by icornish72** [comment]
Removed and reinstalled, and waited overnight for HAos to settle down, and all was well.
