### ISSUE TITLE
[Bug]: number-card doesn't show up

### ISSUE THREAD

**Issue by gbcatrinoiu** [piitaya/lovelace-mushroom#1071]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

After updating the lovelace-mushroom integration through hacs, the new number-card component does not show up in the list of components from the dashboard editor.

### Expected Behavior

The new number-card should be showing up.

### Steps To Reproduce

1. update lovelace-mushroom to the latest version through HACS
2. check the list of cards from the dashboard editor

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome on MacOS
- HA Version: 2023.3.3
- Mushroom: v2.6.1
```

### Anything else?

Everything is up to date.
I also tried to add the code, but it doesn't work.

**Comment by piitaya** [comment]
There is multiple closed issue about this. It's always a cache issue.

**Comment by gbcatrinoiu** [comment]
I only search for the number-card keyword. cleared the cache and it works fine now. thanks!

btw you are doing nice work with the mushroom integration. it is much appreciated, thanks!
