### ISSUE TITLE
[Bug]: Frontend Issue with Duration Sensor

### ISSUE THREAD

**Issue by yjamal01** [piitaya/lovelace-mushroom#1075]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I am experiencing the issue described here: https://github.com/home-assistant/frontend/issues/15103
However for me the issue seems to be limited to the waze integration and the mushroom entity card.

Instead of the entity saying, for example, "15 min" it now says "15:00"
If I use the standard entity card with the waze travel integration, it displays as expected (15 min)
If I use the here travel integration instead with the mushroom entity card, it displays as expected (15 min)
However when using the waze travel integration and the mushroom entity card - it instead displays as clock format (15:00)

### Expected Behavior

Display the duration of travel as "X min" like it used to. 

### Steps To Reproduce

1. Setup waze integration with a travel time sensor
2. Use a mushroom entity card to display the sensor

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Multiple
- HA Version: 2023.03.4
- Mushroom:2.6.1
```

**Comment by mholbert1024** [comment]
I have the exact same problem. I use Waze in one of my chips and not showing this as example:

1:04:00 for one hour and four minutes. 
Use to display:
64 min

**Comment by yjamal01** [comment]
I haven't been able to find the cause (as I know nothing about code) but I managed to successfully use a template sensor to create a second sensor (based on the waze sensor). This allows it to display as expected.

**Comment by mholbert1024** [comment]
I had the same idea, but when trying to creating a template sensor, I get an error that states no sensor available in Waze. 

Do you mind sharing your template sensor code?

**Comment by yjamal01** [comment]
sure, I used chatgpt to produce it, so take it with a grain of salt lol. I've tested it and it seems to work as expected so far. 
`  - platform: template
    sensors:
      <new_sensor_entityid>:
        friendly_name: "<new sensor friendly name>"
        value_template: >-
          {% set time_str = states('sensor.yourwazesensor') %}
          {% if time_str %}
            {% set time_list = time_str.split(':') %}
            {% if time_list|length == 2 %}
              {%- set hours = time_list[0] | int -%}
              {%- set minutes = time_list[1] | int -%}
              {{ '{:d} hours and {:02d} minutes'.format(hours, minutes) }}
            {% elif time_list|length == 1 %}
              {%- set minutes = time_list[0] | int -%}
              {{ '{:d} min'.format(minutes) }}
          {% else %}
            Invalid Format
          {% endif %}
          {% else %}
            Unknown
          {% endif %} `
         
That works for me and it displays in minutes, just need to replace the variables with your entity information

**Comment by mholbert1024** [comment]
thank you much!

    On Thursday, March 16, 2023 at 01:35:25 PM PDT, yjamal01 ***@***.***> wrote:  
 
 


sure, I used chatgpt to produce it, so take it with a grain of salt lol. I've tested it and it seems to work as expected so far.
 - platform: template sensors: <new_sensor_entityid>: friendly_name: "<new sensor friendly name>" value_template: >- {% set time_str = states('sensor.yourwazesensor') %} {% if time_str %} {% set time_list = time_str.split(':') %} {% if time_list|length == 2 %} {%- set hours = time_list[0] | int -%} {%- set minutes = time_list[1] | int -%} {{ '{:d} hours and {:02d} minutes'.format(hours, minutes) }} {% elif time_list|length == 1 %} {%- set minutes = time_list[0] | int -%} {{ '{:d} min'.format(minutes) }} {% else %} Invalid Format {% endif %} {% else %} Unknown {% endif %}

That works for me and it displays in minutes, just need to replace the variables with your entity information

**Comment by mholbert1024** [comment]
Haha! I'm in the same boat as you. Thank you very much! I'm going to try this. Hopefully an official can get fixed at some point. I've done so much research and couldn't find anything.

**Comment by piitaya** [comment]
I close the issue because Mushroom use HA rules to format the state. If the HA behavior change, Mushroom will follow.
