### ISSUE TITLE
Change Font Size for Mushroom Title Card (I know this has been asked many times)

### ISSUE THREAD

**Issue by thisisbenwoo** [piitaya/lovelace-mushroom#1076]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I've search Google for days. I can't seem to find a SIMPLE approach to using card_mod to change the Font Size (and ultimately the line-height) of the Mushroom Title Card. 

My current incarnation is as follows:
```
type: layout-card
layout_type: custom:masonry-layout
layout: {}
cards:
  - type: custom:mushroom-title-card
    title: Lighting
    subtitle: Bedroom
    card_mod:
      style: |
        ha-card {
          --card-primary-font-size: 40px;
        }
      action: none
    subtitle_tap_action:
      action: none
```
But I've literally tried every suggestion on the web that I can find. I've tried the --title-font-size, --mush-title-font-size.
I've tried to  use mushroom-title-card instead of ha-card. I've tried adding h1 and .title, but nothing is working. I am sure that the answer is pretty straightforward, but I'm new to CSS, and despite looking at the CSS literally for hours, I can't make it work.

So, I hope that someone can walk me through this. I know this question has been asked before, and most of the answers point me back to Thomas Loven's great work on the layout card and card_mod, but there isn't enough of a NOOB how-to or tutorial to get me on the right track.

Thanks in advance. 

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by piitaya** [comment]
Which documentation? There is no mention of `card_mod` support for all the cards in the documentation.

**Comment by thisisbenwoo** [comment]
> Which documentation? There is no mention of `card_mod` support for all the cards in the documentation.

Fair enough! I wasn't suggesting that there was any. So, is there actually a way to change the font-size and also the spacing between the Title and the Subtitle please? Thanks in advance.

**Comment by thisisbenwoo** [comment]
Thank you for the education. I NEVER would have found it in a million years!!

So for others looking for this, you need to go into 
config/themes/```[theme]```.yaml
and you add mush-title-font-size.
The various variables that can be defined can be found https://github.com/piitaya/lovelace-mushroom-themes#build-your-own
