### ISSUE TITLE
[Bug]: Number card increment/decrement

### ISSUE THREAD

**Issue by oxigen-dev** [piitaya/lovelace-mushroom#1079]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Before clicking on the + sign:
![image](https://user-images.githubusercontent.com/124933927/226063768-ef4bcc25-0e9e-4ea0-a3a9-620672274110.png)

After clicking on the + sign I see the following for a second:
![image](https://user-images.githubusercontent.com/124933927/226063851-c79bf2b2-786a-4edc-b400-244c238c6cc9.png)

At the end I get:
![image](https://user-images.githubusercontent.com/124933927/226063884-d56f335d-821b-4ac9-a793-25ae6b1e8b07.png)

### Expected Behavior

I'd expect to see 15.5 after clicking on the + sign and not 16 for a second.

### Steps To Reproduce

I have an MQTT number sensor:

```
  - name: "Thermostat Target Temperature"
    state_topic: "homeassistant/thermostat/target_temp/cmd"
    command_topic: "homeassistant/thermostat/target_temp/state"
    device_class: temperature
    qos: 2
    min: 5
    step: 0.5
    max: 35
```

On my Dashboard I'm using a Number Card for this:
```
- type: custom:mushroom-number-card
  entity: number.thermostat_target_temperature
  icon: mdi:thermometer
  fill_container: false
  display_mode: buttons
  layout: horizontal
  secondary_info: last-updated
```

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Firefox 111.0
- HA Version: 2023.3.3
- Mushroom: 2.6.1
```

**Comment by piitaya** [comment]
Thanks @oxigen-dev !
