### ISSUE TITLE
[Feature]: Chip Spacer

### ISSUE THREAD

**Issue by Majumafoo** [piitaya/lovelace-mushroom#1096]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I'd like to be able to adjust the position of chips beyond the Start, Center, End and Justify options that currently exist
![image](https://user-images.githubusercontent.com/45857221/230122748-1bee6c0f-6e80-4a5a-8ff3-4f8a505663d1.png)

### Describe the solution you'd like

I'd like a spacer chip which automatically adjusts to fill any white space and push other chips to the side.
Artists interpretation:
![image](https://user-images.githubusercontent.com/45857221/230124225-e15965ee-eed5-4f6b-9fb0-91a23da6c7ff.png)

This is a feature I've seen in a handful of applications. The menu in VLC comes to mind.

### Describe alternatives you've considered

I've created a blank chip and used null space characters to expand it to the size I want, but it doesn't play well when screen sizes change.
Either it gets too large and pushes chips to the next line, or is too small and doesn't do a good job spacing the chips.

Blank chip example:
![image](https://user-images.githubusercontent.com/45857221/230402817-85994285-2b0c-413c-bc1d-fc31c94af42e.png)
![image](https://user-images.githubusercontent.com/45857221/230125594-05f92a83-ceac-48ab-9419-eab99c50dfb1.png)

**Comment by GitHubGoody** [comment]
@bryan-stewart Thank you for adding this. This is working great for horizontal spacing when there is at least one other chip present. Any chance you could make it work as a chip placeholder for a chip card that has no other chips?
