### ISSUE TITLE
[Feature]: Alarm Panel

### ISSUE THREAD

**Issue by silvannn** [piitaya/lovelace-mushroom#1100]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Horizontal alarm card with only one button arm/disarm. Card option show keypad off.
When I press disarm I am getting error. Wrong Code.

### Describe the solution you'd like

Can we add default popup keypad when disarm button is pressed and code is required. New 2023.04 keypad looks good. Also can we update keypad look to newest version when card option show keypad is on.

**Comment by piitaya** [comment]
It's planned. For now you can use the tile card with alarm modes feature.
