### ISSUE TITLE
[Bug]: volume_buttons not shown in media_player card

### ISSUE THREAD

**Issue by wormiedk** [piitaya/lovelace-mushroom#1103]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I added the following config:
```
type: custom:mushroom-media-player-card
entity: media_player.koekken_sonos
use_media_info: true
use_media_artwork: true
show_volume_level: true
volume_controls:
  - volume_buttons
media_controls:
  - play_pause_stop
  - next
  - previous
```
but no volume buttons are shown. the volume_set options works

### Expected Behavior

Volume buttons shown

### Steps To Reproduce

1 add yaml
2 notice missing buttons

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Brave 1.49.132 Chromium: 111.0.5563.147 (Official Build) (arm 64)
- HA Version: 2023.4.1
- Mushroom: 2.6.3
```

**Comment by piitaya** [comment]
Hi. Another issue is already open : https://github.com/piitaya/lovelace-mushroom/issues/1078
