### ISSUE TITLE
Buttons not showing in the grid card

### ISSUE THREAD

**Issue by adamj3000** [piitaya/lovelace-mushroom#1106]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

As shown on below picture buttons are not showing in the grid card configuration. 

![image](https://user-images.githubusercontent.com/65854745/231683006-94d9a1ec-c10c-438b-b228-2ab5b09411cc.png)

### Expected Behavior

Can you advise? how to get buttons to display again?

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome, EDGE, Firefox
- HA Version: 2023.4.3
- Mushroom: 2.6.3
-  Mushroom Themes 0.0.9
```

**Comment by piitaya** [comment]
This issue is a config issue with the official button card, not a mushroom issue.
