### ISSUE TITLE
[Bug]: Spacer renders correctly in browser (Chrome), but not in iOS app

### ISSUE THREAD

**Issue by Swiftnesses** [piitaya/lovelace-mushroom#1113]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I placed a spacer between my chips, it's ignored in the iOS app.

### Expected Behavior

Spacer works (as per browser).

**Comment by piitaya** [comment]
It must be a cache issue. There is issue like this at each release. Try to refresh the page, kill the app, clear app cache (using app settings => debug)

**Comment by Swiftnesses** [comment]
Sorted - cleared cache. 

Thank you!
