### ISSUE TITLE
[Feature]: Input cards agnostic from input_helpers

### ISSUE THREAD

**Issue by luixal** [piitaya/lovelace-mushroom#1123]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Not really a problem, but it would make some things wide easier then they are right now. I'll put a real example:

I manage my irrigation system using HA with the [Irrigation Unlimited integration](https://github.com/rgc99/irrigation_unlimited). My system has 7 zones, each with with a `switch` that turns on/off irrigation in that zone. Irrigation Unlimited handles the scheduling, repetitions, irrgation times, etc...

I'm now working in building a dashboard to control irrigation as the custom card for Irrigation Unlimited is functional, but not really pretty (and it's not intended to be). I'm using mushroom cards in my other dashboard so it feels the way to go here too.

I would like to have a card for each zone (this is, 7 cards) which are built using other cards: a template card for the main info and turning on/off that zone, a number card for adjusting irrigation times and some chips/buttons for other info/features. Right now, I have something like this:

![image](https://user-images.githubusercontent.com/615268/233628828-9e6b6ed2-983d-4ce2-aa19-7118788a7f21.png)

Problem is: I have 7 zones so I need 7 cards like that one. Irrigation time is stored into an entity attribute provided by Irrigation Unlimited integration but, If I want to have something like this, I have to define 7 input number helpers to store the same info and at least to automations to keep those values synced.

Too much redundant things.

### Describe the solution you'd like

Make the number card agnostic from an input_number helper. This is:

  - Do not make an input_number entity mandatory and add an optional `value` field that takes a template. One of them should be set. This way I can avoid creating 7 helpers and can take the value from the entity's attribute.
  - Add an action for the `onChange'  event. This would make possible to call a service o do whatever other thing when the value is changed.

Combining this two things I won't need to create a lot of input helpers that I don't really need and can do whatever I want with the value of the input number when it's changed.

### Describe alternatives you've considered

Creating 7 input_number helpers and two automations for keeping entity attributes and helpers values synced.

It's possible, but a lot of redundant and innecesary data that can be avoided.

### Additional context

There are some other cases where I would make use of this kind of feature as I like to have as little helpers and automations as possible.

**Comment by piitaya** [comment]
You can define number entity using template. It would avoid creating an automation to keep it sync with others entity because the template is defined in the number entity itself.

Template number allow you to add step, min, max, state and set_value and will perfectly work in mushroom number card.

**Comment by luixal** [comment]
I think I explained myself badly, I'll put a concrete example:

- I got 7 entities which have an attribute called `duration` in HH:mm:ss format (i.e: 00:10:00 for 10 minutes). I only care about minutes so I get that value like this:

```yaml
state_attr('binary_sensor.irrigation_unlimited_c1_z2', 'next_duration').split(':')[1]
```

- In order to change this `duration` value, as the integration does some inner work, I need to call a service `adjust_time` passing a string like `=00:15:00` for setting that duration time to 15 minutes.

I was trying to avoid having 7 input_numbers that replicate the value from the attributes and the needed automation logic to keep them in sync.

I've also faced other scenarios like this where a _"dumb"_ input number would be very handy. That's why I was asking if it was possible to just provide the number card with an initial value (which I could get from an attribute) and an action, that could be calling a service.

Do you know if it's possible to accomplice this with the number card? I haven't found anything about the `set_value` field you mention other than the service to set the input_number value.

Thanks!

**Comment by piitaya** [comment]
Yes, I perfectly understood. I suggest you to create a template number for this : https://www.home-assistant.io/integrations/template/#state-based-template-binary-sensors-buttons-numbers-selects-and-sensors

So you won't have to create some automation. All your logic is inside the number entity (it's not dump). 
Something like that (I didn't tested the code but you got the idea) :

```yaml
template:
  - number:
    - name: "Zona 1"
      unit_of_measurement: minutes
      min: 0
      max: 15
      step: 1
      state: "{{ state_attr('binary_sensor.irrigation_unlimited_c1_z2', 'next_duration').split(':')[1] }}"
      set_value:
        - service: irrigation_unlimited.adjust_time
          data:
            entity_id: binary_sensor.irrigation_unlimited_c1_z2
            actual: "{{ value }}:00"
```

Mushroom was created to display information on your dashboard, not to build some logic. That's why there is only few options. Also, cards are domain based, so number card only accept number and input_number entity and this will not change.

For more advanced things, you can use [custom button card](https://github.com/custom-cards/button-card).

**Comment by luixal** [comment]
Sorry for the long time keeping this issue open :(

I didn't know about the `{{ value }}` variable existence. It's great! A pity that the helper is still needed when using it like this, but it does the work, thanks!
