### ISSUE TITLE
Polymer reference in code

### ISSUE THREAD

**Issue by Aviatorpaal** [piitaya/lovelace-mushroom#1124]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Home Assistant complains about Polymer and will discontinue support in 2023.5.

`WARNING (MainThread) [frontend.js.latest.202304111] WARNING: Polymer will be removed from window in Home Assistant 2023.5. More info: https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer`

### Steps To Reproduce

Mushroom Lovelace and Mushroom Themes, latest versions from HACS.

### Environment

```markdown
- Browser: Safari
- HA Version: 2023.4
- Mushroom: 2.7.0
```

**Comment by piitaya** [comment]
Hello. Do you have any other custom card installed? From what I know, Mushroom doesn't use Polymer.

**Comment by casakampa** [comment]
I got the same warning in my logs after I added mushroom.js to the resources of Home Assistant and created some cards.
Other cards I use are [mini-graph-card](https://github.com/kalkih/mini-graph-card) and [Hass Hue Icons](https://github.com/arallsopp/hass-hue-icons) and before adding mushroom.js, they didn't generate any errors.

**Comment by Aviatorpaal** [comment]
> Hello. Do you have any other custom card installed? From what I know, Mushroom doesn't use Polymer.

Hi,

I have the following custom frontend repositories:

- apexcharts-card
- Entur Card
- card-mod
- Mushroom
- Mushroom Themes


In the JS-file for lovelace-mushroom I find a single reference to Polymer in the code. Could this be it, or am I lost?

**Comment by piitaya** [comment]
There is "Polymer" word in Mushroom code but it's just a comment. Mushroom has been tested with `2023.5` and works well.
