### ISSUE TITLE
[Bug]: Climate Card - HA 2023.6.0 - Tap default action - No longer toggling climate

### ISSUE THREAD

**Issue by isewise** [piitaya/lovelace-mushroom#1160]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Previous to 2023.6.0, the default tap action for the Mushroom climate card turned my connected climate units on to the previous setting. Another tap would turn them off. 

After I upgraded to 2023.6.0, the default tap action does not turn on the unit, but once it is on, tapping once will turn off the unit. 

### Expected Behavior

Tap once, to turn on climate to previous setting. 
Tap again, to turn off. 

### Steps To Reproduce

Climate card
Tap action set to "Default"

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome & in latest Android app
- HA Version: 2023.6.0
- Mushroom: 2.7.1
```

**Comment by piitaya** [comment]
Can you describe more the issue you have? What integration do you use? Can you provide the state of your entity using [dev tools](https://home.piitaya.fr/developer-tools/state) and the yaml of the card you use? I'm unable to reproduce it.

**Comment by isewise** [comment]
I'm sorry the issue was HA
https://github.com/home-assistant/core/issues/94534

Everything is fine now.
