### ISSUE TITLE
[Feature]: Support color code "primary"

### ISSUE THREAD

**Issue by chrisb86** [piitaya/lovelace-mushroom#1164]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Home Assistant seems to support color codes "primary" and "disabled" for icon configurations now. In the tile card I can define these as icon colors and everything works as expected.

In the mushroom Teamplate card only "disabled" works.

I'm not shure if this is a bug report or a feature request.

### Describe the solution you'd like

I would like to use "primary" too to get a consistent look when these colors change by e.g. a theme switch without changing it by hand at all relevant cards.

**Comment by Deldion** [comment]
Great work!! Coherence with themes!! 
Now only remain the other cards, like
- custom:mushroom-media-player-card
- custom:mushroom-cover-card
- custom:mushroom-vacuum-card
