### ISSUE TITLE
[Bug]: Box shadow of title card

### ISSUE THREAD

**Issue by ccMatrix** [piitaya/lovelace-mushroom#1177]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

After the update of the Title card to use ha-card as a base it now has a box-shadow applied to it which shouldn't be there.

![image](https://github.com/piitaya/lovelace-mushroom/assets/96917/70607ccd-885b-4096-a55b-6ee59df6e59e)

### Expected Behavior

Same look like before the ha-card update.

### Steps To Reproduce

1. Add a Title card
2. See box-shadow

### Environment

```markdown
- Browser:  Chrome
- HA Version: Home Assistant 2023.6.2 Frontend 20230608.0
- Mushroom: 2.8.0
```

### Anything else?

The fix is a simple line with
```
box-shadow: none;
```
In the css of the .header class that is applied to the Title card

**Comment by limitless00net** [comment]
Same issue

**Comment by Pepeanuts** [comment]
same here

**Comment by thehedgefrog** [comment]
Same.  Could not find a way to remove it.
