### ISSUE TITLE
[Bug]: Default HVAC mode for climate

### ISSUE THREAD

**Issue by 1iverea9er** [piitaya/lovelace-mushroom#1187]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Now clicking on the climate map causes the device to turn on/off with setting the default hvac mode as "heat".

### Expected Behavior

It would be more correct to untie the set hvac mode  "heat"  from the on/off function of device in one of the following ways:
1) Provide the user with a manually set HVAC mode when the device turn on fuction call;
2) Remove the default hvac mode setting when the device is turned on.

### Steps To Reproduce

This is a problem for multisplit AC's. For such AC's, it is impossible to set the "cool" and "heat" modes simultaneously for indoor units.
Thus, if one of the blocks is in the "cool" mode, when the next block is turned on by clicking on the card, the integration will try to set the "heat" mode. Since this is not possible, therefore the AC will turn off.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome (114.0.5735.135)
- HA Version: 2023.6.3
- Mushroom: 2.8.1
```

**Comment by piitaya** [comment]
Hello. Mushroom can not control the default the default HVAC mode. You can write a script and call it from the action if you want custom behavior.
