### ISSUE TITLE
[Feature]: Add template support for number card

### ISSUE THREAD

**Issue by Krojack** [piitaya/lovelace-mushroom#1188]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I just want to be able to change the icon color based off the number value.

### Describe the solution you'd like

Allow template support for changing some items like icon color

Example
```
icon_color: |
  {% if states('input_number.strength')|int >= 70 %}
    green
  {% elif states('input_number.strength')|int >= 60 %}
    yellow
  {% elif states('input_number.strength')|int > 45 %}
    red
  {% else %}
    grey
  {% endif %}
```
### Describe alternatives you've considered

Template card and badges just don't display the slider bar like number card does.

**Comment by piitaya** [comment]
Hello. It's not plan for now to add template support to other card than template card and template chip.
Mushroom is designed per domain and try to fit most use-cases. If we add such option, someone will want to add state template, badge, etc.. and every card will have tons of options.
