### ISSUE TITLE
[Bug]: assist action is not working

### ISSUE THREAD

**Issue by limitless00net** [piitaya/lovelace-mushroom#1191]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

After the core-2023.7.0 update, I tested the 'assist action' of #1173 on a mushroom card. but this doesn't work.

### Expected Behavior

open assist from mushroom card

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome
- HA Version: core-2023.7.0
- Mushroom: v2.8.1
```

**Comment by piitaya** [comment]
The Mushroom version that support it is not released yet. It will be available soon 🙂
