### ISSUE TITLE
Fan card does not animate anymore

### ISSUE THREAD

**Issue by Toolhead** [piitaya/lovelace-mushroom#1195]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Animation on fan card stopped working on update to 3.0.0.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Safari
- HA Version: 2023.7.1
- Mushroom: 3.0.0.
```

**Comment by LeiChat** [comment]
Is this related to the card_mod breaking change, where ha-icon needs to be replaced by ha-state-icon?
I've amended mine but it did not fix the unanimated icons.
```
card_mod:
  style:
    mushroom-shape-icon$: |
      ha-state-icon {
        {{ '--icon-animation: pulse 3s linear infinite;' if is_state('sensor.myenergi_zappi_plug_status', 'Charging') }}
      }
```

**Comment by piitaya** [comment]
> Is this related to the card_mod breaking change, (mentioned in [release notes](https://github.com/piitaya/lovelace-mushroom/releases/tag/v3.0.0)) where ha-icon needs to be replaced by ha-state-icon? I've amended mine but it did not fix the unanimated icons.
> 
> ```
> card_mod:
>   style:
>     mushroom-shape-icon$: |
>       ha-state-icon {
>         {{ '--icon-animation: pulse 3s linear infinite;' if is_state('sensor.myenergi_zappi_plug_status', 'Charging') }}
>       }
> ```

You should be able to do :
```yaml
card_mod:
  style: |
    mushroom-shape-icon {
        {{ '--icon-animation: pulse 3s linear infinite;' if is_state('sensor.myenergi_zappi_plug_status', 'Charging') }}
      }
```

**Comment by piitaya** [comment]
Safari doesn't handle animation the same way as firefox and chrome, I pushed a fix for that.

**Comment by LeiChat** [comment]
Thank you. That works. 👍

I had another couple of styles on the state info, perhaps that's why I was using the $ nesting!? 🤦‍♂️
```
    mushroom-state-info$: 
      .primary {
        font-size: 16px !important;
      }
      .secondary {
        font-size: 13px !important;
      }
```
