### ISSUE TITLE
Feature Request: Expandable Card

### ISSUE THREAD

**Issue by j-loewen** [piitaya/lovelace-mushroom#120]
I would like to have a Card that can be expanded. By default, it would be collapsed to save space and if you click on it, it would expand to show an additional card.

**Comment by piitaya** [comment]
This card already exist, you can do it with conditional card : https://www.home-assistant.io/lovelace/conditional/

**Comment by Roflcopterer** [comment]
I think more like this: https://www.w3schools.com/howto/howto_js_collapsible.asp

**Comment by j-loewen** [comment]
@Roflcopterer, yes that's the kind of card I would like to see.

**Comment by brandensilva** [comment]
Examples of other designed concepts that encapsulate this accordion functionality:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/200190/154382208-6113a060-da56-4ed0-842c-c46e4f012762.png">

<img width="690" alt="image" src="https://user-images.githubusercontent.com/200190/154382268-0a095ec1-5354-40fb-8196-5cd175e3518c.png">

<img width="338" alt="image" src="https://user-images.githubusercontent.com/200190/154382374-16715e68-c629-4620-b115-6ecacec48163.png">

**Comment by zsarnett** [comment]
The issue you have to deal with is a Jumpy UI. The reason why this hasn't been something we have added yet. We want the UI to stay as consistent as possible and not jump when state changes. Reason why the conditional card takes up space when the condition is false. To reserve it when its condition is met

**Comment by Roflcopterer** [comment]
There is also this custom card: https://github.com/RossMcMillan92/lovelace-collapsable-cards

**Comment by brandensilva** [comment]
@zsarnett Good to see you dropping down to support the community addons. Thanks for your work on HA!

I totally understand that and figured that was the case of why it doesn't exist. I think with the typical Masonry layout it would be problematic but for more advanced users who know how to control layout it wouldn't be a huge issue to deal with. I get that simplicity is key right now. 

Alternatively, you could also bump it out of document flow to be more like a dropdown. Users are used to that pattern more without it disrupting a layout even if it does happen to cover elements. Are there any plans to add dropdowns to HA to allow context menus like this? e.g) https://framer.com/share/Menu-Transitions--4WnylGTbp0uHEXrNlGdQ/kCNo8cAIp

Albeit this effect is more of an advanced way of handling dropdowns but the goal would be to offer more interactive actions and entities within context of a given layout or card without popups or screen transitions.
