### ISSUE TITLE
Animations still not working

### ISSUE THREAD

**Issue by wgumaa** [piitaya/lovelace-mushroom#1200]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Animations not working even after last update on iOS companion app. 

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by piitaya** [comment]
Did you follow : https://github.com/piitaya/lovelace-mushroom#i-dont-see-the-last-changes
Also, what animation are you talking about ? Can you share the config of your card ?

**Comment by EinfachKjell** [comment]
A configuration like this is not working anymore.

type: custom:mushroom-template-card
primary: ''
icon: |-
  {% if is_state('input_boolean.ventilator_test','on') -%}
  mdi:fan
  {%- else -%}
    mdi:fan-off
  {%- endif %}
icon_color: |-
  {% if is_state('input_boolean.ventilator_test','on') -%}
  blue
  {%- else -%}
  disabled
  {%- endif %}
entity: input_boolean.ventilator_test
layout: horizontal
tap_action:
  action: toggle
multiline_secondary: false
fill_container: true
hold_action:
  action: navigate
  navigation_path: /lovelace/schlafzimmer-ventilator
double_tap_action:
  action: none
badge_icon: |-
  {% if is_state("automation.schlafzimmer_ventilator_aus_15", "on") -%} 
  mdi:fast-forward-15
  {%- elif is_state("automation.schlafzimmer_ventilator_aus_30", "on") -%}
  mdi:fast-forward-30
  {%- elif is_state("automation.schlafzimmer_ventilator_aus_45", "on") -%}
  mdi:fast-forward-45
  {%- elif is_state("automation.schlafzimmer_ventilator_aus_60", "on") -%}
  mdi:fast-forward-60
  {%- endif %}
badge_color: blue
card_mod:
  style:
    .: |
      :host {
       --mush-icon-size: 45px;
       height: 50px !important;
       width: px;
      }
    mushroom-shape-icon$: |
      ha-icon {
       {{' --icon-animation: spin 2s linear infinite;'if is_state('input_boolean.ventilator_test', 'on') }}
      }
      :host {
       --mush-icon-size: 20px;
      }

**Comment by piitaya** [comment]
A fix has been proposed in this thread : https://github.com/piitaya/lovelace-mushroom/issues/1195
Also, don't forgot that Mushroom doesn't officially support card mod. I try to do my best to avoid breaking things but the more card mod you use, the more you will have issue like this.
