### ISSUE TITLE
custom element doesn’t exist

### ISSUE THREAD

**Issue by Flyer11111** [piitaya/lovelace-mushroom#1202]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Using a iphone 6 ios 12.5.7 with mushroom cards has issues checked the paths in manage resources

/hacsfiles/lovelace-mushroom/mushroom.js?hacstag=XXXXXXXXXXXXXXXXX

/local/community/lovelace-mushroom/mushroom.js

I’ve used both of these are working as when removed all other devices stop working,

All so reset frontend cache

    delete mushroom resources (https://my.home-assistant.io/redirect/lovelace_resources/)
    uninstall Mushroom from HACS
    reinstall Mushroom from HACS

google browser all so fails

occurred after last update

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome current
- HA Version: current
- Mushroom: current
- HA iphone app current reinstalled
```

**Comment by piitaya** [comment]
Did you try this https://github.com/piitaya/lovelace-mushroom#i-dont-see-the-last-changes ?

**Comment by benchristian88** [comment]
same for me on Tizen 6.0 Samsung Fridge. not sure what working version, as its a little finicky on the reload.  will rollback and see.

**Comment by Flyer11111** [comment]
Correct worked fine with old version

**Comment by ronnienijjar** [comment]
3.0.0 not working for me on older HD8 tablet thought it works on a new HD10

**Comment by Chartreusito** [comment]
Fixed the issue on Lenovo Smart Clock 2 too, thanks !

**Comment by piitaya** [comment]
Thanks for the feedback. I close the issue as it's fixed
