### ISSUE TITLE
[Feature]: Change light icon based on the light color

### ISSUE THREAD

**Issue by bzumik1** [piitaya/lovelace-mushroom#1208]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I am always lustrated when I change the color of the light but on dashboard the light of the icon stays the same.

### Describe the solution you'd like

It would be nice if the icon of light could change with the color of the light, so in case it is warm white the icon would be orange/yellow, when it is cool white it would be light blue etc. The support for RGB would be also appreciated.

### Describe alternatives you've considered

It looks like it is possible to change the color based on the light entity manually but it would be really nice if I could just select "adaptive" in GUI when I am selecting color for the light icon.
<img width="1044" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/32042186/4b30ce60-7814-4ded-892d-9e9255f5e185">

**Comment by piitaya** [comment]
The option already exists : use_light_color.
It's the first switch in the bottom left on your screenshot.

**Comment by piitaya** [comment]
I don't know that language you use, but you can edit it in the translations files : https://github.com/piitaya/lovelace-mushroom/tree/main/src/translations

**Comment by bzumik1** [comment]
Hi, I have created [PR](https://github.com/piitaya/lovelace-mushroom/pull/1213) for that, could you please check it. I have tried to follow all conventions but if I missed something please let me know.

**Comment by bzumik1** [comment]
But in my opinion it would be even better to move this option to the drop down menu on second place (after the default color) with some rainbow icon
<img width="1025" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/32042186/b098989e-bbcd-41d4-b967-cdfe51051855">
