### ISSUE TITLE
[Feature]: Remote button for media player card

### ISSUE THREAD

**Issue by dnestico** [piitaya/lovelace-mushroom#1209]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Now that the Android TV integration provides a remote for Android TVs, it would be nice if the media player card had an option for a remote button, when you click the button it would open a remote popup to control from your phone.

Finally here is a concept via the community forums, a design with these buttons similar to this would be nic but with the media player card:

<img width="463" alt="Screenshot 2023-07-11 at 8 34 30 PM" src="https://github.com/piitaya/lovelace-mushroom/assets/3034555/2d4c2842-72ff-433a-8efe-c8f9c9b09279">

### Describe the solution you'd like

A remote button in the media player card opens a Android TV remote popup, if you have a remote card installed like the one below it could use that since Home Assistant doesn't have a built-in remote UI. 

### Describe alternatives you've considered

I'm currently doing this with https://github.com/pathofleastresistor/polr-android-tv-remote-card for the popup but having it built in would be better.

<img width="432" alt="Screenshot 2023-07-11 at 8 30 57 PM" src="https://github.com/piitaya/lovelace-mushroom/assets/3034555/1661ce3a-e16c-4beb-82b1-4fc0d27f82f9"> 

### Additional context

Android TVs offer remotes via home assistant so built in control UI would be sweet.

**Comment by piitaya** [comment]
Remote are not normalized, command can be any string so it will need many configuration for users to achieve what they want. Also, Mushroom doesn't have custom dialog. I don't think we can bring this feature to Mushroom. There are some other ways to do it : using the custom card you shared with browser mod for example.
