### ISSUE TITLE
[Bug]: iPad Companion App animations no longer work after breaking changes

### ISSUE THREAD

**Issue by thecastle20** [piitaya/lovelace-mushroom#1210]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

After upgrading to the latest Mushroom (since 3.0.0, now on 3.0.3) post breaking changes icons no longer animate on the iPad companion app or other browsers (tried Safari & Firefox). The same code works fine on PC or Android. Code used is below (noting I tried changing to the code below as suggested in #1195). 

`card_mod:
      style: |
        mushroom-shape-icon {
          --icon-animation: boing 3s ease infinite;
          transform-origin: 50% 90%;
         }
         @keyframes boing {
           0% { transform: scale3d(1, 1, 1); }
           7% { transform: scale3d(1.25, 0.75, 1); }
           10% { transform: scale3d(0.75, 1.25, 1); }
           12% { transform: scale3d(1.15, 0.85, 1); }
           16% { transform: scale3d(0.95, 1.05, 1); }
           19% { transform: scale3d(1.05, 0.95, 1); }
           25% { transform: scale3d(1, 1, 1); }
         }`

Card_mod used to modify these cards:

`type: custom:vertical-stack-in-card
cards:
  - type: custom:gap-card
    height: 12
  - type: custom:mushroom-template-card
    primary: House
    icon: mdi:home
    icon_color: purple
    layout: horizontal
    tap_action:
      action: fire-dom-event
      local_conditional_card:
        action: set
        ids:
          - menu-house: show
          - menu-lights: hide
          - menu-security: hide
          - menu-system: hide
    secondary: ''
    fill_container: false`

### Expected Behavior

Icons should animate. 

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Safari 605.1.15
- HA Version: 2023.7.1
- Mushroom: 3.0.3
```

**Comment by piitaya** [comment]
There are some issues closed for this problem and it's mentioned in the 3.0.0. Also Mushroom repository doesn't provide support for card mod. It's not officially supported.

**Comment by thecastle20** [comment]
Retried with suggestion in #1195 - this does work; what doesn't seem to work is custom animations using 'keyframes'. I removed 'card_mod' and just use 'styles' for CSS styling - same issue. Cleared cache on companion app - no difference. 

Works:
```
card_mod:
  style: |
    mushroom-shape-icon {
      {{ '--icon-animation: pulse 3s linear infinite;'  }}
    }
```

Doesn't work
```
    card_mod:
      style: |
          mushroom-shape-icon {{
            --icon-animation: beat 1.3s ease-out infinite both;
          }
          @keyframes beat {
            0% { transform: scale(1); }
            10% { transform: scale(1.1); }
            17% { transform: scale(1.05); }
            33% { transform: scale(1.25); }
            60% { transform: scale(1); }
          }
```

**Comment by piitaya** [comment]
Try 
```yaml
card_mod:
  style: |
    ha-state-icon {
      animation: beat 1.3s ease-out infinite both;
    }
    @keyframes beat {
      0% { transform: scale(1); }
      10% { transform: scale(1.1); }
      17% { transform: scale(1.05); }
      33% { transform: scale(1.25); }
      60% { transform: scale(1); }
    }
```
There is an issue with Safari and css variables using keyframes with shadow dom. I think I will need to drop the support for `--icon-animation`variable because it's not needed anymore with the 3.0.0. Using `ha-state-icon` and `animation` is enough.

**Comment by thecastle20** [comment]
Many thanks Paul! This fixed the animations for me 🙂


________________________________
