### ISSUE TITLE
Wash machine card

### ISSUE THREAD

**Issue by bzumik1** [piitaya/lovelace-mushroom#1233]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

It would be great to have waschmachine card in mushroom, something like this: https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/484?u=bzumik1

### Describe the solution you'd like

Have nice wash machine card.

**Comment by piitaya** [comment]
This card contains multiple sensors. It's not planned to add something like that.
