### ISSUE TITLE
[Bug]: mushroom-chips-card seems not to use accuracy set to the entity

### ISSUE THREAD

**Issue by kpmkpm** [piitaya/lovelace-mushroom#1248]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I have set the aqara temperature sensor's accuracy to one decimal, but in mushroom-chips-card the accuracy is still two decimals.

### Expected Behavior

Sensor value to be shown with one decimal as it is shown for example in an entity card.

### Steps To Reproduce

![Screenshot 2023-09-10 at 17 24 44](https://github.com/piitaya/lovelace-mushroom/assets/55847136/b4eee188-1fd0-4462-81b3-2a0069587780)

Fridge temperature is shown with two decimals (3.22) in chips card, but in the entity card it is shown (as it should) with one decimal (3.2).

![Screenshot 2023-09-10 at 17 26 25](https://github.com/piitaya/lovelace-mushroom/assets/55847136/d1092199-2d55-4147-aca0-2bbbed5e860e)

It is the same sensor, but the temperature changed from 3.2 to 3.4 while making screenshots.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: 
Chrome, Edge, Safari

- HA Version:
Home Assistant 2023.8.4
Frontend 20230802.1 - latest

- Mushroom:
v3.1.0
```

**Comment by TLongstride** [comment]
Hi,
Seems to be a bug, but couldn't reproduce it.
If it don't work for you, you can try using template instead of entity chip

```
type: template
entity: sensor.fridge_temperature
content: '{{ states(''sensor.fridge_temperature'') | round(1) }}°C'
icon: mdi:fridge 
icon_color:green
```

**Comment by piitaya** [comment]
Hello!
The precision is not used for template by default.
You can have the rounded value by using additional parameters.

```jinja2
{{ states('sensor.temperature', rounded=True, with_unit=True) }}
```

Even the unit can be added 🙂
