### ISSUE TITLE
State value is no longer capitalized on recent versions of Home Assistant

### ISSUE THREAD

**Issue by clarinetJWD** [piitaya/lovelace-mushroom#1257]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

For "cover" cards, it will display "open", "closed", "opening", etc.

For "climate" cards, it will display "cool - 74 F", "heat - 74 F", "heat_cool - 74 F", etc.

This is with the default "state" as the secondary_info.

![image](https://github.com/piitaya/lovelace-mushroom/assets/71787034/0f948bf3-48e9-4dc9-b9ce-62955c835bb8)

### Expected Behavior

It should capitalize the text in most cases, and split on underscores to match the screenshots on the documentation.

For "cover" cards, "Open", "Closed", "Opening", etc.

For "climate" cards, "Cool - 74 F", "Heat - 74 F", "Heat Cool - 74 F" (or "Heat/Cool - 74 F"), etc.

### Steps To Reproduce

Just add the card, this occurs with default behavior.

I just updated a lot of things, so I expect that at some point, the state text used to be caps, but it's not now? Or when it switched to use default HA translations? Not sure what the cause, but I'm trying my best to not create an entirely new template just to capitalize a couple letters...

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: All Browsers (Edge, Chrome desktop, Chrome mobile, HA app on Android)
- HA Version: 2023.09.2
- Mushroom: 3.1.0
```

**Comment by piitaya** [comment]
Hum, I don't have this issue. May be some cache issue (as always 😂). Did you reinstalling mushroom?

![CleanShot 2023-09-27 at 18 06 30](https://github.com/piitaya/lovelace-mushroom/assets/5878303/ec79b76c-dc0f-49ec-a482-3524d680b2a6)
