### ISSUE TITLE
Optimize Card Light

### ISSUE THREAD

**Issue by cyrilphoenix71** [piitaya/lovelace-mushroom#126]
**Is your feature request related to a problem? Please describe.**
I this page we can see option of the Minimalist Light Card : https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_light/

**Describe the solution you'd like**
Integrate the card_light_slider_collapse and card_light_slider_horizontal options would be cool

**Comment by piitaya** [comment]
This issue already exist : https://github.com/piitaya/lovelace-mushroom/issues/34. I will close this one.

**Comment by cyrilphoenix71** [comment]
I know but minimalist is not user friendly and this only two option are interresting I thing
