### ISSUE TITLE
[Feature]: How to change color of slider by value?

### ISSUE THREAD

**Issue by Bagunda** [piitaya/lovelace-mushroom#1260]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

This work:
```
type: custom:mushroom-number-card
entity: input_number.dlia_dimmera
icon: mdi:fan
```
![image](https://github.com/piitaya/lovelace-mushroom/assets/16766521/07821a93-3a76-48f8-bb55-5cf9d0483b48)

### Describe the solution you'd like

This doesn't work:
```
type: custom:mushroom-number-card
entity: input_number.dlia_dimmera
icon: mdi:fan
icon_color: >
  {% set state=states('input_number.dlia_dimmera') | int %}
  {% if state < 30 %}
  green
  {% elif state < 70 %}
  blue
  {% else %}
  red
  {% endif %}
```
![image](https://github.com/piitaya/lovelace-mushroom/assets/16766521/d020d4f2-9ad2-47ff-9f33-a78511178f0c)

**Comment by piitaya** [comment]
Template are only supported in template card not other cards. I think it's possible to do that with card mod.
There is currently no plan to bring template to every option of every card because it will be many work and very hard to maintain.
