### ISSUE TITLE
Template card icon color picker missing

### ISSUE THREAD

**Issue by diedrichg** [piitaya/lovelace-mushroom#1263]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Template card icon color picker missing

### Expected Behavior

Template card icon color picker exists and allows selection of available colors

### Steps To Reproduce

1. Create a template card
2. Add an icon
3. Tap icon color field

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: HA Android app
- HA Version: 2023.10.3
- Mushroom: 3.1.0
```

**Comment by piitaya** [comment]
Hello, the color picker is not available in template card because all fields can be templates.
