### ISSUE TITLE
[Feature]: Select card without drop down

### ISSUE THREAD

**Issue by AINER** [piitaya/lovelace-mushroom#1268]
### Is your feature request related to a problem?

The select card is not always convenient for quickly selecting.

### Describe the solution you'd like

Add a feature to the select card to display values in full list view and scroll view with fixed height.

### Describe alternatives you've considered

That's similar to this addon - [select-list-card](https://github.com/mattieha/select-list-card), but it's old addon that is not supported and has an outdated design that doesn't fit with Mushroom cards.

**Comment by piitaya** [comment]
Mushroom controls have a fixed height (~40px) so a list like this will not fit the design. That's why it's a dropdown and not a full list. 

I don't plan to add bigger controls because I prefer to keep Mushroom simple.
