### ISSUE TITLE
[Feature]: Cover Card : Add option to have Up button first

### ISSUE THREAD

**Issue by jfchadeyron** [piitaya/lovelace-mushroom#1274]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Some alternatives (jeedom, figaro), the first button for covers is up.
The transition to Home Assistant will be easier.

### Describe the solution you'd like

In Cover Card, add an option to have Up button first

With the option disabled (by defaut), the interface :
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/2SVgQ5gK/Capture-d-e-cran-2023-10-28-a-08-37-17.png' border='0' alt='Capture-d-e-cran-2023-10-28-a-08-37-17'/></a>
With the option enabled, the interface :
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/28P7t8VJ/capture-to.png' border='0' alt='capture-to'/></a>

**Comment by piitaya** [comment]
Home Assistant tile card and entities card use up button first. I think we can change it to have the same behavior everywhere. No need to add an option for that.

**Comment by jfchadeyron** [comment]
True but twice as high...It's for this, i submit this idea. <a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/pXFbNVVL/Capture-d-e-cran-2023-10-28-a-15-10-51.png' border='0' alt='Capture-d-e-cran-2023-10-28-a-15-10-51'/></a>

**Comment by piitaya** [comment]
I opened a PR to switch the button order. It will be the same order as other HA cards.
