### ISSUE TITLE
[Bug]: URL action as hold_action not working on ios/ipados companion app

### ISSUE THREAD

**Issue by N3rdix** [piitaya/lovelace-mushroom#1276]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Mushroom cards like chips or entity card configured to perform an **URL action when long-pressing** the entity does not work any longer (maybe since ios 17 or the companion app update as it is still working in Chrome/Safari).
Configuring the URL action as tap_action still works as expected, only hold_action does not work. Other hold_action types like "navigate" still work fine.

### Expected Behavior

URL opens in browser when long-pressing the entity in the card

### Steps To Reproduce

1. Add a chip or entity card
2. configure a hold_action for it with type URL, e.g. http://1.1.1.1

### Context

YAML state
```
type: custom:mushroom-entity-card
entity: binary_sensor.xyz
hold_action:
  action: url
  url_path: http://10.10.30.11
```

### Environment

```markdown
- companion app version: 2023.471
- HA Version: 2023.9.3
- Mushroom: 3.1.0
```

### Anything else?

Example video, left entity is configured with tap_action and works correctly, right one with hold_action does not do anything. You actually can't see the click on the left entity in the video...

https://github.com/piitaya/lovelace-mushroom/assets/70015952/d73e5a57-9bc6-4cc9-ad74-467de13fbf3b

**Comment by piitaya** [comment]
Hi 👋
Mushroom uses build-it actions from Home Assistant. Also, I reproduced it with official button card. You should open an issue in HA front-end.

**Comment by N3rdix** [comment]
Thanks for looking into this, opened an issue there:
https://github.com/home-assistant/frontend/issues/18474
