### ISSUE TITLE
Bar Card

### ISSUE THREAD

**Issue by cyrilphoenix71** [piitaya/lovelace-mushroom#128]
**Is your feature request related to a problem? Please describe.**
What do you think about creat a bar card :
![image](https://user-images.githubusercontent.com/18350629/154112212-fcbcb59e-b0f3-4e9f-a40d-b954c1ae4c71.png)

Inspiration : https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_bar_card/

**Comment by piitaya** [comment]
That's not a thing we will add in mushroom but mixing text and progress bar is not very UX friendly.
Maybe we can have different chart display (progress-bar, bar chart, graph chart, etc...) 
There is already an issue for chart : https://github.com/piitaya/lovelace-mushroom/issues/74

**Comment by cyrilphoenix71** [comment]
Why not UX Friendly ?
