### ISSUE TITLE
[Bug]: v3.2.2failed to install

### ISSUE THREAD

**Issue by latel** [piitaya/lovelace-mushroom#1288]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

install failed, I was able to upgrade to v3.2.0, but when I try to upgrade to v3.2.1 and v3.2.2, it failed.
![企业微信截图_ac3b87de-ec70-4970-aa8a-a3a3a5bc9c92](https://github.com/piitaya/lovelace-mushroom/assets/5621862/0353b601-ccc3-4e52-ba52-5aef50244503)

### Expected Behavior

install successful

### Steps To Reproduce

1. Go to Ha setting, found mush room updates prompt.
    ![image](https://github.com/piitaya/lovelace-mushroom/assets/5621862/2b97d268-4841-48d4-861e-cddc28eca4ae).
2. Open prompt, click install, install percentage go to 50% from 30% initial value.
3. failed in error

### Context

YAML state
```yaml

```

### Environment

```markdown
Browser: Chrome 118.0.5993.117
HA Core: 2023.11.1
HA Supervisor: 2023.10.1
HA Frontend: 20231030.1
```

**Comment by piitaya** [comment]
It should be an issue with your installation. Have you try to restart your HA et retry?

**Comment by latel** [comment]
It works now😅
