### ISSUE TITLE
Support more-info action for template card

### ISSUE THREAD

**Issue by Hejki** [piitaya/lovelace-mushroom#129]
**Is your feature request related to a problem? Please describe.**
There is no way how to show more-info action on template-card, so it will be nice to support this action on template-card and on template-chip as well.

**Describe the solution you'd like**
I create simple solution for template-card that use first (or only) entity id from `config.entity_id` and suggest use something similar for template-chip. 

**Additional context**
There is also inconsistency between documentation of template-card tap/hold/double_tap actions and code. Default values for code is toggle, more-info and more-info but non of them works, because no entity is defined. Please also consider rename `entity_id` to `entities`, I think is more standardised names in HA.

I love this cards, nice work. 
Thanks

**Comment by antonio1475** [comment]
It's possible via code editor. Just add an entity row. This one shows me info about the home temp & thermostat, and I can tap it to open the climate.home (thermostat) settings.

But I fully agree it would be nice to have it on the visual editor.

```
type: custom:mushroom-template-card
primary: >-
  La casa está a {{ states('sensor.home_temperature') }}º y {{
  states('sensor.home_humidity')}}% de humedad
secondary: >-
  Termostato a {{ state_attr('climate.home', 'temperature') }}º ({{
  states('sensor.home_tado_mode') | title}} | {{ states('climate.home')  |
  title}} | {{ state_attr('climate.home', 'hvac_action') | title }} {{
  states('sensor.home_heating')  | title}}%)
icon: mdi:home
entity: climate.home
tap_action:
  action: more-info
```

PS/offtopic (sorry): where are template chips???

**Comment by antonio1475** [comment]
I see that while it can be done in Template card by adding the entity row as mentioned (yaml), that doesn't work for template chips.
So, template chip don't allow tap/hold actions for custom entities.

**Comment by piitaya** [comment]
It's added in the editor 🙂

**Comment by 1iverea9er** [comment]
Hi. I noticed that more-info doesn't work for chips card.
This is also not considered in the [examples](https://github.com/piitaya/lovelace-mushroom/blob/main/.hass_dev/views/chips-view.yaml).
Maybe I configured it incorrectly or such a function is not provided now?

>                   - type: template
                    icon: |
                      {% if is_state('switch.fan_l1', 'on') %}
                        mdi:valve-open
                      {% else %}
                        mdi:valve-closed
                      {% endif %}
                    icon_color: |
                      {% if is_state('switch.fan_l1', 'on') %}
                        green
                      {% else %}
                        gray
                      {% endif %}
                    tap_action:
                         action: call-service
                         service: switch.toggle
                         service_data:
                            entity_id: switch.fan_l1
                    hold_action:
                         action: more-info
                         entity: switch.fan_l1
