### ISSUE TITLE
[Feature]: Make Alarm Card display error message when entered code is invalid

### ISSUE THREAD

**Issue by adamf83** [piitaya/lovelace-mushroom#1290]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

If a user enters the incorrect alarm code, for example, when disarming the alarm, the code is simply cleared and no message to say the code was invalid is displayed.

### Describe the solution you'd like

I’d like to see the words “Invalid Code” or something similar displayed if an incorrect code is entered.

### Describe alternatives you've considered

The custom card from Alarmo has this feature, but I prefer the style of the mushroom cards, hence I’d prefer to use them.

**Comment by Laxilef** [comment]
Hi @piitaya 
Same problem. I use Alarmo and it does not allow me to arm it if any door is open. The Alarmo card at this moment displays a list of objects (sensors):
![alt text](https://github.com/nielsfaber/alarmo-card/blob/main/screenshots/alarmo-card.gif?raw=true "demonstration video")

Could you add an option to display an error message in the card? For example, we could add an "error_message" parameter (template) or something like that.

Example template:
```yaml
error_message: >
  {% if state_attr('alarm_control_panel.master', 'open_sensors') is iterable %}
  {% for value in state_attr('alarm_control_panel.master', 'open_sensors') -%}
  - {{ state_attr(value, 'friendly_name') }} ({{ area_name(value) }})
  {% endfor %}
  {% endif %}
```

Thanks!

**Comment by duczz** [comment]
Bump this Feature, i wanna switch to mushroom complete

**Comment by piitaya** [comment]
Open sensors is a custom thing from alarmo. Mushroom only supports official feature from Home Assistant so this feature will not be implemented in Mushroom.
