### ISSUE TITLE
Alarm Card disarm button doesn't work if you have a code

### ISSUE THREAD

**Issue by samtate** [piitaya/lovelace-mushroom#1291]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I have an Alarmo alarm set up with a mushroom alarm Card to control it. I can arm just fine with the mushroom card buttons as my alarm requires no code to arm, but if I then try to use the mushroom button to disarm, nothing happens. 

I understand you can make the card show a keypad when armed and this does work, but it completely ruins my layout as the card goes to 5x its size when armed

### Expected Behavior

If your alarm needs a code to disarm and you have the keypad hidden, pressing the disarm button should open a keypad in a popup so you can disarm

### Steps To Reproduce

1. Link an alarm to the mushroom alarm card that requires a pin to disarm
2. Disable alarm keypad on mushroom card so only the status and disarm button are shown when armed
3. Arm alarm
4. Press disarm button
Nothing happens

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by d0rh4ns** [comment]
perhaps this could use the same popup that the home assistant tile card uses now?

**Comment by Sinfonia97** [comment]
Not sure is I am experiencing the same issue or not, but I am no longer able to click on one of the states and either arm_home or arm_away by entering a code.  I can however click on the title button and get another popup to arm_home or arm_away.  I am also not able to click on the disarm state to get a popup to enter the code to disarm.  I am on the most recent version as of 4 days ago.

**Comment by techwolfpl** [comment]
I have this problem too. The only way to disarm the alarm is to show keyboard, but this brokes my UI.
Also I cant remove the pin, because I have NSpanel with alarm component so if I remove pin then everyone can disarm from the panel without the code.

**Comment by ncodee** [comment]
Having a similar issue here, seems like a prominent bug that still hasn't been addressed.

None of State buttons are working, with error:
```Failed to call service alarm_control_panel/alarm_arm_home. Entity alarm_control_panel.home does not support this service.```

Please could you revist this @piitaya?

**Comment by oerix** [comment]
How has this not been fixed yet? Broken for nearly a year now.

**Comment by d0rh4ns** [comment]
Do it yourself if you have an issue with the development speed. Remember that this is a free piece of software. People tend to focus on what pays their bills and rightfully so. Any development on this at all is nothing but an amazing service to the community!

-------- Original Message --------
