### ISSUE TITLE
[Bug]: Climate card always displays "heating"

### ISSUE THREAD

**Issue by milelo** [piitaya/lovelace-mushroom#1292]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

The climate card always displays "Heating" even when the target temperature has been reached, the heater is off and the climate entity is reporting the state "Idle" as displayed in the standard UI.
My climate definition is:
climate:
  - platform: generic_thermostat
    name: HVAC
    heater: switch.boiler_on_off
    target_sensor: sensor.selected_temperature_sensor
    min_temp: 6
    max_temp: 22
    ac_mode: false
    target_temp: 6
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat"
    home_temp: 18
    away_temp: 6
    precision: 0.5

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:Chrome
- HA Version:
- Mushroom:3.2.2
Home Assistant 2023.11.2
Supervisor 2023.11.0
Operating System 10.1
Frontend 20231005.0 - latest
```

### Anything else?

<img width="311" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/156290/4d8bfc63-dfff-4e41-acc6-d764a006e029">
<img width="304" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/156290/f35c1a7e-0c61-4211-95d4-d45682bbab21">

**Comment by piitaya** [comment]
What's the configuration of your card?
It looks like you set the name "heating" in the card. The action "heating or idle" is represented by the badge on climate card.

**Comment by milelo** [comment]
Good call. Thanks for looking at this.
