### ISSUE TITLE
Feature request: Sliders for multiple attributes per card

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [piitaya/lovelace-mushroom#1293]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Would sometimes prefer to be able to adjust multiple attributes quickly, rather than jumping back and forth (ie adjusting colour temp & brightness of lights).  Also, makes it less obscure / easier to use for people not used to the system (visitors, elderly, etc).

### Describe the solution you'd like

Hi,

I think it would be fabulous if this could have the option to show multiple attribute sliders per card, rather than switching.

For instance, a light could have sliders for both brightness and colour temperature; a cover could have sliders for percent open and slat angle; etc etc.

Would this be possible?

**Comment by piitaya** [comment]
Something like this?
![CleanShot 2023-11-16 at 20 27 39@2x](https://github.com/piitaya/lovelace-mushroom/assets/5878303/fc011062-c91f-461b-b77f-d2c6424fbf61)

You can use [tile card](https://www.home-assistant.io/dashboards/tile/) for this.

```yaml
type: tile
entity: light.bed_light
features:
  - type: light-brightness
  - type: light-color-temp
```

**Comment by TheOriginalMrWolf** [comment]
Ooo.  Noice!  Thank you :)
