### ISSUE TITLE
[Bug]: Spacing when not square

### ISSUE THREAD

**Issue by FilipeOS** [piitaya/lovelace-mushroom#1317]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Right now when the row is not set to square there's a big gap bellow

![Screenshot_20231226_085115_Home Assistant](https://github.com/piitaya/lovelace-mushroom/assets/18313286/fb190655-ae07-4a68-9911-6c47d066fc5c)

### Expected Behavior

Don't have spacing

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version: 11.2
- Mushroom: 3.2.2
Hacs 1.33.0
```

**Comment by piitaya** [comment]
Can you share you configuration? It looks like a configuration problem with grid card.
