### ISSUE TITLE
Badge icon not appear climate-card

### ISSUE THREAD

**Issue by HAlover99** [piitaya/lovelace-mushroom#1319]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Badge icon not appear

### Expected Behavior

Badge icon appear

### Steps To Reproduce

I'm tried to use climate card an work fine, only issue are badge icon, for example if turn on heat function not appear the badge icon.
The issue is the same for all state, dry,cool ecc

### Context

```
- type: custom:mushroom-climate-card
    entity: climate.fujitsu
    name: Condizionatore
    show_temperature_control: true
    hvac_modes:
      - heat_cool
      - heat
      - cool
      - fan_only
      - dry
    card_mod:
      style: |
        mushroom-shape-icon {
          --card-mod-icon: 
          {% if is_state(config.entity, 'heat_cool') %}
            mdi:autorenew
          {% elif is_state(config.entity, 'heat') %}
            mdi:fire
          {% elif is_state(config.entity, 'cool') %}
            mdi:snowflake
          {% elif is_state(config.entity, 'dry') %}
            mdi:water-percent
          {% elif is_state(config.entity, 'fan_only') %}
            mdi:fan
          {% else %}
            mdi:air-conditioner 
          {% endif %};
          display: flex;
          {% if is_state(config.entity, 'fan_only') %}
            animation: rotation 1s linear infinite;
          {% endif %}
        }
        @keyframes rotation {
          100% {
             transform: rotate(360deg);
          }
        }
```

![image](https://github.com/piitaya/lovelace-mushroom/assets/16383417/0e10defe-af59-433b-b86c-e6b74252acfd)

### Environment

```markdown
- Browser: chrome edge and direct by app
- HA Version: 2023.12.1
- Mushroom: 3.2.2
```

**Comment by piitaya** [comment]
Why are you trying to override the icon of the climate card? This card handle the icon automatically. Also, support for card mod is not provided in this repository (see: https://github.com/piitaya/lovelace-mushroom/issues/1366)
