### ISSUE TITLE
[Bug]: How to change the color of an icon on a chip card

### ISSUE THREAD

**Issue by JustinTomerlin** [piitaya/lovelace-mushroom#1320]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

How to change the color of an icon on a chip card

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by scottsuch** [comment]
Using template cards you can use if logic in the yaml like so...
```
{% if is_state(entity, 'on') %}
  mdi:lightbulb-on
{% else %}
  mdi:lightbulb-outline
{% endif %}
```
I've used similar logic for the icon, inforration, color, etc.
