### ISSUE TITLE
[Bug]: Slider for light dimmer not visible on Edge

### ISSUE THREAD

**Issue by Michail71** [piitaya/lovelace-mushroom#1336]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I have a new install of Mushroom and I can't see the slider for the dimmer in the Web browser.  No customizations have been made. Color and temperature sliders are visible. 

The slider displays okay on the app and Chrome.  I tried deleting cache using the developer tools. 

I can still interact with the slider, it's just not visible. 

<img width="388" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/59095417/077e9d67-275c-481f-864d-0a600129da67">

### Steps To Reproduce

1. Add light card
2. Turn on Brightness, Temperature, and Color Control
3. Save
4. View on Edge web browser. 

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Edge
- HA Version: 2024.1.3
- Mushroom: 3.2.4
```

**Comment by maxakash** [comment]
Did you solve it?

**Comment by Michail71** [comment]
> Did you solve it?

I just switched to Chrome for a bit, but I think it resolved on its own.  Perhaps it was an Edge update? 

Thanks for the follow up!
