### ISSUE TITLE
[Feature]: Keetle card

### ISSUE THREAD

**Issue by ganjakyp-hub** [piitaya/lovelace-mushroom#1343]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Manage kettle in a common style

### Describe the solution you'd like

Kettle card in a common Mushroom style

**Comment by piitaya** [comment]
Kettle is not a home assistant entity so Mushroom can not provide support for that.
