### ISSUE TITLE
[Bug]: Mushroom not properly installed anymore when upgrading to 3.4.0

### ISSUE THREAD

**Issue by Igor01-Tech** [piitaya/lovelace-mushroom#1350]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

None of the Mushroom lovelace elements are found anymore. I restarted the whole system. But this is how it looks now:
![image](https://github.com/piitaya/lovelace-mushroom/assets/61701217/4b91881b-b6e4-4372-9cbb-53c244add09f)
Everything was finde before the update to 3.4.0.

There are no Mushroom elements installed anymore:
![image](https://github.com/piitaya/lovelace-mushroom/assets/61701217/6cc2acff-ddc4-425d-a40d-33e53fc89e17)

This is shown inside Lovelace-Ressources:
![image](https://github.com/piitaya/lovelace-mushroom/assets/61701217/132bafac-99aa-4512-a726-534ff2327890)

### Expected Behavior

I would expect everything to work like before..

### Steps To Reproduce

I even reinstalled mushroom. But its still not shown anywhere

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome Version 121.0.6167.86 (Offizieller Build) (64-Bit)
- Mushroom: 3.4.0

Home Assistant:
Core
2024.1.6
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0
```

**Comment by sebking1971** [comment]
same here have just reverted

**Comment by mariosemes** [comment]
Same as OP. Reinstalling multiple times, rebooting, nothing worked. Reverted back to 3.3.0.

**Comment by piitaya** [comment]
Hello 👋 If the card doesn't appear, it's because the Mushroom code is not loaded,
It's certainly a cache issue or a misconfiguration of ressources. Try to clear it even you already did it : https://github.com/piitaya/lovelace-mushroom?tab=readme-ov-file#i-dont-see-the-last-changes.

**Comment by Igor01-Tech** [comment]
I removed mushroom from ressources and after that updated mushroom from V3.3.0 to the latest and it worked right away. @piitaya Thanks a bunch!! <3
