### ISSUE TITLE
[Bug]: Custom element doesn't exist: mushroom-light-card.

### ISSUE THREAD

**Issue by rightsaidfred99** [piitaya/lovelace-mushroom#1361]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

After 3.4.1 Mushroom card entities refuse to load

### Steps To Reproduce

Update to 3.4.1 on 2024.1.6

### Context

type: custom:mushroom-light-card
entity: light.bedroom_k_lights
fill_container: false
show_brightness_control: true
use_light_color: true
show_color_temp_control: true
collapsible_controls: true

Custom element not found even though it's loaded

### Environment

```markdown
- Browser:All
- HA Version: 2024.1.6
- Mushroom:3.4.1
```

**Comment by piitaya** [comment]
Hello 👋 It's certainly a cache issue. Try to clear it : https://github.com/piitaya/lovelace-mushroom?tab=readme-ov-file#i-dont-see-the-last-changes
