### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by juscode** [piitaya/lovelace-mushroom#1363]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Climate card no longer displaying HVAC control icons i.e. Off, Heat, Cool Etc after recent update

### Expected Behavior

Should show icons

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by piitaya** [comment]
Hello. Did you try to clean your cache ? It looks like you didn't have the latest Mushroom version because this issue is fixed with [4.3.1 version](https://github.com/piitaya/lovelace-mushroom/releases/tag/v4.3.1).
