### ISSUE TITLE
Icons are missing in Mushroom card with Home Assistant 2024.2

### ISSUE THREAD

**Issue by whyyouhateme** [piitaya/lovelace-mushroom#1368]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Missing icons on almost all cards after upgrading to 2024.2.0. I installed the latest Mushroom update, it didn't help. Some cards help to assign the icon manually, but when reset to default again disappears. 

UPDATE 
Icons do not work only when connected directly. They appear when connecting through a domain with SSL certificate.
I cleaned cookies and cache for direct connection, it didn't help.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:Chrome
- HA Version: 2024.2.0
- Mushroom: 3.4.2
```

**Comment by RubenKremer** [comment]
Same issue. But for me the it also occurs with a valid SSL certificate. Must be related the the fact that they changed the way icons are handled in HASS 2024.2  (ref. [Home Assistant 2024.2 Release Notes / Blog](https://www.home-assistant.io/blog/2024/02/07/release-20242/#icons-everywhere) )

**Comment by orangelizard** [comment]
Sadly another here.

**Comment by piitaya** [comment]
It's a cache issue. Mushroom has been updated to support the new home assistant logic with 3.4.0 release.
Follow this guide to make sure your cache is refreshed : https://github.com/piitaya/lovelace-mushroom?tab=readme-ov-file#i-dont-see-the-last-changes. You can also clear the cache of your app (iOS or Android).
Also, you are using Cloudflare to access to your instance, you can have additional cache to clear on Cloudflare.

**Comment by orywig** [comment]
Same issue here - will try the above fix. Thanks!

![image](https://github.com/piitaya/lovelace-mushroom/assets/37427108/e7b1fc10-48a3-4de6-9a17-02a9aac37fa3)

**Comment by chrjsorg** [comment]
Web worked right away, the Android app was missing some icons. What helped me: Force close the entire app (in app info, not just app switcher), restart HomeAssistant in the meantime, start app again, everything is back :)

**Comment by lxe** [comment]
I'm seeing this as well even after restarting HA.

**Comment by MikeDeltaHH** [comment]
@piitaya:
 I have the problem on three mobile devices - on my iPhone using the HA app and on two Fire HD tablets using the Fully Kiosk browser. I have already restarted Home Assistant and completely restarted the mobile devices without success. There are no problems using the browser on PCs or the browser on the iPhone... as I can only clear the cache of websites on the devices, I'm at a bit of a loss as to what else I can try apart from completely reinstalling the apps on the mobile devices...

**Comment by user34756361233** [comment]
My icons returned after deinstalling and installing Mushroomcards. Clearing cache had no result on Mac/IOS/Nest Hub.

**Comment by Turton** [comment]
A simple HACS 'Redownload' of Mushroom from my Android device, resolved the issue for me.

**Comment by lukx** [comment]
Hi,
Redownload did not work for me, neither did the remove/uninstall/reinstall-Steps that are outlined in the Manual. Clearing browser Cache apparently did not work either, although I fail to understand why.

However. what worked for me is
- open https://<my-ha-url>/hacsfiles/lovelace-mushroom/mushroom.js
- refresh hitting Ctrl+Shift+R so that my browser gets the newest version
Then everything worked.

**Comment by rubin110** [comment]
So I think I'm hitting this issue too, and have been for the last month or so. Approximately one out of ten reloads will cause some (not all) svg icons do not display from various Mushroom cards. I _think_ which icons are consistent. I've tried the following without seeing any changes to this issue I'm hitting:

- Removed and reinstall Mushroom through HACS
- Removed a slew of other HACS
- Forced a refresh of `mushroom.js`
- Cleared cache in Chrome, ctrl-shift-r and by opening up the debugger and right clicking on the reload button
- Started a fresh Chrome session with no prior cache `/usr/bin/google-chrome --user-data-dir=/tmp/google-chrome-$(date +'%s')`
- Used Chrome Beta
- Used Chromium
- Used Firefox
- Cleared all data to the Android app

After all of these I still see icons missing after a few reloads. There is absolutely nothing in the debugger 

Firefox 123.0:
![image](https://github.com/piitaya/lovelace-mushroom/assets/222551/ae2ede01-a967-44af-b409-ee4c5a17ce66)

Chrome Stable 122.0.6261.94 fresh user profile:
![image](https://github.com/piitaya/lovelace-mushroom/assets/222551/3f1bee27-fc6f-40fd-8910-c9500cdb4bd4)

**Comment by Scheus** [comment]
FYI, for me the problem also seemed to be the HACS Mushroom (--Better-Sliders). I tried for a long time to solve the problem with this addon enabled but since I removed this addon I haven't been able to reproduce the problem.
