### ISSUE TITLE
[Bug]: Space in climate card

### ISSUE THREAD

**Issue by msaphoto06** [piitaya/lovelace-mushroom#1369]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Good morning The spacing between primary and secondary does not work correctly with the climate map.
![Screenshot_20240208_202627_Home Assistant](https://github.com/piitaya/lovelace-mushroom/assets/79517010/fe4922f4-e62b-4162-b99d-60483b0e087a)

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: all
- HA Version: last
- Mushroom: last
```

**Comment by msaphoto06** [comment]
@piitaya 

No Card_Mod in card Climate!
Same with original theme!
Thank
![Screenshot_20240209_061251_Home Assistant](https://github.com/piitaya/lovelace-mushroom/assets/79517010/4221e41c-88d6-48e5-9f22-eb7d39e8507c)
![Screenshot_20240209_061228_Home Assistant~2](https://github.com/piitaya/lovelace-mushroom/assets/79517010/c2713bd6-8c5c-4fff-9044-5e010ad9e0bb)

**Comment by piitaya** [comment]
I can not reproduce it 😢
What browser are you using? I'm on Safari on iOS. Ca. You try with another browser or can you try to put a climate card on a different dashboard? 

The last card is a Mushroom climate card on my screenshot. 
![image](https://github.com/piitaya/lovelace-mushroom/assets/5878303/3e5cbc64-db99-46d0-82a4-0047e20484b8)

**Comment by msaphoto06** [comment]
In my chrome broser on android
![Screenshot_20240209_100555_Chrome](https://github.com/piitaya/lovelace-mushroom/assets/79517010/1a193ba0-8e1b-404d-aae9-4100c3c1b13f)

**Comment by msaphoto06** [comment]
It s ok.
I m delete card and new card. Ok
