### ISSUE TITLE
[Bug]: Icons not defaulting when using HA companion on Android phones

### ISSUE THREAD

**Issue by DravenSA** [piitaya/lovelace-mushroom#1374]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

On desktop through browsers, the icons acta as they should, but on the HA companion App the icons are just not there.

### Expected Behavior

I expect the icons to show in the companion app

### Steps To Reproduce

1. Install companion app
2. use a mushroom entity card
3. see that icon will not display unless actually selected in the entity properties.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: HA Companion app
- HA Version: 2024.2.1
- Mushroom: v3.4.2
```

**Comment by rdeneer** [comment]
Same issue here. For me it fails to display default icons on every platform (browser and app). This started when I updated HA to 2024.2.1.

**Comment by piitaya** [comment]
It's the same as https://github.com/piitaya/lovelace-mushroom/issues/1368, right?

**Comment by rdeneer** [comment]
Correct, fixed by reinstalling and clearing cache!
