### ISSUE TITLE
[Bug]: Extremly Slow and Stuck

### ISSUE THREAD

**Issue by milandzuris** [piitaya/lovelace-mushroom#1382]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

HA: 2024.2+
Logs: Clear
Cache: clear
Chrome
Same problem on Phones

From new Update HA 2024.2+ every Card where is Customized with Card Mod extremly slow load i mean few seconds 5-20, i dont know is this problem in Card Mod or Mushroom, or after few minutes Dashboard it gets stuck and freezes

**Comment by milandzuris** [comment]
https://github.com/thomasloven/lovelace-card-mod/issues/359

**Comment by piitaya** [comment]
I'll close this issue as it's card mod related. See https://github.com/piitaya/lovelace-mushroom/issues/1366
