### ISSUE TITLE
[Bug]: 2024.3 Different card width on different devices

### ISSUE THREAD

**Issue by paull27** [piitaya/lovelace-mushroom#1389]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Not sure if it is a HA or Mushroom error, but I have two cards in the new "sections" dashboard, a Mushroom template card (Internet) and a HA tile card (CPU temp).

On my desktop they are next to each other:
<img width="505" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/109389777/df61155f-a789-4a5d-9f3c-ece624aae460">

But on my phone the template card is wider:
<img width="505" src="https://github.com/piitaya/lovelace-mushroom/assets/109389777/32f7b633-2e01-41b9-96e2-5aab9b194230">

I tried changing the "fill container" parameter, but it has no effect. Layout is "default layout". With "horizontal" it is two columns wide on both devices and with "vertical" it looks like this on desktop:
<img width="487" src="https://github.com/piitaya/lovelace-mushroom/assets/109389777/58a79bdb-d496-4d1a-bbcc-c34b5765ea1c">

and on mobile:
<img width="487" src="https://github.com/piitaya/lovelace-mushroom/assets/109389777/c8bcfd4c-e67c-4f93-bb88-35aa0e1ed677">

### Expected Behavior

The template card should be the same size as the HA tile card, in this case only one column wide, on both devices.

### Steps To Reproduce

Configure a "sections" dashboard with one tile card and one mushroom template card in a section

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Safari on Desktop, HA App on iOS
- HA Version: 2024.3
- Mushroom: 3.5.2
```

**Comment by piitaya** [comment]
Your phone doesn't have the latest version of mushroom, clean your cache, it should work : https://github.com/piitaya/lovelace-mushroom?tab=readme-ov-file#i-dont-see-the-last-changes

You can also try to clear your app cache using the app setting > debug > clear frontend cache.
