### ISSUE TITLE
[Bug]: custom:mushroom-cover-card does not exist after upgrade to V3.6.0

### ISSUE THREAD

**Issue by koenraadhaedens** [piitaya/lovelace-mushroom#1440]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by piitaya** [comment]
Hi 👋 Please uninstall and reinstall Mushroom by following the [troubleshooting instruction](https://github.com/piitaya/lovelace-mushroom?tab=readme-ov-file#i-dont-see-the-last-changes). I can not reproduce your issue and in most cases, it's a cache issue. Reinstalling the card will fix the issue.

**Comment by koenraadhaedens** [comment]
I did try this several times but it did not work, have installed the previous version and now it is working again

**Comment by piitaya** [comment]
Can you provide a screenshot of what you have on this page : https://my.home-assistant.io/redirect/lovelace_resources/

**Comment by koenraadhaedens** [comment]
Just updated to version v3.6.1 and all looks good now.
Not sure why the other one did not work.

You can close the issue.

Thank you very much for the folluw-up

Koenraad


________________________________
