### ISSUE TITLE
[Feature]: Vertical Light slider

### ISSUE THREAD

**Issue by dabucz** [piitaya/lovelace-mushroom#1451]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

There isnt any option to have vertical slider in light card

### Describe the solution you'd like

It would be great if there was a option to have the slider vertical so that for example you could change the brightness by dragging the slider from bottom to top

**Comment by piitaya** [comment]
Mushroom card are designed to present an icon, a title, a text and additional controls. Vertical sliders will not fit the current design.
