### ISSUE TITLE
[Bug]: Light Card space when is collapsed

### ISSUE THREAD

**Issue by joelmora** [piitaya/lovelace-mushroom#1455]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

I got a Light Card with these configuration:

Color control = On
Collapse controls when off

![image](https://github.com/piitaya/lovelace-mushroom/assets/11574884/b43a9d85-fed3-403f-8ba2-f419eb24f5e0)

The preview card looks and works fine but when you put it inside the UI it will expand its height showing an empty space at the bottom:

![Screenshot 2024-06-19 at 10 07 24](https://github.com/piitaya/lovelace-mushroom/assets/11574884/4b442363-7541-4edf-ba7f-e430d97dd21c)

It has something to do with its height, if `height: auto` will work fine, but currently it's conflicting with another css:

![Screenshot 2024-06-19 at 10 11 15](https://github.com/piitaya/lovelace-mushroom/assets/11574884/39543357-c130-4f6e-8a51-1447dba4c4cd)

![Screenshot 2024-06-19 at 10 12 37](https://github.com/piitaya/lovelace-mushroom/assets/11574884/b678beb2-8506-4e9a-bead-b92961a6b7fe)

### Expected Behavior

The Light card will collapse when is off not leaving any space at the bottom if used on a card

### Steps To Reproduce

1. Create a Light Card with `Color control = On` and `Collapse controls when off`
2. Put it on a UI section
3. Turn off the light

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome Version 126.0.6478.61
- HA Version: 2024.5.4
- Mushroom: 3.6.2
```

**Comment by FlyGuye10** [comment]
I'm having this issue too suddenly today. How can we fix this?

**Comment by benyaming** [comment]
+1, same issue
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/da554e34-3bc6-4881-8aca-8527bbf61878">
