### ISSUE TITLE
[Bug]: chips card has too much padding on experimental sections view

### ISSUE THREAD

**Issue by ministryofsillywalks** [piitaya/lovelace-mushroom#1456]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

When using the sections view chips cards leave much more padding space to the next card.

Sections:
![Screenshot_20240626-143150~2](https://github.com/piitaya/lovelace-mushroom/assets/10544895/a8c738f1-fbe4-4890-9b87-22871d822165)

Masonry:
![Screenshot_20240626-143157~2](https://github.com/piitaya/lovelace-mushroom/assets/10544895/d4279bea-9b5c-45ef-a71a-815f16a170eb)

### Expected Behavior

Have the same padding as in masonry.

### Steps To Reproduce

Add a sections dashboard 
Add chips cards

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome/Mobile App
- HA Version:2024.6.3
- Mushroom:3.6.2
```

**Comment by piitaya** [comment]
Section has a minimal height per row so we can not fix this on the Mushroom side. For now, you can use a vertical stack as a quick fix.
