### ISSUE TITLE
[Bug]: Title Card  misaligned in Section

### ISSUE THREAD

**Issue by geeForceOne** [piitaya/lovelace-mushroom#1463]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

If Title Card is used in Sections (Section is max 1 column) and the Layout is set to 1x2 the Subtitle is misaligned.

![image](https://github.com/piitaya/lovelace-mushroom/assets/1780268/6a95d628-78a4-465b-b663-b2442961b4de)

![image](https://github.com/piitaya/lovelace-mushroom/assets/1780268/b7d70836-ffd2-416a-af51-eb5469a4023e)

![image](https://github.com/piitaya/lovelace-mushroom/assets/1780268/a454fb7b-f42e-44cc-8d9c-c01889f310ff)

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Edge
- HA Version: 2024.7.1
- Mushroom: 3.6.3
```

**Comment by piitaya** [comment]
You should increase the height of the card or reset to default.
You can also try with this yaml configuration :
```yaml
grid_rows: auto
grid_columns: 2
```

**Comment by geeForceOne** [comment]
awesome! grid_rows: auto did the job.
Many thanks!
