### ISSUE TITLE
After recent update the alarm card dont show the keypad

### ISSUE THREAD

**Issue by gitlaman** [piitaya/lovelace-mushroom#1469]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

As the title says the alarm card lost the keypad, tried readding but its the same, the normal alarm card from lovelace has the keypad

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version: 2024.7.1
- Mushroom: 3.6.3
```

**Comment by piitaya** [comment]
Since 3.6.0, the keypad is not displayed anymore as it now use a pin code dialog to ask for the code if needed. More info here : https://github.com/piitaya/lovelace-mushroom/releases/tag/v3.6.0

**Comment by gitlaman** [comment]
Didn't saw that... Thanks for the info.
