### ISSUE TITLE
[Feature]: Marquee effect

### ISSUE THREAD

**Issue by JensRudolph** [piitaya/lovelace-mushroom#1470]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I cant see my long names, if the card is too small for it.

### Describe the solution you'd like

I would like to have a text scrolling effect, also called marquee, that enables me to read the full name as it scrolls.

**Comment by piitaya** [comment]
You can configure the name for each card if it's too long. Also, ellipsis is used for long text instead of marquee because most Home Assistant cards do that and I prefer to stay as close as possible as Home Assistant design.
