### ISSUE TITLE
[Bug]: Custom Element doen't exist

### ISSUE THREAD

**Issue by scns** [piitaya/lovelace-mushroom#1480]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

When i install version 4.0.0 the cards no longer load

### Expected Behavior

loaded cards. 

### Steps To Reproduce

1. install version 4.0

### Context

one of them:

YAML state
```yaml
type: custom:mushroom-template-card
entity: sensor.afvalinfo_home_pbd
primary: PMD
secondary: >-
  {% if states('sensor.afvalinfo_home_trash_type_tomorrow') == "Geen" %}

  Geen informatie

  {% elif states('sensor.afvalinfo_home_trash_type_today') == "pdb" %} Vandaag
  geweest. Kliko weer ophalen! 

  {% else %}
    {% set papier = (strptime(states(entity), '%d-%m-%Y').date()) %} 
    {% set delta = (papier - now().date()).days %}
    {% if states(entity) == "Geen" %}Geen informatie 
    {% elif delta < 0.9 %}Vanavond kliko aan de straat! 
    {% elif delta < 1.9 %}Morgen ({{states(entity)}}) 
    {% else %}Over {{delta | round(0)}} dagen ({{as_timestamp(papier) | timestamp_custom("%A %d-%m")}})
    {% endif %}
  {% endif %}
icon: mdi:recycle
icon_color: blue
multiline_secondary: true
```

### Environment

```markdown
- Browser: edge / chrome
- HA Version: 2024.7.4
- Mushroom: 4.0.0
```

### Anything else?

re-install 3.6.4 solves the problem
![image](https://github.com/user-attachments/assets/1281f548-db14-4aa8-aa82-fe98609d182c)

**Comment by jongbj1972** [comment]
I have the same problem.

**Comment by geoffbern** [comment]
I have the same issue and going back to 3.6.4 did not fix the issue

**Comment by gpf2ez** [comment]
Same issue has happened to me after updating to 4.0.0. Reverting back to 3.6.4 has not worked for me yet.

**Comment by gpf2ez** [comment]
> Same issue has happened to me after updating to 4.0.0. Reverting back to 3.6.4 has not worked for me yet.

I had to manually set the resource again and not my mushroom cards are working with 3.6.4


Add reference to mushroom.js in Dashboard. There's two way to do that:

    Using UI: Settings → Dashboards → More Options icon → Resources → Add Resource → Set Url as /local/mushroom.js → Set Resource type as JavaScript Module. Note: If you do not see the Resources menu, you will need to enable Advanced Mode in your User Profile

**Comment by michaelmikelas** [comment]
Upgrading to 4.0.0 via HACS doesn't seem to pull down/install the mushroom.js appropriately (I don't see it in the appropriate directory) and the resource reference URL then includes "null" where mushroom.js should be - /hacsfiles/lovelace-mushroom/null?hacstag=444350375361.  If you then remove 4.0.0 and install 3.6.4, the resource reference above wasn't updated, so I went back and replaced null with mushroom.js and all is working again just like the post above...  I'll try 4.x again in a few days to see if this all gets resolved.

**Comment by jongbj1972** [comment]
Apperantly it is caused by an incompatibility between HA 2024.7 and Mushroom 4.x.x
It now states that Mushroom 4.x.x should not be installed unless you have HA 2024.8

**Comment by scns** [comment]
With the upgrade to 2024.8 and the update van Mushroom to 4.0.2 the problem is solved. I will close this ticket.
