### ISSUE TITLE
3.6.4 update to 4.0.1 you must have a version of HA witch is not released

### ISSUE THREAD

**Issue by concierge-at** [piitaya/lovelace-mushroom#1485]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

the update 4.0.1 ist not possible to install at the core of 

Core 2024.7.4
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

errormassage my homeassistant is to old!

### Expected Behavior

fix before release!

### Steps To Reproduce

Core 2024.7.4
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by deemazz** [comment]
mine too... just reinstalled to the latest 2024.7.4 and mushroom requires at least 2024.8.0b0

**Comment by concierge-at** [comment]
corret yes
![mushroom-errer](https://github.com/user-attachments/assets/9ebbdada-cdef-4010-8e13-8427b9fe491e)

**Comment by piitaya** [comment]
2024.8 is the current Home Assistant beta version. It will be released Wednesday 🙂.

**Comment by piitaya** [comment]
It's fixed with `4.0.2`. The latest version is now compatible with both HA `2024.8` and HA `2024.7`.
