### ISSUE TITLE
[Bug]: Update shown when system requirements are not met

### ISSUE THREAD

**Issue by dhover** [piitaya/lovelace-mushroom#1487]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Version 4.01 on 2024.7.4 is shown but cannot be installed. Pressing "Install" produces an error "This version requires Home Assistant 2027.8.0b0 or newer"

### Expected Behavior

Don't show update 4.01 for versions lower than the requirements

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:2024.7.4
- Mushroom: 4.0.0
```

**Comment by ELKER54** [comment]
Also having this, also on the same versions of each

**Comment by abard35** [comment]
Same issue with 
Core 2024.7.4
upgrade from v4.0.0

**Comment by piitaya** [comment]
2024.8 is the current Home Assistant beta version. It will be released Wednesday 🙂

**Comment by dhover** [comment]
I understand that.
I want to make a point about the fact that the update is shown but the requirements are not met.

**Comment by piitaya** [comment]
It's how HACS works. If an update is available, it will be shown.

**Comment by dhover** [comment]
Ok, clear. Thanks

**Comment by piitaya** [comment]
It's fixed with `4.0.2`. The latest version is now compatible with both HA `2024.8` and HA `2024.7`.
