### ISSUE TITLE
[Feature]: Stop releasing version before Home Assistant

### ISSUE THREAD

**Issue by sebastienserre** [piitaya/lovelace-mushroom#1489]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

My HA 2024.7.4 is notifying me about a mushroom update 4.0.2 which seems not compatible with my HA version... 
Why releasing it?

### Describe the solution you'd like

I would like to be notified only for installable version.

**Comment by concierge-at** [comment]
wer veröffentlicht ein addonupdate für eine betaversion? ganz frisch kann der in der birne nicht sein

**Comment by piitaya** [comment]
The 4.0.2 is compatible with Home Assistant 2024.7.4 and 2024.8 beta. You should not have a problem to install it. I'm using 4.0.2 version with Home Assistant 2024.7.4.

**Comment by sebastienserre** [comment]
I shouldn't is a great news.... but I have an error message at the bottom of the screen...
https://www.loom.com/share/56855b64af9a440aa7d52ffa76585c3e

**Comment by piitaya** [comment]
Try restarting your HA instance or reload mushroom information from hacs panel.

**Comment by sebastienserre** [comment]
Reloading the information from HACS panel has fixed. 
I've successfully updated. Thanks for your job.
