### ISSUE TITLE
[Bug]: Card padding broken with HA 2024.8

### ISSUE THREAD

**Issue by thisistotallyshaun** [piitaya/lovelace-mushroom#1490]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

The padding on Mushroom cards (between the elements and the edge of the card) has roughly halved after upgrading to Home Assistant 2024.8. It looks quite bad. How can we get the previous level of padding back?

### Expected Behavior

Padding as per HA 2024.7

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Firefox
- HA Version: 2024.8
- Mushroom: 4.0.2
```

**Comment by mikedrawback** [comment]
The latest update made my stack-in-cards misaligned. The number controls on this used to be centered:
![image](https://github.com/user-attachments/assets/9508a4aa-58df-4312-9157-2433ebfe02d8)

**Comment by niekniek89** [comment]
For me the same issues with stack-in-cards.
Temporarily downgraded to v3.6.4 solves my problem.

**Comment by nima-1102** [comment]
The same problem also exists with the "[Restriction Card](https://github.com/iantrich/restriction-card)" after the update.

**Comment by wneessen** [comment]
This is probably related:
![image](https://github.com/user-attachments/assets/85f727d6-e2b6-46f4-879a-842df9723bc7)

Since the last update, the small cards are not showing the icons centered anymore.

**Comment by wtmh** [comment]
Here's the issue on my side.

![image](https://github.com/user-attachments/assets/ad57b5c7-1413-4bc4-933d-8faeceff96cd)

**Comment by Test-subj** [comment]
Mine is mainly wonky if I tell it not to display the name in the card. It looks fine if I set the name to a single space though.
![image](https://github.com/user-attachments/assets/415775a9-46a5-4822-b381-fc906ef2d909)
![image](https://github.com/user-attachments/assets/690d6b7a-5346-441b-a720-75c1c85fcf59)
