### ISSUE TITLE
[Bug]: Cards overlap in HomeAssistant 2024.8.0

### ISSUE THREAD

**Issue by jjavin** [piitaya/lovelace-mushroom#1493]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

With the latest version of HomeAssistant the cards are placed on top of each other as shown in the screenshot below

### Steps To Reproduce

1. Home Assistant 2024.8.0
type: custom:mushroom-light-card
entity: light.centro
name: Centro
use_light_color: false
show_brightness_control: true
show_color_temp_control: false
show_color_control: false
collapsible_controls: true
layout_options:
  grid_columns: 2
  grid_rows: 1

### Context

type: custom:mushroom-light-card
entity: light.centro
name: Centro
use_light_color: false
show_brightness_control: true
show_color_temp_control: false
show_color_control: false
collapsible_controls: true
layout_options:
  grid_columns: 2
  grid_rows: 1

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

### Anything else?

<img width="351" alt="Captura de pantalla 2024-08-08 a las 12 22 14" src="https://github.com/user-attachments/assets/092ceb40-8bf0-40b0-8e7a-0fe5e04c11ef">

**Comment by piitaya** [comment]
Why did you put `grid_rows: 1` on your card? You should put `grid_rows: 2` or remove this line if you want no overlap. The card is designed to use 2 grid rows.

**Comment by anhnvme** [comment]
> Why did you put `grid_rows: 1` on your card? You should put `grid_rows: 2` or remove this line if you want no overlap. The card is designed to use 2 grid rows.

some card have function hide when inactive. I have same issue
