### ISSUE TITLE
[Bug]: command not visible in visual editor

### ISSUE THREAD

**Issue by nbai777** [piitaya/lovelace-mushroom#1502]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

After updating from one of the 3.6 version previously created template card if it has action "send command" both for remote and for vacuum under "command" line if there was data there it is no longer visible in editor, also unable to edit or add a new data on this card (not saved).  I'm able to send the command when pressing card on dashboard. However if I copy the card to a new dashboard the data is still not there and I'm unable to send the command form the dashboard by pressing the card.
Also after editing via code editor and saving the command line still does not get saved. The command line is visible in the file editor version of the dashboard.
This is not a problem for newly created card. Also this is not problem with HA as in automation the commands are still visible.

### Expected Behavior

command line visible in the card editor, able to copy and edit the data

### Steps To Reproduce

Template card that was created before update from 3.6.2 (something like that but definitely before 4.0 version) with tap action send command something in Command line.
after update the command line data not visible in visual editor only if editing code

### Context

This is what I see in code editor of dash board, in the file view the command: 'power" is there

cards:
  - type: custom:mushroom-template-card
    primary: ''
    secondary: ''
    icon: mdi:power
    tap_action:
      action: call-service
      target:
        entity_id: remote.nappali_rm4
      data:
        num_repeats: 1
        command: {}
        device: Samsung_TV
      perform_action: remote.send_command
    icon_color: |-
      {% if states('media_player.nappali_tv_samsung') == 'off'%}
      grey
      {% else %}
      pink
      {% endif %}

This is in file which is attached as well:

              "cards": [
                {
                  "type": "custom:mushroom-template-card",
                  "primary": "",
                  "secondary": "",
                  "icon": "mdi:power",
                  "layout": "horizontal",
                  "tap_action": {
                    "action": "call-service",
                    "target": {
                      "entity_id": "remote.nappali_rm4"
                    },
                    "data": {
                      "num_repeats": 1,
                      "command": "power",
                      "device": "Samsung_TV"
                    },
                    "perform_action": "remote.send_command"
                  },
                  "icon_color": "white"

### Environment

```markdown
- Browser: Chrome
- HA Version:2024.8.2.
- Mushroom: v4.0.3.
```

### Anything else?

[lovelace mobile dash.zip](https://github.com/user-attachments/files/16640345/lovelace.mobile.dash.zip)

**Comment by piitaya** [comment]
Do you have the same issue if you use this action using a official Home Assistant card (e.g. tile card) ?

**Comment by nbai777** [comment]
Unfortunately I can not test this as I had no official HA card with this command type action before the update. What I can see that in automations I still can see the command line which was there before the update, because of this I think the issue is probably with Mushroom. 

Also if I create now a new card with the latest update the issue is not there both for HA and for Mushroom card, command line is editable and visible.

Also looking now more deeply into my dashboard this issue is there only if I send command to RM4 or the Roborock vacuum (both official integration), if the command is to the Samsung TV the issue is not there... This issue is getting strange...

**Comment by piitaya** [comment]
I can confirm it's not a Mushroom issue. The problem is present for every type of card. An issue has been open in the frontend repository : https://github.com/home-assistant/frontend/issues/21659
