### ISSUE TITLE
[Bug]: Additional vertical space when light entity is on

### ISSUE THREAD

**Issue by Azaelyus** [piitaya/lovelace-mushroom#1503]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

When light entity is turned on (mushroom-light-card), there is an additional vertical space above the icon. I am using the new sections view.

### Expected Behavior

There should not be any vertical space when switching between states.

### Steps To Reproduce

`type: custom:mushroom-light-card`
`entity: light.led_postel_light`
`name: LED Postel`
`icon: mdi:led-strip-variant`
`use_light_color: true`
`show_brightness_control: true`
`show_color_control: true`
`show_color_temp_control: true`
`collapsible_controls: true`
`tap_action:`
`  action: toggle`
`hold_action:`
`  action: none`
`double_tap_action:`
`  action: none`
`layout_options:`
`  grid_columns: 4`

### Environment

```markdown
- Browser: Chrome
- HA Version: 2024.8.2
- Mushroom: 4.0.3
```

### Anything else?

ON:
![image](https://github.com/user-attachments/assets/1b8721e2-43fd-4e33-a063-3e6d0583d172)

OFF:
![image](https://github.com/user-attachments/assets/25f18bb7-74bc-4c53-be79-82755fed8d8f)

It seems the bug is caused due to the fact that mushroom-state-item container is being vertically centered to the middle mushroom-state-item. When I turn off CSS property height 100% within mushroom-state-item, everything gets alligned to the top and there is no additional space.

![image](https://github.com/user-attachments/assets/ad0fefcc-4cda-4ef5-a551-29d2742ef53d)

**Comment by piitaya** [comment]
Mushroom use the same margin as tile card. When there are controls at the bottom, the content is vertically centered to avoid large space between the content and the controls.

**Comment by Azaelyus** [comment]
Ah, I see. In my point of view this looks a little bit weird as all icons are normally centered to the top. Anyway, nothing card-mod could not fix! :)
