### ISSUE TITLE
Template card is missing icon and color picker

### ISSUE THREAD

**Issue by SaSa1983** [piitaya/lovelace-mushroom#152]
The mushroom template card has a field for icon color and icon.
But there're no pickers, instead you have to type in the desired value manually.

Please update those fields to use the corresponding pickers:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/1494844/155506165-abe752fb-5d95-495e-8b50-8e59849f966e.png">

**Comment by piitaya** [comment]
It's by design. All fields are template so we don't use the color and icon picker.
