### ISSUE TITLE
[Bug]: relative_time does not return a localized result

### ISSUE THREAD

**Issue by lxffm** [piitaya/lovelace-mushroom#1520]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

if you use a template card, to show specific information e.g. as secondary information 

{{ states('sensor.rasen_sensor_soil_humidity')  }} % ⸱ {{ relative_time(states.sensor.rasen_sensor_soil_humidity.last_updated) }} ago

relative_time will always return an english localized result "1 hour" instead of "1 Stunde" (German)

This also applies if you are using other time functions like:
{{ time_since(states.sensor.rasen_sensor_soil_humidity.last_updated, 1) }}

### Expected Behavior

It's supposed to show the correctly localized result according to the language set up in Home Assistant.

### Steps To Reproduce

1. Have your language set to German
2. Set up a template sensor
3. try to show relative_time value of last_updated of your favorite sensor
example: {{ states('sensor.rasen_sensor_soil_humidity')  }} % ⸱ {{ relative_time(states.sensor.rasen_sensor_soil_humidity.last_updated) }} ago
4. Check card, it show "x hour" instead of "x Stunden", whereas an mushroom-entity-card will properly show the localized version.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: 127.0.6533.120
- HA Version: 2024.8.4
- Mushroom: 4.0.5
```

**Comment by piitaya** [comment]
Mushroom is using regular template function from Home Assistant (https://www.home-assistant.io/docs/configuration/templating/#time). I assume it should be a feature request for Home Assistant, not Mushroom.

**Comment by lxffm** [comment]
But how can that be that every Mushroom card supports it correctly translated as well as every HASS built-in card but not the template card? And how can that be an HASS issue then?

**Comment by piitaya** [comment]
Because all cards are using javascript function to get relative time (translated) and template card is using jinja function to get relative time (not translated)
