### ISSUE TITLE
[Bug]: Entity card is accepting jinja templates for icon_color

### ISSUE THREAD

**Issue by lxffm** [piitaya/lovelace-mushroom#1521]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Mushroom entity cards are not reactive to jinja templates e.g. for changing icon_colors based on values. It just leads to a white icon background with an black icon. 

### Expected Behavior

It's supposed to respect jinja templates and execute it's code.

### Steps To Reproduce

1. Create an mushroom entity card of your sensor.
2. Add you icon color code
e.g.
```
icon_color: |-
  {% set s = states('sensor.rasen_sensor_soil_humidity')|int %}
  {% if s > 50 %}
    light-green
  {% elif s <= 50 %}
    orange
  {% else %}
    red
  {% endif %}
```

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2024.8.3
- Mushroom: 4.0.5
```

**Comment by piitaya** [comment]
Only template card is using template. Other cards (entity, light, etc...) don't support templates.
