### ISSUE TITLE
[Feature]: change background of badge

### ISSUE THREAD

**Issue by j3mu5** [piitaya/lovelace-mushroom#1535]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

The [configuration variables](https://github.com/piitaya/lovelace-mushroom/blob/main/docs/badges/template.md) for badges should make it possible to change the background of the badge.

### Describe alternatives you've considered

You can change the colour of the icon. However, the colour of the icon should be used for the status of the entity (on / off). As additional information, i want to  display whether a manual mode (timer) is active. This is already possible with tile cards using card_mod. Now i would like to use the same method for badges.

```
card_mod:
  style: |
    ha-card {
      {% if not(is_state('timer.floor0_couch_cover_garden_manual_mode', 'idle')) %}
      --ha-card-background: whitesmoke;
      {% endif %}    
    }
```

**Comment by piitaya** [comment]
badges are using `--ha-card-background` as background but card mod doesn't support badges. An issue is already open on card mod repository : https://github.com/thomasloven/lovelace-card-mod/issues/391
