### ISSUE TITLE
[Bug]: Incorrect accent color

### ISSUE THREAD

**Issue by luuquangvu** [piitaya/lovelace-mushroom#1541]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

It displays incorrect color when changing icon_color or badge_color to accent color

![20240926_143453_uywl](https://github.com/user-attachments/assets/d3b85a10-c769-4223-8ca2-29f5606cb2b8)

### Expected Behavior

It should be the same as the default card

### Steps To Reproduce

1. Create a template or any card that supports icon_color or badge_color attributes
2. Set its color to accent

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Edge, native iOS app
- HA Version: 2024.9.3
- Mushroom: 4.0.7
```

**Comment by piitaya** [comment]
Mushroom is using `rgb-accent-color` because it only supports rgb color while while Home Assistant is using `accent-color`. I thought these values were sync by Home Assistant but apparently not. You can set `rgb-accent-color` in your theme to fix your issue.

**Comment by luuquangvu** [comment]
> Mushroom is using `rgb-accent-color` because it only supports rgb color while Home Assistant is using `accent-color`. I thought these values were sync by Home Assistant but apparently not. You can set `rgb-accent-color` in your theme to fix your issue.

Thanks a lot for your help.  I tried that setting as you suggested but it didn't work. I tried more and saw that when accent-color directly set to hex code or rbga then it works (Ex: accent-color: #ff9900), but when accent-color is referred by other variable then it doesn't work (Ex: accent-color: var(--light-primary-color) )
Is it a bug? Thank you so much.

**Comment by piitaya** [comment]
It's not really a bug but a limitation, if you are using a hex code, it's easier to convert it to rgb code.
But if you are using variables, it's impossible as we don't know if the variable is hex or not.
