### ISSUE TITLE
[Bug]: Chip entity

### ISSUE THREAD

**Issue by duczz** [piitaya/lovelace-mushroom#1543]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

In this code example the state is "11" but the chip shows as "11:00", why he adds :00 to the value?

```
type: custom:mushroom-chips-card
chips:
  - type: entity
    entity: sensor.waze_xxxx
```

Entity:
```
state_class: measurement
unit_of_measurement: min
device_class: duration
friendly_name: xxxx
duration: 11
distance: 4.226
route: xxxxxxxxxxxxxxxxxxxx
origin: xxxxxxxxxxxxxxxx
destination: xxxxxxxxxx
attribution: Powered by Waze

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: chrome
- HA Version: 3.9.2024
- Mushroom: 4.0.7
```

**Comment by piitaya** [comment]
It's Home Assistant that format the state, not Mushroom. You must notice the same issue if you use built-in card like the `tile` card.
Your entity has a `duration` device class so it's formatted using `hh:mm:ss`. I also work on Home Assistant front-end and we are aware of this issue so this will probably resolved in few releases.

**Comment by duczz** [comment]
On badges it is correct on tile Card Not your right, thanks
