### ISSUE TITLE
Dynamic URL in tap_action redirects to localhost in Mushroom Chips Card

### ISSUE THREAD

**Issue by jrhessels** [piitaya/lovelace-mushroom#1544]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

I'm encountering an issue where using a dynamic URL in the tap_action for the mushroom-chips-card results in the URL redirecting to localhost instead of the correct external URL. The same dynamic URL works correctly in a markdown card, but not within the mushroom-chips-card.

Clicking the chip redirects the browser to localhost instead of the expected external URL.

### Expected Behavior

The card should redirect to the dynamic URL specified by the release_url attribute from the state_attr function.

### Steps To Reproduce

1. Add the following YAML configuration to a Lovelace dashboard:
2. Ensure the entity has a valid release_url attribute.
3. Click on the chip and observe that it redirects to localhost instead of the expected URL.

### Context

type: custom:mushroom-chips-card
chips:
  - type: template
    icon: mdi:web
    icon_color: blue
    content: Release Changelog
    tap_action:
      action: url
      url_path: >
        {{ state_attr('update.zigbee2mqtt_firmware_update', 'release_url') }}

### Environment

```markdown
- Browser: google chrome
- HA Version: Core v2024.9.3 - OS V13.1 - Supervisor V2024.09.1
- Mushroom: v4.0.7
```

### Anything else?

The dynamic URL works correctly in a markdown card, as shown below:
******** Yaml ***************
type: markdown
content: >
  [Click here]({{ state_attr('update.zigbee2mqtt_firmware_update', 'release_url') }})

Please let me know if there’s any additional information or logs I can provide.

**Comment by piitaya** [comment]
As discussed in other issues. Home Assistant actions doesn't support templating, it's not a Mushroom limitation, you should experience the same thing with all Home Assistant cards.
