### ISSUE TITLE
Lights show as 0% brightness, while it should be 1%

### ISSUE THREAD

**Issue by golles** [piitaya/lovelace-mushroom#155]
**Describe the bug**
The light card is showing 0% brightness, while the lights are set to 1%

**To Reproduce**
The lights where turned on by a Hue scene.

**Expected behavior**
Obviously, the correct brightness to be shown.

**Screenshots**
<img width="463" alt="Schermafbeelding 2022-02-25 om 00 52 51" src="https://user-images.githubusercontent.com/2211503/155701028-89c90615-66d6-4b0a-b0e0-a82bf99ad54a.png">

Individual lights:
<img width="424" alt="Schermafbeelding 2022-02-25 om 00 53 18" src="https://user-images.githubusercontent.com/2211503/155701117-2c30abe1-34ac-4520-bee8-673f5824624b.png">
<img width="425" alt="Schermafbeelding 2022-02-25 om 00 53 07" src="https://user-images.githubusercontent.com/2211503/155701118-2ad4b3a3-6b26-4e72-b529-66b2febfad2d.png">

Group (hue):
<img width="375" alt="Schermafbeelding 2022-02-25 om 00 54 01" src="https://user-images.githubusercontent.com/2211503/155701165-26f04311-5431-4020-a1db-c1c3560879bb.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 98.0.4758.102 (Officiële build) (x86_64)

and
 - Browser: Companion app
 - Version: 2022.2 (2022.345)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15.3.1
 - Browser: Companion app
 - Version: 2022.2 (2022.345)

**Additional context**
Using v1.1.2

**Comment by piitaya** [comment]
The value of brightness is between 0 and 254. The value is rounded for the display. `Math.round(1 / 255)` => `0`. I will look the HA behavior for this value. 🙂

**Comment by bemble** [comment]
That's not an issue, it's a rounding problem, `brightness` is between 0 and 254. You have to use `brightness_pct` to set brightness using percents.

**Comment by golles** [comment]
Hi @bemble, I see thats it a rounding issue, but it does look really strange. Don't you agree?

**Comment by bemble** [comment]
Not for me: `(1/255)*100 = 0.39`. Rounding works like:
```
if the_value is lower than 0.5
   then the_rounded_value is zero
   else the_rounded_value is 1
```
It's the mathematic rules for rounding. We have to check if HA uses `round` or `ceil` for these value, or better, directly use `brightness_pct` instead of recompute that value.

**Comment by bemble** [comment]
After different checks, HA seams to use `round` and not `ceil`. `brightness_pct` is not given in the state.
Default `light` card sets `brightness_pct` and not `brightness`, the `brightness` value is never under `3`  which is `1%` when rounded.
Question is, @piitaya should we set `brightness_pct` instead of `brightness`?

**Comment by piitaya** [comment]
@bemble We already use `brightness_pct`.
Maybe we can display at least 1% with the light is `on` ? Light can have `brightness: 1` with automation for example.

**Comment by golles** [comment]
> Light can have `brightness: 1` with automation for example.

That's indeed what I do with my bed lights :-)
