### ISSUE TITLE
[Bug]: perform-action with notify.persistent_notification not work

### ISSUE THREAD

**Issue by nm20220210** [piitaya/lovelace-mushroom#1553]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### The error is new. It has worked before

**![Screenshot 2024-10-08 091833](https://github.com/user-attachments/assets/dd5c13f6-d497-4315-829f-01c953144d6c)**
![Screenshot 2024-10-08 091452](https://github.com/user-attachments/assets/5614f0d9-a92b-4d7c-94a5-85ab1799c40b)
![Screenshot 2024-10-08 091433](https://github.com/user-attachments/assets/777d4224-bf6f-48a5-8bdd-cd70d92c00bb)

### Steps To Reproduce

![Screenshot 2024-10-08 095119](https://github.com/user-attachments/assets/75ae86b7-0daa-41d8-a921-1c462cba2b89)

### Context

/homeassistant/custom_templates/geburtstag.jinja

YAML state
```yaml
{%- macro gruss() -%}
{{ [
 "Test1",
 "Test2",
 "Test3" ] | random -}}
{% endmacro %}
{{ gruss() }}
```

### Environment

```markdown
- Browser: Firefox or Chrome
- HA Version: 2024.10.1
- Mushroom: 4.0.7
```

**Comment by piitaya** [comment]
It's a Home Assistant limitation, template are not supported for perform-action. You can use a script as a workaround.

**Comment by nm20220210** [comment]
Is this restriction new? The same code ran before without restriction.

**Comment by piitaya** [comment]
With the exact same code? Using a tap action in the dashboard?

**Comment by piitaya** [comment]
I just checked, and you right, it worked before and it was removed with the latest update : <https://github.com/home-assistant/core/pull/122820>
This was deprecated for a long time, the proper way to do it is to create a script and call it from the dashboard.
