### ISSUE TITLE
[Bug]: Sometimes works, sometimes doesn't

### ISSUE THREAD

**Issue by sebcbien37** [piitaya/lovelace-mushroom#1557]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Hi use mushroom style but it doesn't work all the time. I have to refresh the page and sometimes it works.
It is the same on Iphone app.

![HA_problem](https://github.com/user-attachments/assets/d858b04f-304d-437e-aee3-0777e5a40064)
![HA_problem_mod_exemple](https://github.com/user-attachments/assets/ae75f9d7-89b3-48a6-a8ef-7c07a48f6bf3)

### Context

card_mod:
    style:
      mushroom-state-info$: |
        .container {
          align-items: safe normal;
          --card-primary-color: #3deadd;
          --card-secondary-color: #3deadd;
        }
      mushroom-shape-icon$: |
        .shape {
          --shape-color: #c2fcf8  !important;
        }
      .: |
        ha-card {
          height: 50px !important;
          border: 1.5px dashed #3deadd;
        }
        ha-state-icon {
          color: #3deadd;
        }

### Environment

```markdown
- Browser: Chrome
- HA Version: 2024.10.0
- Mushroom: 4.0.7
```

**Comment by piitaya** [comment]
The issue should be open on card mod repository, the support for card mod is not provided in this repository.
