### ISSUE TITLE
Hold action not working on person card

### ISSUE THREAD

**Issue by Ulrar** [piitaya/lovelace-mushroom#156]
**Describe the bug**
The hold action drop down is there on the person card, but selecting something like 'Call service' does not make the rest of the form appear.
Using the code editor to add an action anyway does not work, when I save the action gets wiped.

**To Reproduce**
- Try to add a call service on hold_action for a person card

**Expected behavior**
Same as on other cards, hold_action should work

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 97.01

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 12
 - Browser: Companion app
 - Version: Latest

**Comment by piitaya** [comment]
That was just a typo in the card editor. It will be fix in the next release. As a workaround you add the hold action with ymal 🙂
