### ISSUE TITLE
[Bug]: Number state in number card not displaying correct "time unit"

### ISSUE THREAD

**Issue by flavioxavier** [piitaya/lovelace-mushroom#1561]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

When a input number with device_class: duration and unit s (seconds) is used in number card it shows only seconds even if more than 60s

### Expected Behavior

It should show hours/minutes when the value is more than 60s like the Tile or Mushroom Entity cards

<img width="407" alt="Captura de ecrã 2024-10-23, às 16 26 46" src="https://github.com/user-attachments/assets/fbba229b-ec49-4c34-9d9d-e709e24f5228">

### Steps To Reproduce

1 - Create a number with device class duration and unit seconds
2 - Set a value bigger than 60
3 - Add it to a Mushroom number card

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Firefox
- HA Version: 2024.10.1
- Mushroom: 4.0.7
```

**Comment by piitaya** [comment]
The duration device class is not consistent in Home Assistant. Because you can set an unit but it's not respected in the UI. I will look how I can fix that in Home Assistant and then Mushroom can adapt.

**Comment by flavioxavier** [comment]
But it's fixed in home assistant, it works as expected (and even in the
mushroom entity card ) a quick fix seems to use the same code to show the
state here as in the mushroom entity card, if nothing else for consistency.

A quarta, 23/10/2024, 20:33, Paul Bottein ***@***.***>
escreveu:
