### ISSUE TITLE
[Bug]: <title>Denon receiver volume control gone after latest HA update

### ISSUE THREAD

**Issue by troybarwick** [piitaya/lovelace-mushroom#1574]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

After last night’s HA OS upgrade, the volume control is gone from my Denon receiver in Mushroom.

### Expected Behavior

I expected to have the Volume control.

### Steps To Reproduce

Bring up Mushroom card, and look for volume control.

### Context

N/a

### Environment

```markdown
Core
2024.11.0
Supervisor
2024.11.2
Operating System
13.2
Frontend
20241106.0
```

### Anything else?

N/a

**Comment by piitaya** [comment]
Do you have volume control using the other official card or using the more info?

**Comment by troybarwick** [comment]
Yes it is there in the official card.

**Comment by piitaya** [comment]
Can you share the full yaml state of your entity using this page https://my.home-assistant.io/redirect/developer_states/ ? I don't have this receiver so I can not tested but I can take a look if I had the state.

**Comment by troybarwick** [comment]
auto_update: false display_precision: 0 installed_version: 2.1.1 in_progress:
false latest_version: 2.1.1 release_summary: null release_url:
https://github.com/madmicio/ampli-panel-card/releases/2.1.1 skipped_version:
null title: null update_percentage: null friendly_name: AV Receiver control
card update supported_features: 23

**Comment by troybarwick** [comment]
ok, after the last update, it is now back.  Thank you,   Very odd.
