### ISSUE TITLE
[Feature]: Add Support for Decimal Increments in Number-Card Buttons

### ISSUE THREAD

**Issue by systempal** [piitaya/lovelace-mushroom#1579]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Currently, the number-card buttons only support integer increments. This enhancement request proposes adding the option to allow decimal increments for these buttons.

### Describe the solution you'd like

Add a configurable property to the number-card component, allowing users to define the increment value, including decimal values.
The default increment can remain at 1, but the user can specify other increments like 0.1, 0.5, etc.

### Additional context

In some applications, users may need to adjust values in decimal steps (e.g., 0.1, 0.5) rather than whole integers. Having decimal increment support would improve flexibility and usability in scenarios where precision is needed.
Example: This functionality would be particularly useful for adjusting temperature presets on a thermostat, where precise decimal increments allow for more accurate control.

Look at the image below. Using preset entities i can only increment temperature by 1.

![Screenshot 2024-11-10 003217](https://github.com/user-attachments/assets/6ea3ffd7-6b1f-4783-8100-fafa382cdfcd)

**Comment by piitaya** [comment]
It supports decimal increment. It should use the step attribute defined in your number entity.

**Comment by systempal** [comment]
The entities I need to control are part of a device that likely does not define the step attribute but does support it. Is it possible to add a property to force the step value directly from the card?

**Comment by piitaya** [comment]
No, it should be fixed at the entity level, not the card level. If you device supported decimal increments, it must set it in attributes. You should be able to override the step using `customize:` in your `configuration.yaml` (documentation: https://www.home-assistant.io/integrations/homeassistant/#manual-customization)

**Comment by systempal** [comment]
ok, tnks,
btw i'm using versatile thermostat.
