### ISSUE TITLE
[Bug]: Person Card "Away" Inconsistency

### ISSUE THREAD

**Issue by greghesp** [piitaya/lovelace-mushroom#1588]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

I know this card only officially supports `device_tracker` and `person`, however I ended up using a template sensor which combines our location based of the app and/or beacons

```yml
template:
  - sensor:
      - name: "Gregs Location"
        picture: "/api/image/serve/ab4e1a0a8c88177db100859a9e94a07e/512x512"
        state: >
          {% set person = states('person.greg') %}
          {% set beacon = states('sensor.greg_phone_beacon') %}
          {% if person != 'home' %}
            {% if person == 'not_home' %}
              Away
            {% else %}
              {{ person | replace('_', ' ') | title }}
            {% endif %}
          {% else %}
            {% if beacon != 'not_home' %}
              {{ beacon | replace('_', ' ') | title }}
            {% else %}
              {{ person | replace('_', ' ') | title }}
            {% endif %}
          {% endif %}
 ```
 
 This works perfectly, but there's some weird bug when I am `not_home`.  I know the sensor doesn't return `not_home`, but even if you force it as you see below, it doesn't fully work

As you can see, the left card uses my template sensor above,  and the card on the right, uses the device_tracker entity based on the mobile app.

<img width="501" alt="image" src="https://github.com/user-attachments/assets/1e2287cc-586d-4a46-b741-9dfd8885e8f8">

The icon on the person card works in both instances, but where things are different is the actual state.  The state reported for both the sensor and device_tracker is `not_home`, but the device tracker in the card reports `Away`.

Any idea where this actually comes from?  The states are identical and there are no attributes

<img width="820" alt="image" src="https://github.com/user-attachments/assets/4207a9a3-2bf8-4e24-ad25-d61e843b33cd">
<img width="718" alt="image" src="https://github.com/user-attachments/assets/9d46cb5a-cadf-4a6e-be4e-d5c239abaa3a">

### Expected Behavior

A state of `not_home` would show `Away` for all entities

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2024.11.1
- Mushroom: 4.1.1
```

**Comment by piitaya** [comment]
Hello 👋
This is not a Mushroom issue. However, I can help you debugging.
All cards are using state translations when displaying a state in the UI. That's why the state is "not_home" and the displayed value is `Away`. (more info about [state translations here](https://developers.home-assistant.io/docs/internationalization/core/#state-of-entities)). These translations are done for every domain (person, device tracker) but are not supported by template sensor because the state can be anything. Only person and device tracker entities will show `Away`. 
I let you continue the discussion on another platform (HA forum, HA discord) as it's not a Mushroom issue.
