### ISSUE TITLE
Card Styling - Width & General Styling

### ISSUE THREAD

**Issue by jaredguiles** [piitaya/lovelace-mushroom#159]
**Is your feature request related to a problem? Please describe.**
The problem I'm running into is some cards need to be wider than others, and set to different widths when placed in horizontal rows. 

**Describe the solution you'd like**
1) Add a feature to define the size of the card
or 
2) Allow other styling on mushroom cards. I "hacked" the fan and light entity below to display how it wanted it to but wrapping them in a vertical stack (not ideal solution, but it wouldn't work without it), but when trying to do the same with a title and chip card, it does not work causing my chips to be wrapping when space is available from the title card. 

Styling in general would be great as there are other tweaks to the "look and feel" I would like to have control over. The Mushroom Theme helps with some, but not all variables work (I.e. mush-rgb-state-fan: var(--rgb-blue) doesn't work, it still remains green thus having to change the color of the mush-rgb-green variable)

```
type: horizontal-stack
cards:
  - type: vertical-stack
    cards:
      - type: custom:mushroom-light-card
        entity: light.office_ceiling_light_local
        name: Ceiling Light
        icon: fapro:svgs/duotone/light-ceiling
        style: |
          ha-card {
            width: 50%;
          }
  - type: vertical-stack
    cards:
      - type: custom:mushroom-fan-card
        entity: fan.office_ceiling_fan_2
        icon_animation: true
        layout: horizontal
        show_percentage_control: true
        name: Ceiling Fan
        style: |
          ha-card {
            width: 150%;
            margin-left: -50%;
          } 
```
![Screen Shot 2022-02-26 at 09 31 50](https://user-images.githubusercontent.com/43616413/155853356-22f4138f-05ea-4aa3-934d-98e93dd2b6f4.png)

**Comment by antonio1475** [comment]
For layout topics, you might want to check out [Layout card](https://github.com/thomasloven/lovelace-layout-card)

**Comment by cyrilphoenix71** [comment]
@jaredguiles your lovelace seems To be cool, did you already share screens ?

**Comment by piitaya** [comment]
This a layout issue. Mushroom does solve layout issue. It's just custom cards.
Thanks @antonio1475 for the link 🙂

**Comment by jaredguiles** [comment]
Thanks @antonio1475, I forgot about that. Worked like a charm!

**Comment by jaredguiles** [comment]
> @jaredguiles your lovelace seems To be cool, did you already share screens ?

Thanks! Not yet, but once I get things finalized I can. Heres a preview of what it looks like so far...

![Tablet – Home Assistant](https://user-images.githubusercontent.com/43616413/155922958-5fd9b712-9bec-4359-a2e0-9dc72e4c36ee.png)
