### ISSUE TITLE
Light Card State: instead of State a Number is shown

### ISSUE THREAD

**Issue by wcorne** [piitaya/lovelace-mushroom#1607]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Hi! recently it seems that the state of light cards is not working anymore. In secondary information if state is selected then normally it would show on/off below the name of the light. Also the brightness slides does not show % anymore but a number instead. I am not able to change any of the settings to get this back. 
![image](https://github.com/user-attachments/assets/015dbdd4-de41-47d4-a4fb-c2b762a403af)
![image](https://github.com/user-attachments/assets/b3f1b708-be31-4986-b4b7-3ea6a485bfe7)

### Expected Behavior

The state is shown as on or off. When changing brightness i want to see a % instead of a number. 

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by piitaya** [comment]
Try refreshing your dashboard, it's a cache issue.
I'll close the issue as it's not Mushroom related (your screenshot shows the more info)

**Comment by piitaya** [comment]
Yeah, sorry for the explanation. Just refreshing the page should work, or clearing the cache yes :)

**Comment by wcorne** [comment]
Thanks! It works now
________________________________
