### ISSUE TITLE
Cover Card buttons disabled if motors not report state

### ISSUE THREAD

**Issue by EMP83** [piitaya/lovelace-mushroom#163]
I have a problem with Cover Card.
I use Somfy RTS roller motors.
The problem with these roller motors is that they do not report the state.
They accept 4 commands:

UP
Down
Stop
Pairing
If i want to open 20% of the roller ( assuming it is closed) i press UP and after that Stop when I consider that I have reached the 20%.

My problem: when i press Up button the cover card switch state from Closed to Open and disable the button Up. After that if i want to open to 50% or 100% i have to press Down to change the state to Closed , then Stop and Up to open.
Every time I want to change roller position , I have to do something like that.
I was wondering if there was a possibility that the buttons would remain active regardless of roller position?

**Comment by piitaya** [comment]
Can you send a detail of your entity attributes in the different state ?
Example : 
<img width="435" alt="Capture d’écran 2022-02-27 à 21 59 29" src="https://user-images.githubusercontent.com/5878303/155899715-19aa015a-e73e-438c-bde0-005547d97658.png">

**Comment by EMP83** [comment]
![IMG_1664](https://user-images.githubusercontent.com/36104474/155920115-b9378057-fb26-4d79-9f1a-82413f5d7976.PNG)
![IMG_1663](https://user-images.githubusercontent.com/36104474/155920118-eefa29be-a0d3-4d72-9027-f8a8d94acdb8.PNG)
![IMG_1662](https://user-images.githubusercontent.com/36104474/155920119-b67b84a2-bc28-4eb3-a677-becd5df24a60.PNG)
3 positions:
closed
open 50%
open 100%

**Comment by EMP83** [comment]
This [Video](https://www.youtube.com/shorts/zhzI-6Jf19g) can properly demonstrate my problem.

**Comment by piitaya** [comment]
Thanks. It will be fixed with the linked PR using the assumed state property.

**Comment by EMP83** [comment]
> Thanks. It will be fixed with the linked PR using the assumed state property.

Merci beaucoup!

**Comment by piitaya** [comment]
> > Thanks. It will be fixed with the linked PR using the assumed state property.
> 
> Merci beaucoup!
> 
> The changes will be seen in the next release?

Yep
