### ISSUE TITLE
Unable to find Mushroom in HACS

### ISSUE THREAD

**Issue by adamcavendish** [piitaya/lovelace-mushroom#165]
![Screenshot from 2022-02-28 01-48-41](https://user-images.githubusercontent.com/1346161/155893581-8a9179ed-b14e-4373-a586-48ca30df2d74.png)

HA version:  core-2022.2.9
HA install method: container / docker
HACS version: 1.23.0

**Comment by piitaya** [comment]
I pushed the 1.2.2 update. This should fix your issue :)
