### ISSUE TITLE
Display badges on entity cards

### ISSUE THREAD

**Issue by zbuh** [piitaya/lovelace-mushroom#166]
**Is your feature request related to a problem? Please describe.**
Allow the display of numeric/icon badges

**Describe the solution you'd like**
have two configuration fields with templates, one for value, another for color

**Describe alternatives you've considered**
n/a

**Additional context**
Noticed the display of ? notification when entity is unavailable. Maybe we can extend the functionality, to make it configurable.

**Comment by bemble** [comment]
Hi, thanks for your request.
We have something planed #84. Maybe the text will be available, not sure yet (maybe in templates).

**Comment by KTibow** [comment]
@zbuh can you please close this issue as it is a duplicate?
