### ISSUE TITLE
Zipping Releases

### ISSUE THREAD

**Issue by eximo84** [piitaya/lovelace-mushroom#167]
**Is your feature request related to a problem? Please describe.**

Not a big request but can the js files be zipped to provide an easy download.  Downloading 36 individual files is annoying especially if you miss one or two.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by piitaya** [comment]
I reverted to a single file because HACS doesn't fully support multiple file : https://github.com/piitaya/lovelace-mushroom/releases/tag/v1.2.2

**Comment by eximo84** [comment]
Ah ok, i dont use HACS, no worries. No issue then.
