### ISSUE TITLE
Allow line break for entity name

### ISSUE THREAD

**Issue by pedolsky** [piitaya/lovelace-mushroom#173]
**Is your feature request related to a problem? Please describe.**

When I arrange multiple cards in a grid, I have to make sure that the name of the entity fits in the line for the name (see picture below). 

**Describe the solution you'd like**

The Mushroom Template Card has a multi-line feature, so I wonder if this could be used for the other cards. 

**Additional context**
Screenshot:
![E251740C-0832-40B3-B0A5-ED213FB017E8](https://user-images.githubusercontent.com/71203830/156071024-38ccd7d9-2ce4-4ee3-9868-98fb5d2e69de.jpeg)

**Comment by piitaya** [comment]
I pushed an update to crop the primary information on card to avoid text overflow like this.
For design consistency, we do not plan to add multi text for the name for now.

**Comment by pedolsky** [comment]
Wow, fast as lightning! Thank you very much ♥️
