### ISSUE TITLE
No controls for actions in card or chip editor

### ISSUE THREAD

**Issue by gadgetchnnel** [piitaya/lovelace-mushroom#176]
**Describe the bug**
When creating or editing a Mushroom card or chip, no controls are shown to select the actions to perform on tap, double-tap, or hold. These were previously being shown

**To Reproduce**

1. Add a new Mushroom entity card 
2. Add a Mushroom chips card 
3. Add a chip to the card

**Expected behavior**
Fields should show to select tap, double-tap, and hold actions

**Screenshots**
Entity card editor:

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/2099542/156165951-8a655811-e842-4aba-b184-534567447acc.png">

Chip editor:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/2099542/156167087-296c8b0a-a8dc-4f48-b33e-8bd10d660bca.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 98.0.4758.102

**Additional context**
Home Assistant version: 2022.3.0b5
Mushroom version:  v1.2.2

**Comment by piitaya** [comment]
I think it's due to the 2022.3 HA version. Try open the editor of the light card before opening editor of a mushroom card.

@zsarnett Do you think there is a way to preload some HA component from a custom card ? Or if it is something we can do ? The entity picker and the action picker is very useful and It can be good to avoid copying all the code from HA in the custom cards.
Maybe exposing a `window` function to load some components ?
```
window.loadHAComponent("ha-entity-picker");
```

**Comment by zsarnett** [comment]
I am looking into seeing if it's possible to allow for custom cards to utilize `ha-form` and we could add in action editors (possibly).

This would allow for these components to be lazy-loaded by HA based on what is used in the schema.

**Comment by piitaya** [comment]
> I am looking into seeing if it's possible to allow for custom cards to utilize `ha-form` and we could add in action editors (possibly).
> 
> This would allow for these components to be lazy-loaded by HA based on what is used in the schema.

Cool 🙂 
Maybe all `ha-form-*` and `ha-selector-*` imports from [ha-form.ts](https://github.com/home-assistant/frontend/blob/dev/src/components/ha-form/ha-form.ts) and [ha-selector.ts](https://github.com/home-assistant/frontend/tree/dev/src/components/ha-selector) can be lazy-loaded based on the schema 🙂.

**Comment by zsarnett** [comment]
Yep. That is the goal. Ill let you know as soon as I get any concrete answers
