### ISSUE TITLE
Entity Icon Incorrect when not specified

### ISSUE THREAD

**Issue by eximo84** [piitaya/lovelace-mushroom#178]
**Is your feature request related to a problem? Please describe.**

I am using auto entities to list out a selection of switches.  This works great however the icon is the default HA switch rather than the icon configured.

See TV is using lightning bolt icon in the list but on the entity it shows a TV icon.

**Describe the solution you'd like**

Entity icon to use the configured entity icon rather than default HA icon

**Describe alternatives you've considered**

Nothing

**Additional context**

![Entity](https://user-images.githubusercontent.com/25502878/156186687-255512ad-161a-40db-a974-ecc96c83aabe.png)

![icon](https://user-images.githubusercontent.com/25502878/156186736-6d746a99-75db-4907-844a-17d69b90095c.png)

**Comment by eximo84** [comment]
To add to this, it does this with non auto entity cards too.  Example an input_boolean shows a X or a Tick rather than the icon configured on the entity

**Comment by piitaya** [comment]
Which version of mushroom are you using ?

**Comment by eximo84** [comment]
> 

https://github.com/piitaya/lovelace-mushroom/releases/tag/v1.1.2

I just downloaded each file before you uploaded 1.2.2

**Comment by piitaya** [comment]
The `1.2.2` fixes your issue.

**Comment by eximo84** [comment]
Downloaded latest, issue fixed.  Thanks
