### ISSUE TITLE
Hex codes for Icon Colours

### ISSUE THREAD

**Issue by eximo84** [piitaya/lovelace-mushroom#180]
**Is your feature request related to a problem? Please describe.**

If i used a HEX code e.g. #40445a the icon has no colour.

**Describe the solution you'd like**

Ability to use HEX codes for icons

**Describe alternatives you've considered**

Nothing

**Additional context**

**Comment by piitaya** [comment]
Hexa decimal code is not supported. The default palette isn't enough ? You can change the color with mushroom theme if you want to change the palette.

**Comment by berrywhite96** [comment]
> Hexa decimal codes are not supported. The default palette isn't enough ? You can change the palette with mushroom theme if you want.

For example I want to exactly match the icon color to the main logo color. So I need to define it as exactly as hex or similar.
