### ISSUE TITLE
Chip Entity does not show Name even when filled

### ISSUE THREAD

**Issue by eoren1** [piitaya/lovelace-mushroom#187]
The Chips Entity has an option for Name (optional) but, when filled, the name does not show at the top of the chip as expected.
Chips would be more useful (having to rely more on Entity cards now) with a Name visible

**Comment by piitaya** [comment]
Can you provide more detail, I unable to reproduce the issue (version of HA, version of mushroom, config exemple, screenshots, etc...)
<img width="639" alt="image" src="https://user-images.githubusercontent.com/5878303/156894589-0594f4b7-720e-41f3-8e7d-ef77ec01ebc6.png">

**Comment by eoren1** [comment]
Thanks for that. I had mistakenly left it at content_info default
However, I am having issues with being able to tell the state of an Entity Chip when using name as the icon does not change color with toggling on/off as the default entities does
I did not see any option to show this. I looked at icon colors but ended up leaving it as default.
Perhaps offering a secondary info for Chip entities would provide added functionality? That would allow me to show if on/off in case the icon cannot change color to show this. 

`type: custom:mushroom-chips-card
chips:
  - type: entity
    entity: switch.mudroom_heat_basement_dehumidifier_switch
    name: Basement
    tap_action:
      action: toggle
    content_info: name
    icon: mdi:toggle-switch
  - type: entity
    entity: switch.zooz_zen15_power_switch_switch
    content_info: name
    name: Leila Heat
    tap_action:
      action: toggle
  - type: entity
    entity: switch.attic_dehumidifier_switch
    content_info: name
    name: Attic
    tap_action:
      action: toggle
  - type: entity
    entity: switch.unfinished_dehumidifier_switch_2
    content_info: name
    name: Unfinished
    tap_action:
      action: toggle
  - type: entity
    entity: switch.crawlspace_dehumidifier_switch
    content_info: name
    name: Crawl
    tap_action:
      action: toggle
alignment: center
`
<img width="471" alt="Screen Shot 2022-03-05 at 1 09 48 PM" src="https://user-images.githubusercontent.com/57462669/156895227-74ec3f1c-bfae-4b4b-812d-5b3aad0cfe16.png">

Neither icon changes color or type when toggle the icon

**Comment by piitaya** [comment]
Just add a icon_color property 🙂 it's available with the editor. The color is applied when the entity is active.
```
    icon_color: orange
```

**Comment by eoren1** [comment]
Sorry - I'm an idiot. Thought that was the solid color not the toggled color...
