### ISSUE TITLE
Support groups in light card

### ISSUE THREAD

**Issue by samuelmcconnell** [piitaya/lovelace-mushroom#188]
**Is your feature request related to a problem? Please describe.**
Groups cannot be selected with the light card, even for groups that consist entirely of lights. If you type in the group entity name manually you can create the card, but without brightness/color/temperature control.

**Describe the solution you'd like**
Groups should be supported as lights, with brightness/color/temperature control functionality, just as if it were a single light.

**Comment by piitaya** [comment]
You can define group with platform group : https://www.home-assistant.io/integrations/light.group/. to support all light features.
We didn't add group support (https://www.home-assistant.io/integrations/group/) but it's to hard to manage and attributes are very limited.

**Comment by SaSa1983** [comment]
I'm using a light.group and it works like a charm
