### ISSUE TITLE
Support custom open/close icon for cover

### ISSUE THREAD

**Issue by anhnvme** [piitaya/lovelace-mushroom#189]
Hello,

Can you support open/close state icon for cover ?
We can add more field choose icon for close state and open state ?

Thank you

**Comment by piitaya** [comment]
It's not planned because it will overload the editor. We will keep the same rules as HA official card.
If we do this for cover, some people will ask to do this on lights, alarm, sensor, etc...
You can set the `device_class` on your cover to adapt the icon (curtain, door, window, shutter, etc...)
