### ISSUE TITLE
Sliders does not work after closing edit mode

### ISSUE THREAD

**Issue by pascalMN** [piitaya/lovelace-mushroom#190]
**Describe the bug**
In Home Assistant after adding mushroom card with slider and clicking "Done" slider does not work. After refreshing page everything is ok.

**To Reproduce**
1. Click "Edit Dashboard" button from context menu in right top corner
2. Add mushroom card with slider. For example light card with brightness control enabled
3. Click "Done" button to exit edit mode

**Expected behavior**
There is possibility to change brightness of light

**Desktop:**
 - Browser: Safari, Chrome, Home Assistant Android application
 - Home Assistant Core 2022.2.0
 - Home Assistant Supervisor 2022.01.1

**Additional context**
The same bug is when user reactivates tab with sliders.

**Comment by antonio1475** [comment]
I'm seeing something potentially related to this (and more frequent than after Edit): if I turn on a light from a different dashboard tab/view (non-Mushroom) and then go to a Mushroom view with the slider:
The Mushroom light card status is okay (on & % brightness), but the slider can't be operated until:
a) I refresh the page
b) I toggle it off & on
c) I click on the button for light temperature control, then again for brightness.

I'll do some more testing and record a video.

**Comment by antonio1475** [comment]
Can confirm it also fixes the issues I was having described above, not coming from Edit mode! Thank you!!

**Comment by pascalMN** [comment]
For me everything looks fine. Good job! 👍
