### ISSUE TITLE
Show percent while using sliders

### ISSUE THREAD

**Issue by capstan1** [piitaya/lovelace-mushroom#197]
When using the sliders on the lights card, the shown percentage only reflects the change when I'm done adjusting. While changing it, I have to guess where I'll be landing according to the length of the bar (which can be quite difficult on mobile).
It would be great to change the shown brightness to the % you are adjusting to.

**Comment by pedolsky** [comment]
Maybe you could compare the code of [Mattiehas slider-button-card](https://github.com/mattieha/slider-button-card) with that in Mush used.

**Comment by sachinss123** [comment]
Yes please, I second this request
