### ISSUE TITLE
Allow change font size

### ISSUE THREAD

**Issue by fantnhu** [piitaya/lovelace-mushroom#198]
Hi! 
Your work is very good, congratulations :)
I would like to be able to change the primary and secondary (name and status) font size on the card.
I tried to overwrite css in the mushroom.js file, but I didn't succeed. Even if I change it there, something always overwrites it. Have any idea? Unfortunately, the letter is very small for me (14-12px).
Have a nice day!

**Comment by piitaya** [comment]
The title card and chip card font size can already be changed with the theme. It's a good idea to add this 🙂

**Comment by fantnhu** [comment]
I was able to do it on the climate card. Configuration with editing the template. Unfortunately, the template does not work on light and entity cards. Or am I just lame? : D
Thank you so much for your work, each card is wonderful.
![image](https://user-images.githubusercontent.com/73642352/159049077-1370d475-db08-484f-b349-5f1d1a3985e8.png)

**Comment by posreg** [comment]
> I was able to do it on the climate card. Configuration with editing the template. Unfortunately, the template does not work on light and entity cards. Or am I just lame? : D Thank you so much for your work, each card is wonderful. ![image](https://user-images.githubusercontent.com/73642352/159049077-1370d475-db08-484f-b349-5f1d1a3985e8.png)

I', very sorry to ask here, but how did you ssetup this climate card > any chance you could share the code please
as far as I know the mushroom climate card has not been launched yet

**Comment by fantnhu** [comment]
The problem is solved. I didn't do it in a configuration editor. (It should work there too) The classes have been added, if you have card-mod installed, you can easily set it:
`type: vertical-stack
cards:
  - type: custom:mushroom-light-card
    entity: light.nappali_mennyezet
    name: Mennyezet
    show_brightness_control: true
    show_color_temp_control: true
    layout: horizontal
    tap_action:
      action: toggle
    hold_action:
      action: none
    double_tap_action:
      action: none
    icon: hue:ceiling-round
    card_mod:
      style: |
        ha-card {
          --card-primary-font-size: 1.1rem;
          --card-primary-font-weight: bold;
          --card-secondary-font-size: 1.1rem;
          --card-secondary-font-weight: solid;
        }`
        
![image](https://user-images.githubusercontent.com/73642352/159637232-7f408d9f-3d39-43e2-a07e-521f58416888.png)
This allows me to set the font size for each card.
