### ISSUE TITLE
Vertical Covers

### ISSUE THREAD

**Issue by benquan** [piitaya/lovelace-mushroom#223]
**Is your feature request related to a problem? Please describe.**
The cover card is currently only horizontal. I would love to see a vertical option as this is the way blinds usually work.

**Describe the solution you'd like**
Two options come to mind, either a simple minimalistic slider that goes vertical, or an actuall shutter like shutter card

**Describe alternatives you've considered**
There is a shutter card [https://github.com/Deejayfool/hass-shutter-card](url) which displays this image:
![shutter-card](https://user-images.githubusercontent.com/3030645/161320581-091b79da-83fa-4a9f-9dec-e089b9fa088f.gif)

The problem is that seems to be discontinued and also could be prettier.

**Comment by piitaya** [comment]
Hi 🙂 It does not respect the Mushroom design because slider are horizontal in Mushroom. I don't think we can provide such a thing.
