### ISSUE TITLE
Inverse cover active icon

### ISSUE THREAD

**Issue by bramstroker** [piitaya/lovelace-mushroom#227]
Thanks for the great card library, you did an awesome job on this! reworking my whole dashboard using your cards.

I have one feature request.

I use the cover card for multiple of my roller shutters, and sunscreen. When the roller shutter is `open` it is actually in an inactive state (i.e. the shutter does not cover the screen), but the icon shows it as active. When the shutter is `closed` the icon is showing an inactive state.

See this screenshot what I mean.

<img width="511" alt="Screenshot 2022-04-03 at 20 49 31" src="https://user-images.githubusercontent.com/2345875/161443575-56c0dbda-448b-4a9e-9895-e9333bc03481.png">

In this case I would like the cover icon to be grayed out instead of blue, what will make much more sense.
Would be nice if there is some option `invert_open_state` or `invert_icon_state` or something like that which allows to swap this behaviour.

**Comment by beauterham** [comment]
Im up fotme this!

**Comment by dominicusmento** [comment]
I'd like something pretty similar - and it is to have switched logic on state of the cover.
When it's 'Opened 74%', I'd like to see it as percentage of how much window is covered '26%'.
So states would be:
1. Open
2. Percentage of coverage
3. Closed

Any way of having this implemented along with the icon inverse as an option?
Here is the same cover shown in stock card and mushroom:
![image](https://user-images.githubusercontent.com/7549001/164936560-0ca82a14-91a0-4f95-9d13-6fc42b94b16c.png)

(by the current implementation I have a feeling that I operate a light and not a cover)
