### ISSUE TITLE
Light card mobile mode : more room for slider!

### ISSUE THREAD

**Issue by graounest** [piitaya/lovelace-mushroom#231]
Hey guys, thanks for the amazing job!

Just suggesting an idea for mobile users about light cards : in default display mode, would it be easy to put the temp and palette buttons on the right of the icon and name area? So that the slider would have more room.
Indeed say I have two light cards in a grid (2 columns) on a mobile phone (6.8" screen) I find the slider a little bit too small to use (I've attached a screenshot)

Again : just asking. Job is amazing and this mushroom project adds so much to my dashboard !!
![IMG_20220404_195525](https://user-images.githubusercontent.com/54250806/161603062-c6f31266-1919-410f-a3be-97f0eeba0aa7.jpg)

**Comment by antonoal** [comment]
I would also love to see improved the way mushroom cards look like on small screens. I often use HA on my iphone xs and find the controls are unusable.
