### ISSUE TITLE
Whare do i set grid etc for layout cards?

### ISSUE THREAD

**Issue by henrikrox** [piitaya/lovelace-mushroom#235]
When i try to add a light, person etc, it just goes under each other, i dont see any possibiltes of setting a grid like in the picture on github
![2022-04-05 13_59_17-test – Home Assistant](https://user-images.githubusercontent.com/6884716/161749231-c2de7f8a-f308-4b54-ac90-867285bb2eb0.png)

**Comment by piitaya** [comment]
Hello 🙂  You must use https://www.home-assistant.io/dashboards/grid/ for grid and add mushroom cards in the grid.

**Comment by henrikrox** [comment]
> Hello 🙂 You must use https://www.home-assistant.io/dashboards/grid/ for grid and add mushroom cards in the grid.
![2022-04-05 20_38_02-test – Home Assistant](https://user-images.githubusercontent.com/6884716/161826374-68c0ffcd-5bff-4579-a704-32c674dc71a1.png)

already tried grid card, then this happens

**Comment by henrikrox** [comment]
i still miss the picture on this github where you can set columns etc. am i missing something?

**Comment by antonio1475** [comment]
@henrikrox grid CARD, not Grid view on the Dashboard tab.

Add a card, search for type: Grid. You can then set how many columns (3 by default)

**Comment by henrikrox** [comment]
> @henrikrox grid CARD, not Grid view on the Dashboard tab.
> 
> Add a card, search for type: Grid. You can then set how many columns (3 by default)

ok sorry, misread, is there a discord im wondering also how i can create a group of lights, so i have a main screen thats like weather, persons, then lights for example. So when i press the lights group, i get a list of all my lights, is that possible

(sorry for changing the topic)

**Comment by panessa70** [comment]
Check this out: [https://www.youtube.com/watch?v=E2yJG9cpOA0](url)
Nice walkthrough from Zack Barett
