### ISSUE TITLE
How to use selected entity in Template card in "service_data"

### ISSUE THREAD

**Issue by j-loewen** [piitaya/lovelace-mushroom#237]
Hello,

I use the Template card to show my Network devices. Now I would like to call a script on tap and provide the script with the entity_id as a variable.

Here is my simplified config of the Template card:
```
type: custom:mushroom-template-card
entity: switch.amazon_6f5b262cc
primary: '{{ state_attr(entity, ''friendly_name'') }}'
secondary: |-
  {{ 
    iif(state_attr(entity, "network") == "guest", 'GUEST', 'MAIN') 
  }} | D: {{
    state_attr(entity, 'receive_speed_mbitps') 
  }} {{
    state_attr('sensor.google_wifi_download_traffic', 'unit_of_measurement') 
  }} U: {{
    state_attr(entity, 'transmit_speed_mbitps') 
  }} {{
    state_attr('sensor.google_wifi_upload_traffic', 'unit_of_measurement') 
  }}
icon: mdi:wifi
icon_color: |-
  {% if is_state(entity, "on") -%}
    {% if state_attr(entity, "prioritized") == true -%}
      green
    {%- else -%}
      {% if (state_attr(entity, 'receive_speed_mbitps') | float) > (states('sensor.speedtest_download') | float) / 2 or (state_attr(entity, 'transmit_speed_mbitps') | float) > (states('sensor.speedtest_upload') | float) / 2 -%}
        red
      {%- else -%}
        white
      {%- endif %}
    {%- endif %}
  {%- else -%}
    grey
  {%- endif %}
layout: horizontal
hold_action:
  action: none
double_tap_action:
  action: none
tap_action:
  action: call-service
  service: script.network_prioritize
  service_data:
    entity: '{{ entity }}'
  target: {}
```
The entity is replaced everywhere but in "service_data" in "tap_action".
How can I call the script and provide the "entity" variable to prioritize the device? 

I know that I could use the entity_id itself in this example but this is just a simplified example. In my setup I use this Template card in a "auto-entities" card.

**Comment by piitaya** [comment]
The `{{ entity }}` variable is only available in template (primary, secondary, icon, icon_color).
Tap action is not a template so templating variables don't work but you should be able to use `this.entity` from `custom:auto-entities` custom-card : https://github.com/thomasloven/lovelace-auto-entities#entity-options

**Comment by j-loewen** [comment]
It works!
Thanks.
