### ISSUE TITLE
Not HA User Question: Color Picker Format

### ISSUE THREAD

**Issue by MarcelMertens** [piitaya/lovelace-mushroom#240]
Hello, 
i'm using this great card on IObroker Lovelace. Can someone explain me which "format" the value of the selected color is?
I received a 18 digit Hex value #XXXXXXXXXXXXXXXXXX as a return, sometimes with a single dot on different positions.
![grafik](https://user-images.githubusercontent.com/20799825/162047487-bab3945e-e80b-4b2a-9518-ecf977825f4b.png)
Kind Regards,

**Comment by KTibow** [comment]
This seems out of scope for Mushroom Cards... Consider closing and asking somewhere else, like the Home Assistant forums/Discord?
