### ISSUE TITLE
Alarm panel does not display correctly within a grid

### ISSUE THREAD

**Issue by RaulVKoNe** [piitaya/lovelace-mushroom#249]
**Describe the bug**
Alarm panel does not display correctly within a grid, when it is armed and see the numbers to disarm. It goes off the grid.

**Screenshots**
![imagen](https://i.ibb.co/Vq68w7Z/Captura-de-pantalla-2022-04-07-230246.png)

**Desktop (please complete the following information):**
 - From any browser

**Smartphone (please complete the following information):**
 - App Android

**Comment by yormedia** [comment]
same here, also in Custom Grid layout from Layout-card

**Comment by dbaq** [comment]
I can confirm the issue with grid.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/1867703/164059794-e06c0e88-a516-459e-9537-e31781a8c7f1.png">

```
type: custom:mushroom-alarm-control-panel-card
entity: alarm_control_panel.ha_alarm
states:
  - armed_away
```
