### ISSUE TITLE
Attribute in Primary/Secondary Info

### ISSUE THREAD

**Issue by josuabarron** [piitaya/lovelace-mushroom#253]
**Is your feature request related to a problem? Please describe.**
There is no real Problem, I really love the Mushroom cards! Best I have seen so far.
But I have a few entities, that have Attributes I want to show. E.g. the NINA Warning System here in Germany. It has its Warning in the Attributes. Is there a way to include those in the Primary/Secondary Information?

**Comment by capandcamera** [comment]
```
secondary: "{{ states['sensor.nina_sensor'].attributes.headline }}"
```

(Replace the sensor name and the attribute name)

**Comment by piitaya** [comment]
You can also use :
```
entity: sensor.nina_sensor
secondary: "{{ state_attr(entity, 'headline') }}"
```
The entity variable is available in template 🙂.
For the attributes, it's better to use `state_attr` according the [Home Assistant Documentation](https://www.home-assistant.io/docs/configuration/templating/)

**Comment by capandcamera** [comment]
That will definitely improve my lovelace yaml!

**Comment by josuabarron** [comment]
That works. I was looking at different codes, but none where working. But yours works!

**Comment by loryanstrant** [comment]
Is this possible for entity cards?

I'm using this:
`type: custom:mushroom-entity-card
entity: sensor.sunbury_line_to_sunbury_from_flinders_street_station_4
primary_info: state
secondary_info: '{{ state_attr(entity, ''platform_number'') }}'
`

And getting this:
_At path: secondary_info -- Expected one of `"name","state","last-changed","last-updated","none"`, but received: "{{ state_attr(entity, 'platform_number') }}"_

The documentation for entity cards backs this error reasoning up, so I didn't know if I was missing something or if it just wasn't possible.

**Comment by piitaya** [comment]
@loryanstrant You have to use template card, not entity card.
