### ISSUE TITLE
RTL Alignment Issue

### ISSUE THREAD

**Issue by planecore** [piitaya/lovelace-mushroom#259]
**Describe the bug**
Cards with an icon have an alignment issue where the icon has a big margin to the right and almost zero margin to the left.
In addition, cards are overlapping each over in horizontal stacks.

**To Reproduce**
1. Add a new card with an icon (for example Entity Card).
2. Add a horizontal stack with two Entity Cards.

**Expected behavior**
The icon should behave similar to the LTR version with the same margin in each side, and cards shouldn’t overlap each over in horizontal stacks.

**Screenshots**
![7684489A-CB83-4AEB-8D05-0192A13C5C28](https://user-images.githubusercontent.com/12946462/162487599-81b37980-166b-483e-9fc4-706c2f9d6d34.jpeg)

**Additional context**
I’m running the latest versions of Mushroom, HACS, Home Assistant, Home Assistant OS and iOS.

**Comment by piitaya** [comment]
Mushroom is not compatible with RTL yet but we will add this support 🙂

**Comment by planecore** [comment]
I changed all the `margin-right` in the code to `margin-left` and it looks great!

I'm not very familiar with Home Assistant tooling, but if there's a way to detect if the current layout is RTL it should be fairly simple to add support!

**Comment by piitaya** [comment]
We can detect it with the `computeRTL` function. I created a PR to add RTL support 😜
