### ISSUE TITLE
Template Card Icon field needs to use the new icon chooser dropdown

### ISSUE THREAD

**Issue by WizBangCrash** [piitaya/lovelace-mushroom#264]
**Is your feature request related to a problem? Please describe.**
The Mushroom Template Card seems to be the odd one out. All other cards support the new icon dropdown chooser, but this card requires you to have to type in the icon reference without showing you the interactive dropdown list.

**Describe the solution you'd like**
Use the same icon dropdown chooser across all cards please

**Describe alternatives you've considered**
N/A

**Additional context**
I am using Mushroom Cards v1.4.0
![Screenshot 2022-04-09 at 13 31 02](https://user-images.githubusercontent.com/3075593/162574262-e1a4e222-72fa-4e93-8cd7-8949ca92fe37.jpg)

BTW Great set of cards. Keep ups the good work :-)

**Comment by piitaya** [comment]
It's by design. Icon is a template like the other fields. That's why there is no icon picker 🙂

**Comment by WizBangCrash** [comment]
@piitaya Thanks. Should have realised and am now using that functionality as you intended it to be used 👍😁
