### ISSUE TITLE
Switch on/off as action

### ISSUE THREAD

**Issue by P-Verbrugge** [piitaya/lovelace-mushroom#266]
**Is your feature request related to a problem? Please describe.**
Feature request. I would like to see the option to turn on or off a switch for the single, hold or double press option.

**Describe the solution you'd like**
Option to flip a switch next to, default action, scene selection, etc. After selecting the option to flip a switch a list with switches you can choose from.

**Comment by piitaya** [comment]
You can select the service option and call the service `switch.turn_on` with your switch id

**Comment by P-Verbrugge** [comment]
Aaaah. :-) I see it now. I wasn't aware I could it that way. Thanks!
