### ISSUE TITLE
Swap cover card icon positions

### ISSUE THREAD

**Issue by damusmf** [piitaya/lovelace-mushroom#269]
**Is your feature request related to a problem? Please describe.**
Using the mushroom cover card, it swaps the position of the up and down arrows vs what the built in home assistant entity card uses.  

**Describe the solution you'd like**
Would like for the up and down arrows to swap positions in the mushroom cover card (up on the left, down on the right).  Whether it be a hard change or a user selectable change. 

**Describe alternatives you've considered**
n/a

**Additional context**
Built-in entities card
![image](https://user-images.githubusercontent.com/31552122/162600581-45be7472-43ab-4187-844e-e8d5903d0ee5.png)

Mushroom Cover card
![image](https://user-images.githubusercontent.com/31552122/162600657-38aa9b86-cb66-4ecd-95c0-8b33df17852a.png)

**Comment by acesyde** [comment]
Hi @damusmf 

Today button commands are like in [ui-minimalist](https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_cover/)

**Comment by bramstroker** [comment]
I have reported similar issue a week ago. https://github.com/piitaya/lovelace-mushroom/issues/227.
Would be nice if there would be an option to switch/swap the behaviour of the buttons and active state.

**Comment by piitaya** [comment]
We can't provide options for everything. We have to make choices. Why do you prefer the home assistant solution?

**Comment by damusmf** [comment]
> We can't provide options for everything. We have to make choices. Why do you prefer the home assistant solution?

Garage is usually in a closed state over 90% of the time.  When the cards extend to the edge of your phone screen, if you swipe to go back a page on your phone this also triggers the up button causing the garage to open.  swiping from left edge has a buffer as the icon is there and you can have it "do nothing" or "more-info" but the arrow on the right you will always trigger.  used card mod to shrink the size of the card as a whole so it only extended about 75% of the screen, have since stopped using the position controls on the card and gone to just requiring a long press to toggle.

**Comment by piitaya** [comment]
I think it's fixed with https://github.com/piitaya/lovelace-mushroom/pull/384
