### ISSUE TITLE
Set entity card decimals

### ISSUE THREAD

**Issue by dasfuu** [piitaya/lovelace-mushroom#271]
So my sensors sometimes produced values like this:
![image](https://user-images.githubusercontent.com/1564453/162616667-8a158484-99d1-499b-8d79-d727fd8784bb.png)
Í would love to round them to one or two decimals in the card only.

**Describe the solution you'd like**
A field to set the max number of decimals or show all of them if not set.

**Comment by piitaya** [comment]
You can define a template sensor to round the values 🙂

**Comment by dasfuu** [comment]
Yes I can do that. But I think this would still be a benifit, since it makes the cards easier to use for other people like my family. And I dont need a bunch of additional sensors. Also I cannot add template sensors through the UI I think?

**Comment by piitaya** [comment]
HA added group and helpers in UI in the 2022.4 release. Maybe, there will be template in the 2022.5.

Which integration send you value like this ? I think it more a rounding issue in this integration.
