### ISSUE TITLE
Would it be possible to reference the {{user}} variable inside of a template?

### ISSUE THREAD

**Issue by patzobil** [piitaya/lovelace-mushroom#278]
Hello,

The idea here is that I can use template card that is already using this {{user}} variable, but a bit deeper into the template itself.. Would be great to be able to substitute for example "person.john" to "person.{{user}}" somehow.

e.g.
Primary Information:
Hello, {{user}}

Icon Color:
{% if is_state("person.{[user]}", "away") -%}
  green
{%- else -%}
  brown
{%- endif %}

**Comment by bemble** [comment]
Hi,

The only way to do so right now is a little bit hacky but it should work:
```jinja2
{% for state in states.person %}
  {% if state.name == user %}
    {{ 'green' if is_state(state.entity_id, "away") else 'brown' }}
  {% endif %}
{% endfor %}
```

**Comment by piitaya** [comment]
You can also do this:
```jinja2
{% set user_entity_id = expand(states.person | selectattr("name", 'eq', user))
  | map(attribute='entity_id')
  | first %}
{{ 'green' if is_state(user_entity_id, "away") else 'brown' }}
```

**Comment by patzobil** [comment]
> You can also do this:
> 
> ```
> {% set user_entity_id = expand(states.person | selectattr("name", 'eq', user))
>   | map(attribute='entity_id')
>   | first %}
> {{  is_state(user_entity_id, "away") | iif('green', 'brown') }}
> ```

Thanks a lot! Seems I need to get better in jinja templating 😂
That worked perfect

**Comment by patzobil** [comment]
> Hi,
> 
> The only way to do so right now is a little bit hacky but it should work:
> 
> ```
> {% for state in states.person %}
>   {% if state.name == user %}
>     {{ 'green' if is_state(state.entity_id, "away") else 'brown' }}
>   {% endif %}
> {% endfor %}
> ```

That worked great! Thanks!

**Comment by gbcatrinoiu** [comment]
can it also be used in the mushroom-person-card?

```
- type: custom:mushroom-person-card
   entity: person.personName
   icon_type: entity-picture
   secondary_info: state
```
