### ISSUE TITLE
Custom: Mushroom Vacuum Card is not displayed

### ISSUE THREAD

**Issue by F0min-ivan** [piitaya/lovelace-mushroom#279]
![Screenshot_1](https://user-images.githubusercontent.com/52936590/162712582-65a2a224-8703-4979-aec0-ff76a4383f36.png)

**Comment by acesyde** [comment]
Hi @F0min-ivan 

Sorry for that, actually the vacuum card is available in the 1.4.0, @piitaya has fixed the README

**Comment by piitaya** [comment]
It will be available in the 1.5.0 🙂
