### ISSUE TITLE
Large Icon on Light Card (if not others)

### ISSUE THREAD

**Issue by dmyoung9** [piitaya/lovelace-mushroom#283]
**Is your feature request related to a problem? Please describe.**
It would be great to have an option for a "large icon", especially on the Light Card, if not others.

**Describe the solution you'd like**
Just a bigger icon 😁 Take the standard HA Light Card, for example:
![image](https://user-images.githubusercontent.com/101432365/162826898-67270609-f61d-4da1-b701-7085d355f396.png)

**Describe alternatives you've considered**
Using other cards or just dealing with the small icon 😅 

**Additional context**
What a Mushroom Light Card currently looks like:
![image](https://user-images.githubusercontent.com/101432365/162826845-6c43cbfc-2071-4ffb-897c-e8f414cd2753.png)

**Comment by KameDomotics** [comment]
I also join in this request.  It would be great to be able to set the size of the icons (e.g. px or%)
Thank's for your job!

**Comment by piitaya** [comment]
With the new [1.8.1 release ](https://github.com/piitaya/lovelace-mushroom/releases/tag/v1.8.1), you can set the size using theme variables 🙂
