### ISSUE TITLE
cant see vacuum card

### ISSUE THREAD

**Issue by lior612** [piitaya/lovelace-mushroom#285]
after update i cant get the vacuum card

**Comment by piitaya** [comment]
I think you have a cache issue. What version did you install?

**Comment by lior612** [comment]
Do you mean ver of home assistant?

בתאריך יום ג׳, 12 באפר׳ 2022, 10:36, מאת Paul Bottein ‏<
***@***.***>:

**Comment by lior612** [comment]
Hi
I cleaned the cache and it fix it
Thanks

בתאריך יום ג׳, 12 באפר׳ 2022, 11:31, מאת Paul Bottein ‏<
***@***.***>:
