### ISSUE TITLE
Vacuum card not showing in dashboard edit

### ISSUE THREAD

**Issue by spicerackk** [piitaya/lovelace-mushroom#294]
**Describe the bug**
Mushroom Vacuum Card is not showing up after updating to current version.

**To Reproduce**
1. Edit dashboard
2. Click on add card
3. Search mushroom 
4. All cards except vacuum card showing

**Expected behavior**
New vacuum card to be available.

**Comment by kubiksamek** [comment]
Hi, you need to clear your cache. See https://github.com/piitaya/lovelace-mushroom/issues/285

In chrome, open devtools, right click on reload button and click on Empty cache and hard reload.

**Comment by spicerackk** [comment]
So I did that and then it showed up, but now it keeps disappearing and showing "custom element doesn't exist". I have emptied cache and hard refreshed multiple times, restarted HA with no luck. It's extremely intermittent.

**Comment by kubiksamek** [comment]
Do you see this, when you open devtools?
```
🍄 Mushroom 🍄 - 1.5.0
```

**Comment by spicerackk** [comment]
Where in devtools would I see that?

**Comment by kubiksamek** [comment]
In console log

**Comment by spicerackk** [comment]
Sorry, I am unsure where to find that

**Comment by spicerackk** [comment]
I can confirm that Mushroom v1.5.0 is installed, I removed the frontend, restarted HA then installed it again.

**Comment by spicerackk** [comment]
Even after updating to the latest version (1.6.2), vacuum card is still not displaying when adding a card.

**Comment by spicerackk** [comment]
@piitaya any update on this at all? At a complete loss. Vacuum and Media cards aren't showing up at all.

**Comment by piitaya** [comment]
Can you provide some screenshots? I think it's an issue on your side, not a Mushroom issue but it's complicated to help because we don't have a lot of information 😅

**Comment by atkjedi** [comment]
I had the same issue in windows 11 edge, but only on one system.

clearing the cache resolved it.

**Comment by spicerackk** [comment]
> I had the same issue in windows 11 edge, but only on one system.
> 
> clearing the cache resolved it.

I've activated dev tools and cleared cache and hard reset multiple times with no luck at all. 



> Can you provide some screenshots? I think it's an issue on your side, not a Mushroom issue but it's complicated to help because we don't have a lot of information 😅

https://imgur.com/n49oTYX this is a screenshot of what happens when I search for mush in cards. I've since tried in chrome as well, and am having the same issue happen. I know someone else on discord I was chatting with was unable to get the vacuum card to show up in their system as well after updating through both HACS and as well as manually importing the .js file.

**Comment by kubiksamek** [comment]
Today after updating to 1.6.2, I reloaded HA with opened devtools and I saw that I had still version 1.5.0, so I had to "Empty cache and hard reload", and then I saw correct 1.6.2. I had same "issue" on my iPhone, so I had to go to App settings -> Debugging -> Reset frontend cache

![Screenshot 2022-04-18 at 17 06 29](https://user-images.githubusercontent.com/18164177/163828549-ae4cd067-8be8-4efa-af78-f77635f3cb4e.png)

Can you confirm that you see this in devtools (or 1.5.0 at least)?
![Screenshot 2022-04-18 at 17 08 55](https://user-images.githubusercontent.com/18164177/163828907-6c99acab-33ad-4340-8bd0-efee7f39f25b.png)

**Comment by spicerackk** [comment]
I am unsure where to find 
> this in devtools (or 1.5.0 at least)? ![Screenshot 2022-04-18 at 17 08 55](https://user-images.githubusercontent.com/18164177/163828907-6c99acab-33ad-4340-8bd0-efee7f39f25b.png)

I have emptied cache and hard reloaded in edge multiple times already. It also doesn't work in chrome, which I have emptied cache and hard reloaded.

**Comment by kubiksamek** [comment]
I meant browser console:
![Screenshot 2022-04-18 at 21 32 53](https://user-images.githubusercontent.com/18164177/163865533-c93c0344-764c-4b77-b2bd-1d2a66709543.png)

**Comment by piitaya** [comment]
@spicerackk HA 2022.4 is required for the latest Mushroom version. Do you have this version?

**Comment by spicerackk** [comment]
> I meant browser console: ![Screenshot 2022-04-18 at 21 32 53](https://user-images.githubusercontent.com/18164177/163865533-c93c0344-764c-4b77-b2bd-1d2a66709543.png)

![image](https://user-images.githubusercontent.com/31406866/163894755-78bc9c0b-1322-4c6a-8e64-627e48517c64.png)

I have no idea how it is showing a beta version. 

@piitaya yeah I have the latest update for HA as well. I'd say the beta is the issue but not sure how that has happened.
