### ISSUE TITLE
Make cover second title selectable

### ISSUE THREAD

**Issue by tuanha2000vn** [piitaya/lovelace-mushroom#297]
![Screenshot at Apr 14 01-11-47](https://user-images.githubusercontent.com/2765517/163244410-c7a45bab-9466-45c4-9fa9-0c6c93e61b80.jpeg)

Currently Cover second title only support state. It would be great if we can select other attribute. Last changed state for example.

Please make it happen.

Thank you

**Comment by KTibow** [comment]
Fixed in Mushroom 2.0.0, consider closing?
