### ISSUE TITLE
Cover card disabled if unknown status

### ISSUE THREAD

**Issue by EMP83** [piitaya/lovelace-mushroom#298]
Hello again.
I use Somfy RTS motors for my covers and they do not report the state to home assistant. 
After each restart of home assistant they go into state unknown until first use.  
Every time they go into an unknown state mushroom cover card commands are disabled.
![1](https://user-images.githubusercontent.com/36104474/163248702-0a1e77a7-2943-4da4-bdc7-165e9eb53a57.jpg)

To reactivate the card I have to use the home assistant commands once to change the state of cover.
![3](https://user-images.githubusercontent.com/36104474/163248740-6b701dcb-1818-4a14-b0a2-99cf0e8fc6d1.jpg)

![4](https://user-images.githubusercontent.com/36104474/163248777-17e6b913-deeb-4f72-b6a5-acfab0fa7c79.jpg)

Can be fixed this behavior please?
Thank You

**Comment by Stinocon** [comment]
Hello everyone!
I confirm, I think I have the same problem with some cover entities generated by the Tuya addon.

![immagine](https://user-images.githubusercontent.com/2804739/163344210-86081723-bc26-408e-b3d5-24ffb4ec6efa.png)

As you can see from the above image the entity works perfectly if used with a "standard" card. However, the commands are not available in the Mushroom card.
I'm not 100% sure because it's my parents' instance and I don't use it much, but I think the problem showed up with the latest Home Assistant update.

**Comment by acesyde** [comment]
Hi @Stinocon and @EMP83 can you capture the state (when it's doesn't work and when it's work) of your entity in the developer tools ? and share it here please

Thank you

**Comment by piitaya** [comment]
Can you provide the integration of your cover ? May be it's an issue related of a custom integration instead of a Mushroom one.

**Comment by EMP83** [comment]
State when not working:
<img width="796" alt="Captură de ecran din 2022-04-14 la 13 34 42" src="https://user-images.githubusercontent.com/36104474/163383284-98b2206a-939f-4c9b-8517-62a4e2ea259f.png">

State when working:
<img width="796" alt="Captură de ecran din 2022-04-14 la 13 35 42" src="https://user-images.githubusercontent.com/36104474/163383323-860b95d2-1333-4437-9a1b-12b3b3bc2e8f.png">

I use mqtt to communicate with tostcorp ( covers hub) and it's pretty simple, only 4 commands:
UP
Down
Stop
Pairing

Cover config:

- platform: mqtt
  unique_id: 6d2f20bd-2e96-4295-b8dd-bd5c0d785b08
  name: Rulou Dormitor Stânga
  command_topic: volet/dormitor_stanga
  payload_open: "u"
  payload_close: "d"
  payload_stop: "s"
  state_open: "open"
  state_closed: "closed"

I also want to specify that it works without problems 
with the native home assistant cover commands even if it is in an unknown state.

**Comment by EMP83** [comment]
Thank You

**Comment by piitaya** [comment]
It's strange that your entity is `unknown` and not `closed`. But it's more logic to not consider unknown `state` as `unavailable` 🙂

**Comment by EMP83** [comment]
I don't think it can be closed because the cover do not report this to the home assistant, in fact it reports nothing. The home assistant will receive the first report only after the first press up or down. 
For example, the stop command does not report any state. If the roller does not move and i press the stop command, it goes to the favorite position, however if before it was in an unknown state will remain in this state because nothing has been reported to the home assistant. As u cand see in my config only reports: Open and Closed

I hope it makes sense
