### ISSUE TITLE
Configuration for theme mode (dark & light)

### ISSUE THREAD

**Issue by welcoMattic** [piitaya/lovelace-mushroom#299]
**Is your feature request related to a problem? Please describe.**
I would like to take control of theme mode : use light for day, and dark for night (I use [a blueprint](https://community.home-assistant.io/t/light-dark-theme-switcher-based-on-sun/255455) to automate this).

**Describe the solution you'd like**
I would like to use "mode" field to control the mode of Mushroom theme.
<img width="615" alt="image" src="https://user-images.githubusercontent.com/773875/163272245-2d4f39ba-aa74-49ca-934f-149186e85f2b.png">

**Describe alternatives you've considered**
I can't find any alternative

Thanks to consider it

**Comment by piitaya** [comment]
Mushroom support Light/Dark/Auto theme from the profile interface. I don't known want this mode doing. Impossible to use it even with the default HA theme.

**Comment by welcoMattic** [comment]
Oh nice, IDK for the setting in profile. Thanks :+1:
