### ISSUE TITLE
Feature request | Alarm card hide digit panel

### ISSUE THREAD

**Issue by joaovitoriasilva** [piitaya/lovelace-mushroom#306]
**Is your feature request related to a problem? Please describe.**
In my setup, I do not need to input a code to arm the alarm, so the option to add the alarm card with the digit panel hidden would be awesome.

**Describe alternatives you've considered**
Entity card that on click calls service to arm alarm, but it is prone to accidental arming.

**Comment by idefxH** [comment]
You can achieve it with [Lovelace Card Mod](https://github.com/thomasloven/lovelace-card-mod) from [Thomas Lovén](https://github.com/thomasloven/lovelace-card-mod/commits?author=thomasloven), e.g.:

```
type: custom:mushroom-alarm-control-panel-card
entity: alarm_control_panel.home
style: |
  #keypad, mushroom-textfield {
    display: none !important;
  }
states:
  - armed_night
  - armed_away

```

**Comment by joaovitoriasilva** [comment]
Hello @idefxH thank you for the help and the suggestion however, I believe one of the objectives of the lovelace-mushroom integration is to not use additional integrations and I would like that.
