### ISSUE TITLE
Request for a card for lock domain

### ISSUE THREAD

**Issue by xBourner** [piitaya/lovelace-mushroom#313]
Hi i asked myself why no one made a "lock card".

I think it would look very cool and would fit better than an mushroom entity card.
Layout should be the same as the mushroom cover card.

You should have three buttons under the primary (and secondary) info.
The left one should be an unlock, the middle one a lock and the right one to open the lock.

Service calls would be lock.unlock (left), lock.lock (middle) and lock.open (right).
If the state of the lock is locked the middle button should be not accessible. Also the same for the left button when the lock is unlocked.

The way locks work with your mushroom entity card is great. It toggles the lock but i am not able to open the door without a service call from HA. So i think is quite a nice idea. 

Please let me know what you think about. The other cards rock!

**Comment by NimlothPL** [comment]
Thanks for adding it - works great.

Some locks (like Tedee) have "open" action to pull string when lock is unlocked.
Can it be also added?

**Comment by piitaya** [comment]
Yep, it will be added in a next release 😉

**Comment by xBourner** [comment]
Nice one. Thank you!

**Comment by acesyde** [comment]
@NimlothPL can you share some screenshot about the standard HA card for your integration and can you share the state of this entity ? thk you :)

**Comment by xBourner** [comment]
I got a Nuki. My standard card does not provide an „open action“ on default. 
i added this with a button card which calls a service „lock.open“

**Comment by NimlothPL** [comment]
> Yep, it will be added in a next release 😉

With your release speed then in like 5 minutes ;)

**Comment by xBourner** [comment]
is this update already the next release which should include lock.open action?

**Comment by acesyde** [comment]
@xBourner Can you check the PR, I'm not sure about the unlocked state if the "open" icon should be here or not

**Comment by xBourner** [comment]
> @xBourner Can you check the PR, I'm not sure about the unlocked state if the "open" icon should be here or not

i would say open should be only available if the door is in unlocked state. otherwise you should need to unlock first.
anyway to have the control buttons on the bottom not the right?

**Comment by piitaya** [comment]
Yep, buttons position depends on the layout you choose for your card 🙂

**Comment by xBourner** [comment]
ok i will wait for next release
looks good :)

**Comment by acesyde** [comment]
@xBourner thks now the "open" button should be only visible when the state is "unlocked"

**Comment by piitaya** [comment]
It's release (1.6.1 version)

**Comment by NimlothPL** [comment]
@piitaya  just want to say thanks - it's perfect now 💯

**Comment by piitaya** [comment]
@acesyde did all the work for the lock card 😅

**Comment by NimlothPL** [comment]
@acesyde big thanks 🙏👍 awesome job
