### ISSUE TITLE
Button Card Request 

### ISSUE THREAD

**Issue by Noob25930** [piitaya/lovelace-mushroom#32]
Requesting if you could include a button card. I have alot of switches connected to lights and fans which dont show up in either light or fan cards.

I am new to github, couldnt find the button to request feature. Love the cards. Thanks for sharing.

**Comment by pierrecle** [comment]
Hi,

Thanks for your request.
You can already add button card: add an entity card with your `input_boolean`, on tap action, call the service `input_boolean.toggle`, select the Wright entity to toggle and voilà.

**Comment by piitaya** [comment]
@pierrecle I think we can add the `toggle` to `tap_action` and `hold_action` for entity card to facilitate the switch or button usage 🙂

And the documentation need to be updated too 👍

**Comment by piitaya** [comment]
I re-open this issue for the documentation improvement 😅

@Noob25930 You can update to the latest version to use the `toggle` tap action with entity card.

**Comment by Noob25930** [comment]
Thank you both of ya'll for your answers @pierrecle @piitaya . I will try that. Again, fantastic work.

**Comment by dtar72** [comment]
Is it also possible to add 'scene.turn_on' option to the entity card tap action?
Using 'toggle' to activate scenes gives an error due to the lack of a 'scene.turn_off' service.

Thanks for your efforts both this is a fantastic set of cards.

**Comment by piitaya** [comment]
You can use any service you want by choosing the call service action in tap action 😉

**Comment by dtar72** [comment]
Awesome thanks for clarifying, I was pulling my hair out and missed the obvious.

**Comment by pierrecle** [comment]
@piitaya should we close this issue or an action still needed?

**Comment by piitaya** [comment]
We can close it and we will add a task : improve doc
