### ISSUE TITLE
Alarm control panel not working anymore

### ISSUE THREAD

**Issue by tnagels** [piitaya/lovelace-mushroom#331]
I use the Satel Integra integration for control of my alarm. Since the Upgrade of Mushroom to 1.6, I can't switch the alarm on/off anymore. The buttons to control the alarm are greyed out and don't do anything when I click them. 

Switching on and off with the Home Assistant built-in control panel (reached by clicking more info) does work as expected.

**Comment by larry-glz** [comment]
Same here w Envisalink and Arlo.

**Comment by JohnnyM84** [comment]
Same for me

**Comment by Osjuh** [comment]
Same for me, with Somfy.

**Comment by hebbister** [comment]
Same for me
