### ISSUE TITLE
All Mushroom card are blank

### ISSUE THREAD

**Issue by smashteevee** [piitaya/lovelace-mushroom#334]
I installed Mushroom and configured manually in my Lovelace > Resources config, per your instructions, but when adding cards, the preview cards appear in the list, but visually all appear blank.

In Chrome Developer Tools, I see multiple Console errors, like:

```
 🍄 Mushroom 🍄 - 1.6.1
mushroom.js:1369 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at Rr.render (mushroom.js:1369:38)
    at Rr.update (mushroom.js:37:412)
    at Rr.performUpdate (mushroom.js:25:5057)
    at Rr.scheduleUpdate (mushroom.js:25:4704)
    at Rr._$E_ (mushroom.js:25:4612) 
```

Is there a minimum version required? I run HA Core 2021.4.5 and that is my first guess (but I couldn't find any mention in your README)

Version | core-2021.4.5
-- | --
Installation Type | Unknown
Development | false
Supervisor | false
Docker | false
Virtual Environment | false
Python Version | 3.9.2
Operating System Family | Linux
Operating System Version | 4.4.210-gae6d0ab37d61

Thank you for your work!

**Comment by acesyde** [comment]
Hi @smashteevee 

Actually mushroom works well with 2022.x can you upgrade your home assistant ?

**Comment by piitaya** [comment]
Mushroom use the icon-picker and ha-form to build the editor. You need to have the latest version of HA to make it works.

**Comment by smashteevee** [comment]
Ack - running HA Core on Android via Termux so will need to do some upgrading I've been postponing. Thanks for letting me know. I'll close this for now since it sounds like 2021.4.5 is too old. Thanks!
