### ISSUE TITLE
[Idea] Light brightness slider in one row

### ISSUE THREAD

**Issue by Stooovie** [piitaya/lovelace-mushroom#34]
Hi, Mushroom is incredibly nice! I'd love an option to have the light brightness slider in the name row, so the entire control only takes one row instead of two. Thanks!

**Comment by piitaya** [comment]
Somethings like that ?
 
<img width="468" alt="Capture d’écran 2022-02-05 à 14 23 34" src="https://user-images.githubusercontent.com/5878303/152643928-1fda09fb-a5ee-4153-a3ed-c0775bdac5d1.png">

Maybe we can add an option `inline_controls` for that?

**Comment by Stooovie** [comment]
Exactly! Or even put the slider behind the entity name (but that may introduce color contrast issues) :) Thank you!

**Comment by Ulrar** [comment]
Absolutely agreed, I'm trying to make per room group card and it's a bit tough to get Light cards and entity cards (for smart plugs controling lights, in the switch domain) to line up cleanly on one line.
The ability to get the light card to only take one line would make that look good, +1 !

**Comment by Stooovie** [comment]
OT: I must say I absolutely love the haptic feedback implementation on the iPhone. That's something the default Lovelace stuff should have.

**Comment by Dielee** [comment]
Yeah, this would be nice. Until this feature is available, just use an vertical stack! 
![2022-02-07 09_31_49-Home - Home Assistant](https://user-images.githubusercontent.com/45101649/152752198-6b51705b-3407-4161-946b-3820801dd1b8.png)

**Comment by redford-jones** [comment]
Another option that I'd like to see is to be able to hide the slider if the current state of the light is 'off'

**Comment by posreg** [comment]
> Another option that I'd like to see is to be able to hide the slider if the current state of the light is 'off'

I'm doing this by Conditional Card
![image](https://user-images.githubusercontent.com/80816020/153058621-fe9768cc-d336-41a1-b930-d90f9c42584d.png)

hide slider when other than `on`, show when on

**Comment by simon2d** [comment]
+1 for one row light.
Would be also nice to have a height attribute so we can make the slider even more compact if needed.
I'm currently using it for a mobile device and less real estate on slider would be a great help.

Thanks for the amazing work on this btw.

**Comment by brandensilva** [comment]
Also would love to see this to reduce vertical space. It likely can get extended to be reused for other entities as common layout option too.

For example, this is the mushroom alarm card with vertical disabled:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/200190/153640843-0b97ce7e-bd6e-4f88-9145-aae787d76cfa.png">

Here is how it could look like with a layout mode of horizontal and vertical disabled:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/200190/153641527-d74294bc-04ff-49da-a401-5bfa08f919f1.png">

This looks possible with `flex-direction: row; justify-content: space-between; align-items: center;` on the container and some modifications to some of the padding on the mushroom entity.

This sets us up for getting closer to Yuhang's horizontal card layouts that are rounded:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/200190/153642094-c0775d2c-1846-4cbd-a4f6-7de3ffd5243c.png">

**Comment by brandensilva** [comment]
I wanted to share this as well given there are constraints you have to deal with doing this approach:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/200190/153695697-89fbcbad-f23b-47f8-8aa4-768d089ea448.png">

This is a 50/50 split with space reserved for text and the other portion reserved for actions. I feel the look and usability is acceptable but users will need to be more careful about not ending up in situations where they break these constraints or risk text or elements collapsing to a new line thus negating the main benefit of this approach.

It also means this mode is primarily used for full-width columns and not half-columns in a horizontal stack. Need to think through how to gracefully handle these use cases. One initial thought is maybe the horizontal layout mode is ignored and things function with vertical flow as if the layout option didn't exist.

**Comment by Stooovie** [comment]
Wouldn't it be possible to have the slider extend (begin) under the text? It would probably be bad from an UX perspective, right?

**Comment by simon2d** [comment]
I did a mock up of how it could look like with and without title with light and dark themes.. Don't hesitate if you want me to try different versions since it's all in photoshop and split in layers. It's pretty easy for me to change things around if needed. I hope this helps.

![Mushroom_light_theme](https://user-images.githubusercontent.com/35505104/153757261-9d69f417-caac-427c-8237-b241005313d6.jpg)
![Mushroom_dark_theme](https://user-images.githubusercontent.com/35505104/153757268-01dc5a54-eb27-4746-a6ec-8b4f0bf36bf3.jpg)
![Mushroom_light_theme_with_title](https://user-images.githubusercontent.com/35505104/153757273-841f1dba-91f4-47f0-b42d-d4887cfcbd70.jpg)
![Mushroom_dark_theme_with_title](https://user-images.githubusercontent.com/35505104/153757277-498dbcc5-ba0c-42b5-a0ae-8d55615508df.jpg)

**Comment by piitaya** [comment]
We will not propose such slider in Mushroom because it's too different than other cards. 
If you want this, you can use this card : https://github.com/mattieha/slider-button-card#general

**Comment by brandensilva** [comment]
> Wouldn't it be possible to have the slider extend (begin) under the text? It would probably be bad from an UX perspective, right?

It's doable but not great code to write. Because each of these sections is separated as two different components or elements, they cannot easily mingle into each other like that without a bit of hackery. You could alter how it renders based on those options but that's a lot of code for little benefit.

**Comment by Stooovie** [comment]
I agree, it wouldn't be pretty or very useful anyway as the slider would be very close to the tappable button.

**Comment by pierrecle** [comment]
@piitaya will give a first answer to this issue in 1.0.6 ;)

**Comment by piitaya** [comment]
I think the `vertical` option can be removed and can be replaced by a `layout` options : `default` `vertical` `horizontal`.
And we can a backward compatibility to avoid breaking change.

There will be 3 layouts :
# Default
![Capture d’écran 2022-02-15 à 17 46 20](https://user-images.githubusercontent.com/5878303/154108692-8164206b-b410-40b4-8ad5-f30bda01807c.png)
# Vertical
![Capture d’écran 2022-02-15 à 17 46 38](https://user-images.githubusercontent.com/5878303/154108688-eacf1dac-1d21-4647-9f4a-c714ea67dcf6.png)
# Horizontal
![Capture d’écran 2022-02-15 à 17 47 30](https://user-images.githubusercontent.com/5878303/154108685-b8cfbda2-57db-4234-a400-fe847ffc2403.png)

**Comment by cyrilphoenix71** [comment]
Clearly a good proposition ! :)
With collasped option who hide the sliders and controls when light is off, it will be perfect :)

**Comment by Stooovie** [comment]
That's oh so pretty! Thank you!

**Comment by simon2d** [comment]
Wow really nice!!!!
Can't wait to try it :-).

Thanks

**Comment by brandensilva** [comment]
> We can add `collapse_controls` to hide controls when entity is considered `off` too. I think it's easy to understand if `collapse` and `layout` are two different options.

Yeah collapse could work well too in either vertical or horizontal layout. For example I imagine you could collapse the vertical version as well where the icon and text are on the same horizontal axis to reduce a little bit of that vertical space.

**Comment by cyrilphoenix71** [comment]
Perfect
