### ISSUE TITLE
Template Card and Chip don't display correctly with RGB values for Icon Color

### ISSUE THREAD

**Issue by aagrifo** [piitaya/lovelace-mushroom#343]
**Describe the bug**
The Template Card (and Chip) fail to properly display under certain conditions relating to modifying color using comma separate RGB values. In Chrome Dev Tools I get _TypeError: t.startsWith is not a function_ which appears to be coming from src/utils/colors.ts line 31 _color.startsWith('#')_. It seems like a number is being passed for color which causes color.startsWith to fail. I modified my compiled js to change the function to t.toString().startsWith which seemed to fix the issue, but I haven't investigated all scenarios.

**Expected behavior**
The template card renders the appropriate color and details based on the provided template

**To Reproduce**
It seems to be intermittent, but I have templates that determines a color based on a state's value. Here's a couple of configurations that are failing:
```
type: custom:mushroom-template-card
entity: climate.hallway
primary: '{{ state_attr(entity, ''friendly_name'') }}'
secondary: >-
  {{ state_attr(entity, 'hvac_action')  | capitalize }} - {{
  state_attr(entity,'current_temperature') }} /  {{ state_attr(entity,
  'temperature')}}
icon: mdi:thermometer
icon_color: |-
  {%- if state_attr(entity, 'hvac_action') == 'heating' -%}
  red
  {%- elif state_attr(entity, 'hvac_action') == 'cooling' -%}
  blue
  {%- elif state_attr(entity, 'hvac_action') == 'idle' -%}
    {% if states(entity) == 'heat' -%}
    247,173,173
    {% elif states(entity) == 'cool' -%}
    173,173,247
    {% endif -%}
  {%- else -%}
  {%- endif -%}
multiline_secondary: false
```

```
type: custom:mushroom-chips-card
chips:
  - type: template
    entity: sensor.bathroom_t_and_h_sensor_battery_level
    content: >-
      {{ state_attr(entity, 'friendly_name') | lower | replace('
      battery','') | replace(' level','') | title + " " + states(entity) }}
    icon: >-
      mdi:battery
  
      {%- if is_state_attr(entity, 'battery_charging', true) or
      is_state_attr(entity,'charging',true) -%}-charging
  
      {%- endif -%}
  
      {%- if 0 < (states(entity) | int(0) / 10) <= 100 -%}
        -{{ (states(entity) | int(0) / 10) | round(0) * 10 }}
      {%- else -%}
        {%- if (states(entity)  | int(0)) / 10 == 0 -%}-outline
        {%- endif -%}
      {%- endif -%}
    icon_color: >-
      {{ 225 if states(entity) | int(0) <=50 else (1 - ((states(entity) |
      int(0) - 50) / 50))*255*0.80, 225 if states(entity) | int(0) >=50 else
      ((states(entity) | int(0) / 50))*255*0.80, 0 }}
    tap_action:
      action: more-info
```

**Screenshots**

![image](https://user-images.githubusercontent.com/54122039/163681600-fdbcee09-0b98-4073-a350-bab216a1ea9e.png)
![image](https://user-images.githubusercontent.com/54122039/163681911-398e3630-fd40-43eb-9974-8b00c9c8a68a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 100.0.4896.127

**Comment by piitaya** [comment]
You can use hexa code instead of RGB value. Example : #ff00ee

**Comment by aagrifo** [comment]
In the first configuration (the one using a climate entity) I can, that is using static colors. But the second is creating a color gradient based on the value of the battery which I don't think I would be able to convert to a hexa code value.

**Comment by piitaya** [comment]
You can convert each number to hexa value with 

```jinja2
{{ "%0x" | format( value | int }}
```

**Comment by aagrifo** [comment]
Thank you, that does work. Just for anyone in the future, the new working format for the second configuration is below. However, this does still seem to be a bug. Unless RGB values for the colors are not supported, then I guess this would be an enhancement.

```
type: custom:mushroom-chips-card
chips:
  - type: template
    entity: [[BATTERY ENTITY]]
    content: >-
      {{ state_attr(entity, 'friendly_name') | lower | replace('
      battery','') | replace(' level','') | title + " " + states(entity) }}
    icon: >-
      mdi:battery
  
      {%- if is_state_attr(entity, 'battery_charging', true) or
      is_state_attr(entity,'charging',true) -%}-charging
  
      {%- endif -%}
  
      {%- if 0 < (states(entity) | int(0) / 10) | round(0) <= 100 -%}
        -{{ (states(entity) | int(0) / 10) | round(0) * 10 }}
      {%- else -%}
        {%- if ((states(entity)  | int(0)) / 10) | round(0) == 0 -%}-outline
        {%- endif -%}
      {%- endif -%}
    icon_color: >-
      {{ "#" + "%02x" | format((225 if states(entity) | int(0) <=50 else (1 -
      ((states(entity) | int(0) - 50) / 50))*255*0.80) | int(0)) + "%02x" |
      format((225 if states(entity) | int(0) >=50 else ((states(entity) | int(0) /
      50))*255*0.80) | int(0)) + '00' }}
    tap_action:
      action: more-info
```

**Comment by KTibow** [comment]
Can we close this issue as it's resolved?

**Comment by aagrifo** [comment]
Resolved with workaround
