### ISSUE TITLE
The "template card" does not work as expected

### ISSUE THREAD

**Issue by riwich** [piitaya/lovelace-mushroom#350]
The usual "fields" process templates perfectly. However, no templates are interpreted in the "Actions". I would like to use the action "URL" for an action type and a template should serve as the target. Unfortunately, template is not converted in actions.
Will this be possible in a future version?

**To Reproduce**
1. create a mushroom teplate card
2. select any action choose action type "URL"
3. insert as target http://{{ states('sensor.any_sensor_ip') }}
4. test the selected action, the target is: "`http://%7B%7B%20states%28%27sensor.any_sensor_ip%27%29%20%7D%7D/`"

**Expected behavior**
Open a browser-tab with the IP-Address inside the template.

**Additional context**
Home Assistand Core Version: 2022.4.5
Mushroom Version: 1.6.2

**Comment by piitaya** [comment]
The action doesn't support template and we can not add template support because it will be to complicate. Also Mushroom only standard action editor so the action editor of home assistant should be modified.

**Comment by riwich** [comment]
OK, that makes sense! 
**Thank you for your great work!**
