### ISSUE TITLE
Shorter light slider heights

### ISSUE THREAD

**Issue by OverZealous** [piitaya/lovelace-mushroom#358]
**Is your feature request related to a problem? Please describe.**
A minor improvement, but the mushroom light sliders are fairly tall when stacked, and just as tall as an entity row when laid out horizontal. I would really like to be able to keep the general look, but shrink the slider height to something like 16px.

I tried using cardmod to change the styling, but I could not figure out a way to target the `::slotted()` light slider height, and it's also not set via variable.

**Describe the solution you'd like**
It would be nice to have an option for a much shorter light slider to give a more compact feel for dimmable lights.

**Describe alternatives you've considered**
I tried using cardmod, but could not figure out how to target the correct element. If there's a way to use card mod for this, then I'd be fine with that solution instead.

**Additional context**
You can see how much space these take up on a desktop environment here:
![Screen Shot 2022-04-18 at 10 19 40 AM](https://user-images.githubusercontent.com/965719/163821583-deffa66f-cd40-4f64-9548-9b69cf5e119a.png)

Thanks!

**Comment by piitaya** [comment]
That something we can bring to theme 🙂 We will take your suggestion as consideration when improving theme support 🙂

**Comment by apivaral** [comment]
The best UI for sliders is the one in Samsung phones, it’s a 1px bar with green large circle, on start slide, the area of the slider turns into a big slider area like it looks all the time now, check it out :)

**Comment by piitaya** [comment]
The control height can now be configured with themes with the 1.8.3 version.
