### ISSUE TITLE
Preset options for cover card

### ISSUE THREAD

**Issue by Smiggel** [piitaya/lovelace-mushroom#359]
Feature request:

I really like the cover card. However, I am missing one thing right now and that is the option do some preset options for how far the curtain should be opened.

**Describe the solution you'd like**
Something like this: https://github.com/finity69x2/cover-position-preset-row. I would like to see it as an option that you can enable/disable. An row below the controls with preset buttons would be really nice in my opinion.

**Describe alternatives you've considered**
Tested this: https://github.com/finity69x2/cover-position-preset-row. This works, but the layout does not match with Mushroom.

**Comment by piitaya** [comment]
Presets are not native in Home Assistant. We prefer to prioritize official features to Mushroom for now. We can not bring all feature from all cards in Mushroom 😅

**Comment by phgie** [comment]
Is this still your stance? A preset option would be nice for Linak desks for example...
