### ISSUE TITLE
Vacuum Start Button hidden by label

### ISSUE THREAD

**Issue by capandcamera** [piitaya/lovelace-mushroom#361]
**Describe the bug**
On smaller screens the Vacuum Play button seems to be hidden by the label of of the vacuum

**To Reproduce**
Set Dev Tools to a small phone resolution:
iPhone SE, iPhone 13 Mini, iPhone XR

**Expected behavior**
Truncate Text if required but show buttons

**Screenshots**
![IMG_0951](https://user-images.githubusercontent.com/79606905/163942006-50aa0d5c-9588-4356-a247-d4e202a78285.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Mini
 - OS: 15.4.1
 - Browser Companion App / Safari

**Comment by piitaya** [comment]
For now the layout is 50% 50% because we want consistency with the UI. For now you have 2 choices :
- use default layout.
- only display 3 buttons with vertical layout (that why Mushroom allow you to choose which button you want to display)

**Comment by capandcamera** [comment]
Thanks @piitaya I'll set it to only 3 buttons for now
