### ISSUE TITLE
Person Card: Add secondary info (like last changed)

### ISSUE THREAD

**Issue by goyney** [piitaya/lovelace-mushroom#365]
**Is your feature request related to a problem? Please describe.**
I would like my people cards to state how long someone has been in a given zone, specifically by using Last Changed, but really just enabling secondary info on the cards would solve the problem.

**Describe the solution you'd like**
Allow secondary information to be specified on Person Card.

**Describe alternatives you've considered**
The Entity Card almost does this, but it doesn't allow display of State (home, away) and Last Changed. I also can't use the person's picture on an entity card.

**Comment by acesyde** [comment]
Hi @goyney,

You can use template card if you want for that 

![image](https://user-images.githubusercontent.com/958435/164174046-1d4a948c-aff1-408a-99f2-1c6f6be3fb09.png)

**Comment by goyney** [comment]
I cannot change the icon to be the person's picture though, so that really isn't a solution.

**Comment by acesyde** [comment]
@piitaya what do you think about adding the possibility to select the primary and second information level in the editor like other cards ?
