### ISSUE TITLE
Failed to change light temperature

### ISSUE THREAD

**Issue by agustusbotti** [piitaya/lovelace-mushroom#37]
Hello, incredible work for us who know little about design and programming.

I have the following problem and it is when I make a temperature change in the lights that the error appears that I show you in the screenshot that I leave you.

![image](https://user-images.githubusercontent.com/70614796/152651111-c64c34fa-f00d-4243-9e67-c960cef0142e.png)

**Comment by pierrecle** [comment]
The temperature might not ne set using kelvins. @piitaya can you check?

**Comment by agustusbotti** [comment]
Hello, I apologize, the error is from the yeelight integration, not from the Mushroom interface.

**Comment by agustusbotti** [comment]
Hello, I apologize, the error is from the yeelight integration, not from the Mushroom interface.
