### ISSUE TITLE
[Feature]: Optionally remove shape around icon and set icon size

### ISSUE THREAD

**Issue by teogira** [piitaya/lovelace-mushroom#385]
### Is your feature request related to a problem?

Icons are quite small for my 50 y.o. eyes

### Describe the solution you'd like

If you don't want to render this parameters on UI, eventually you can include variables like: _mush-shape-enabled_ and _mush-icon-size_ into mushroom themes configuration.

**Comment by greghesp** [comment]
Do you mean something like:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/768908/164894426-33038008-d166-4d91-b32c-a9dcfd948032.png">

**Comment by teogira** [comment]
Exactly.
I managed to obtain it by modifying mushroom.js file, but I wouldn't loss the changes after upgrading...

**Comment by acesyde** [comment]
Do you want to do this for just one card are all cards ?

**Comment by greghesp** [comment]
> Do you want to do this for just one card are all cards ?

Probably best to enable for all cards but through theme options I'd have thought?

**Comment by teogira** [comment]
Better by theme options for all cards. Best if add per-card UI option.

**Comment by piitaya** [comment]
You can override theme variable with card-mod by defining them locally I think 🙂

**Comment by teogira** [comment]
@piitaya yes but card-mod is css-dependant and I wish a stable theme configuration.

**Comment by piitaya** [comment]
I will look to add additional theme variables 🙂

**Comment by teogira** [comment]
great!

**Comment by fenty17** [comment]
Just adding my +1 to this. Not having any luck getting icon size changed with card-mod. I'd be happy if I could do that, but even better to have options/theme variables baked in.

**Comment by piitaya** [comment]
New variables have been added to allow you customize the sizes of slider, icon and control with theme variables 🙂https://github.com/piitaya/lovelace-mushroom/releases/tag/v1.8.1

**Comment by totalitarian** [comment]
Still not able to hide the shape?

**Comment by teogira** [comment]
I confirm: no way to remove shape

Matteo Girardi
iOS Senior Developer
www.matteogirardi.com
