### ISSUE TITLE
[Feature]: Graph in Cards

### ISSUE THREAD

**Issue by apivaral** [piitaya/lovelace-mushroom#386]
### Is your feature request related to a problem?

Please add option to show a graph in cards like in Minimalist UI.

### Describe the solution you'd like

Reference: https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_graph/

**Comment by acesyde** [comment]
Pr already opened #308

**Comment by piitaya** [comment]
Duplicate https://github.com/piitaya/lovelace-mushroom/issues/74
