### ISSUE TITLE
[Feature]: Light Card Group Light option to adjust Individual Lights

### ISSUE THREAD

**Issue by GitHubGoody** [piitaya/lovelace-mushroom#390]
### Is your feature request related to a problem?

I cannot address individual lights within a light group entity.

### Describe the solution you'd like

I'd like to be able to double-tap or long press a group light and be presented with a mushroom card for the group's individual lights. Ideally, this would be a temporary drawer that would slide out under the group card to quickly adjust the brightness, color, and temp of an individual light. Another double-tap or long press on the group card would close the drawer.

### Describe alternatives you've considered

Creating cards for each individual light. I don't think this is the best solution because:

1. Most of the time I don't want to see the individual lights.
2. It doesn't take full advantage of HA's new group capabilities.
3. The individual cards could get out of place in relation to the group light card.

### Additional context

Thank you for creating Mushroom cards. They're a great step to creating a streamlined UI!

**Comment by piitaya** [comment]
Hi 🙂
You can create a view for controlling your lights and navigate to with the navigate action. Building drawer or popup is not in the road map.

**Comment by GitHubGoody** [comment]
@piitaya Bummer. Navigating to an entirely other view for this isn't minimalist IMO. But, I was able to sort of achieve what I'm after with a swipe card (https://github.com/bramkragten/swipe-card).

**Comment by piitaya** [comment]
I known it's not perfect. I'm building Mushroom on my free time. As you can see there is more than 80 issues so I have to prioritize and make choice 😉
