### ISSUE TITLE
[Feature]: Media Player Card - Ability to seek

### ISSUE THREAD

**Issue by indykoning** [piitaya/lovelace-mushroom#392]
### Is your feature request related to a problem?

At the moment it's not possible to "seek"/scroll/skip & rewind through the content if the content support it.
It would be nice to have the ability to navigate the content currently playing

### Describe the solution you'd like

While the ability to seek like the volume slider would be nice it might not align with the current design since it'll probably need to be on a new line.

It may be a better idea to have one of the mdi:rewind & mdi:fast-forward buttons next to the skip-forward & skip-backwards buttons

**Comment by piitaya** [comment]
I did not out this feature because it can be done with the more info. Mushroom should stay minimalist. The goal is not the provide all the HA features in card because some feature required more space that just a mushroom card.

**Comment by indykoning** [comment]
If I understand you correctly this is actually one of the few things that are not available in the more info dialog.

This seek bar is available on the Lovelace cards
![Screenshot_20220427-002352](https://user-images.githubusercontent.com/15870933/165403243-c0e865e2-e61e-4d66-ad6a-26eaf9fe8a30.jpg)

but not in the more info dialog
![Screenshot_20220427-002417](https://user-images.githubusercontent.com/15870933/165403615-2978e92d-395e-4f18-a59a-666a916539e2.jpg)

Which is why I though it would be nice to have the option to have a button to skip & rewind 15 seconds in place of the next/previous track buttons since these are mostly unused on video media player.

I do agree with the minimalism sentiment though, so I respect the decision made.
Maybe I'll turn adding it myself into a weekend project 🙂

**Comment by piitaya** [comment]
Yep, may be a rewind or forward button can be good 🙂
For the seek bar, I can be difficult to make the difference between volume slider and seek slider 🙁
