### ISSUE TITLE
[Feature]: Picture Entity Card

### ISSUE THREAD

**Issue by greghesp** [piitaya/lovelace-mushroom#396]
### Is your feature request related to a problem?

The default picture entity card is boring, and lacks featured such as rotation.

### Describe the solution you'd like

A Mushroom version of the picture entity card 

### Describe alternatives you've considered

None

**Comment by piitaya** [comment]
I don't think Mushroom is the right place for this. We can not replace all HA card by Mushroom card.

**Comment by greghesp** [comment]
If the goal is the create a fresh looking dashboard with easy to use features, is this not the exact place for it?
Having to take stuff from other components is a lot of people's main problem.

I'd have envisioned it to look and function similar to this:

![Screenshot_20220425-083615](https://user-images.githubusercontent.com/768908/165042292-daa3ab0f-c9dd-45f7-ab7a-a9020e3bfbde.png)
