### ISSUE TITLE
RGB color ramp ?

### ISSUE THREAD

**Issue by nightfever77** [piitaya/lovelace-mushroom#40]
Thanks for sharing your great work.
Would be great if you could add an RGB color ramp in addition to temperature and brightness in your future update.

**Comment by thundergreen** [comment]
Also maybe fetch the effects if available? I am planning to make your light card my standard card :)

**Comment by pierrecle** [comment]
> Also maybe fetch the effects if available? I am planning to make your light card my standard card :)

That’s a different thing, and it’s not planned for some reasons:
- we want to keep ui as light as possible
- as far as I know, effects are mainly used by automations, not manualy 
- we already have a good-but-not-great UX with the color selector, we have to enhance it before adding new elements in this card


Today you can create a grid with the light card and below another grid with buttons that call the right service.

**Comment by thundergreen** [comment]
I agree maybe it would be overwhelming having to many options in the card . Thanks for the hint and keep up this great work .maybe for colour picker it could be something like settings button or expandable like with fold card ?

**Comment by pierrecle** [comment]
Done in #48
