### ISSUE TITLE
[Feature]: Icon Background Colour Help

### ISSUE THREAD

**Issue by Shaun-Harrison** [piitaya/lovelace-mushroom#402]
### Is your feature request related to a problem?

Yes, when using the alarm panel, I'd like to hide the icon by using 
`icon: ''`

However this leaves a blueish circle on the outline of the icon from the theme

![image](https://user-images.githubusercontent.com/46562010/165288993-5f31ea56-0b1b-4f72-9d43-ea1927c3be67.png)

### Describe the solution you'd like

Know if there's something that can be done on the mushroom side of things, or know what I need to do to change this on my theme side of things, couldn't find anything on the usual 'inspect'

### Describe alternatives you've considered

This may not be anything to do with mushroom card, but couldnt find anything related in my theme

**Comment by piitaya** [comment]
It can be done with the 2.0.0 version using `icon_type: none` 🙂
