### ISSUE TITLE
[Bug]: Unable to install

### ISSUE THREAD

**Issue by Vincevega83** [piitaya/lovelace-mushroom#408]
### Current Behavior

Manual installation and installation via hacs doesnt work. 
Cant see any custom cards in the editor.
I cann add mushroom.js as a source, but still nothing happens.
Any idea?

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by greghesp** [comment]
Restart and check your logs. I suspect there will be an error

**Comment by ka0n** [comment]
Had the same issue after installing through HACS. After restarting core and refreshing in Chrome (Ctrl+F5) I can see the Mushroom cards in the editor

**Comment by Vincevega83** [comment]
Thanks a complete restart with disconnection from Power helped!

ka0n ***@***.***> schrieb am Fr., 29. Apr. 2022, 02:56:
