### ISSUE TITLE
Make sliders less sensitive 

### ISSUE THREAD

**Issue by Ulrar** [piitaya/lovelace-mushroom#41]
Hi,

I redid my dashboard using the light cards and they look really good, I love the brightness and temperature sliders.
However on mobile when I'm scrolling I (very often) turn random lights on by touching the slider, it seems like if my finger happens to start the scroll on a slider it'll register as a touch as well, turning the light on.

I don't know if it can be made less sensitive but if so, it would be great.
Alternatively maybe an option to hide the slider and only show them when a button is pressed, or even just a lock might do it.

I turned on the main light in the nursery three times last night while the baby was sleeping when trying to scroll past it :(

Thanks

**Comment by rfnovo** [comment]
From what I've seen this is due to the "My Cards Bundle" integration they are using to build that slider. But I agree it is super annoying.

**Comment by piitaya** [comment]
`My Cards Bundle` slider is based on html `input range` and the iOS behaviour is strange. That's why we develop our own slider. 
I think we must look to gesture control lib like [hammerjs](https://hammerjs.github.io/) to improve this behaviour and reduce sensitivity with a threshold.

**Comment by rfnovo** [comment]
Got it! Maybe check the [slider-entity-row](https://github.com/thomasloven/lovelace-slider-entity-row) integration - not sure if using the same method but it at least it does not suffer the same issue with scrolling.

**Comment by piitaya** [comment]
The slider-entity-row has the same problem. It's the [polymer slider](https://www.webcomponents.org/element/@polymer/paper-slider). But you don't have the issue because of the size of the slider 🙂

**Comment by rfnovo** [comment]
At least for Android it does not. Take a look at this test dashboard. Slider-entity does not change when I click on it during scrolling, but the mushroom slider does
![Screenshot_20220208-105141_Parallel Space 64Bit Support](https://user-images.githubusercontent.com/11941836/153035995-9099ea45-15d1-4453-b86a-3e3470a5a012.jpg)
.

**Comment by Ulrar** [comment]
I don't use the slider entity row as much but I've never noticed that problem on Android either. Can't talk to iOS

**Comment by pierrecle** [comment]
On iOS I have the same problem.

It will be hard to find the right threshold. Apple set a 300ms delay but it brings reactivity issues. So Fastclick was created and brings such issues.

**Comment by piitaya** [comment]
I will try with this : https://hammerjs.github.io/recognizer-pan/

**Comment by Ulrar** [comment]
Hey @piitaya, just did a quick test and it does seem much better, even trying to I haven't been able to get an accidental turn on.
Let me keep using it for a couple of days to confirm, but that looks pretty good to me, thank you very much !

**Comment by piitaya** [comment]
Ok, I will close the issue, I pushed the stable `1.0.3` version with the fix.
