### ISSUE TITLE
[Bug]: Issue with casting on Google Nest Hub

### ISSUE THREAD

**Issue by buzzard10** [piitaya/lovelace-mushroom#416]
### Current Behavior

There is an issue with displaying Mushroom card with location of person, because instead of showing card with picture, name and current position, there is this:
![IMG_20220429_132503](https://user-images.githubusercontent.com/17282191/165935799-ca96e87c-6e65-4d02-a5e2-3da692671e0b.jpg)

### Expected Behavior

Mushroom card with location and other information

### Steps To Reproduce

1. Create card with location
2. Cast to Google Nest

### Anything else?
Other Mushroom cards seems fine.

**Comment by piitaya** [comment]
I do not have a Google Nest to test that 🙁 Do you have the same issue with other card using `entity_picture` ?

**Comment by buzzard10** [comment]
@piitaya yeah, i added default entity card to dashboard with the same person and it worked.. Maybe i could load image through template card? I mean load image as icon? Idk

**Comment by buzzard10** [comment]
@piitaya also as you can see, there is no text. On other cards text is visible..

**Comment by buzzard10** [comment]
@piitaya i can't also display entity_picture in Entity card: https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/entity.md

**Comment by buzzard10** [comment]
@piitaya do you know when it'll be available for download?

**Comment by buzzard10** [comment]
@piitaya it's still doesn't work. I upgraded to the newest version and i still can't display pictures and/or text next to them like on a screenshot above.

**Comment by buzzard10** [comment]
@piitaya i tried today to share the same dashboard on my tv, and there is also a problem! So if you have Chromecast, you can reproduce issue in your environment :)
![image](https://user-images.githubusercontent.com/17282191/167372345-2ba09401-8c7f-4227-9fa9-7cb94d5894b7.png)

**Comment by piitaya** [comment]
Should be fixed in [1.8.5 release](https://github.com/piitaya/lovelace-mushroom/releases/tag/v1.8.5)

**Comment by buzzard10** [comment]
Yeah, it's working! Thank you very much :))))
