### ISSUE TITLE
[Entity card]: Two lines name

### ISSUE THREAD

**Issue by maicol07** [piitaya/lovelace-mushroom#424]
### Is your feature request related to a problem?

When adding cards of entities with long names it gets cut

### Describe the solution you'd like

An option to enable displaying more than one line of text (ideally two lines)

### Describe alternatives you've considered

Less long name for entity

**Comment by piitaya** [comment]
Hello.
It's by design. For the UI consistency, the name is only one line to keep a minimalist design.
