### ISSUE TITLE
Flickering template chips 

### ISSUE THREAD

**Issue by ascorria** [piitaya/lovelace-mushroom#426]
### Current Behavior

All template chips are flickering.
This behavior wasn’t present on 1.6.x.

### Expected Behavior

No flickering 

### Steps To Reproduce

https://user-images.githubusercontent.com/73254700/166164932-b1eb023a-68ca-4b77-a8f4-1467cea02061.MOV

### Environment

```markdown
- Version:1.7.2
- Hassio:2022.4.7
```

**Comment by piitaya** [comment]
I think it's because you have two lines of chips. 
I reverted the 1.7.2 version. I will push a fix a soon as possible 🙂 you can revert to the last version for now.

**Comment by ascorria** [comment]
It definitely not because of the 2 lines.
I still have the issue with one single chip, on other dashboards.
Only on template chips.

https://user-images.githubusercontent.com/73254700/166165427-08128b64-ef7e-4d99-9ab2-76d525dbab5b.MOV

**Comment by alexreddy78** [comment]
Dear Developer,

Confirm flickering as well for all templates...Kindly check and advise

Regards

**Comment by piitaya** [comment]
@ascorria @alexreddy78 I pushed a fix (`1.7.3` beta version). Can you update and say if the issue is fixed ? 🙂

**Comment by alexreddy78** [comment]
> @ascorria @alexreddy78 I pushed a fix (`1.7.3` beta version). Can you update and say if the issue is fixed ? 🙂

Thanks! Work well!

BRGDS

**Comment by ascorria** [comment]
> @ascorria @alexreddy78 I pushed a fix (`1.7.3` beta version). Can you update and say if the issue is fixed ? 🙂

Fix! 👍🏻😀

**Comment by piitaya** [comment]
Ok. I will release it for all 🙂 
Thanks !
