### ISSUE TITLE
[Bug]: after upgrade to 1.7.3 all entities lovalce are not showing any more

### ISSUE THREAD

**Issue by shaylami** [piitaya/lovelace-mushroom#435]
### Current Behavior

update the pack from 1.6 to 1.7 with the latest HA 
after reload/restart my dashborad cards was completely messad up with error of custom entity not found 
when i was trying to add new entity i don't able to see any mushroom card to pick from the list.

### Environment

```markdown
- OS:HASSOS
- Node:
- Version: 2022.4.7
- Hassio: 7.6
- supervisor: 2022.04.0
```

**Comment by piitaya** [comment]
Looks like the same bug ? https://github.com/piitaya/lovelace-mushroom/issues/106

**Comment by shaylami** [comment]
Hi,

 

Yes it’s the same bug but even after reboot clear nothing worked for me.
