### ISSUE TITLE
[Feature]: Size Options for Chips

### ISSUE THREAD

**Issue by 12xx12** [piitaya/lovelace-mushroom#443]
### Is your feature request related to a problem?

The Chips are tiny when viewed with my mobile phone. I use them as triggers for scenes, and I'd like to tab those tiny buttons.

### Describe the solution you'd like

Some kind of size selector for the Chip Card. Maybe small [right now], medium [the size of the buttons on the other cars] and large.

**Comment by piitaya** [comment]
Hello 🙂

Chips can be resized using themes https://github.com/piitaya/lovelace-mushroom-themes. You can customize the size, the space, etc...
