### ISSUE TITLE
[Bug]: When choosing a scene as an entity, the toggle action will fail since there is no on/off available

### ISSUE THREAD

**Issue by 12xx12** [piitaya/lovelace-mushroom#444]
### Current Behavior

Failed calling the service scene/turn_off. Service not found. [Might be different. Using HA in another language]

### Expected Behavior

The Scene should turn on [off is not available inside of HA]

### Steps To Reproduce

- create Entity Chip 
- use a scene as entity
- select toggle as action

### Environment

```markdown
- OS: 			Home Assistant OS, aarch64 5.10.103-v8
- Version:		2022.5.1
- Python-Version:	3.9.9
- mushroom-version:	1.7.3
```

**Comment by piitaya** [comment]
Hello !
Scenes can't be turned off but design. You need to call the `turn_on` service in the actions instead of the toggle action 🙂
