### ISSUE TITLE
Entity card show attribute

### ISSUE THREAD

**Issue by Protoncek** [piitaya/lovelace-mushroom#45]
Hi!
I just discovered your card and it's pretty impressive! However, i'd like to ask if it's possible to add attribute selection in entity card, so we could choose either to show state (default) or rather certain attribute of the entity? It would be a nice addition...

**Comment by pierrecle** [comment]
Like the idea. @piitaya what do you think about this?

**Comment by piitaya** [comment]
The problem with `attributes` is that you don't have the unit and the translation to format the attributes. 😟
For example for a weather entity :
```
temperature: 3.9
humidity: 80
pressure: 1026.6
wind_bearing: 295
wind_speed: 18
```

**Comment by Protoncek** [comment]
Well, if this is the only problem it could be solved with template in which unit would be added...
I have a specific example: i have set up "next holiday" sensor: [https://github.com/partofthething/next-holiday-sensor](url)
state of this sensor is the name of next holiday. But this sensor has also an attribute "holidays" where all holidays this year are stated. So, i'd like to show these, that's why i asked for attribute. Unless it can be solved in some other way...

**Comment by piitaya** [comment]
You can use templating to create your own cards using the [template card](https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/template.md)

Somethings like this (I don't known how this sensor is defined 😅):
```yaml
type: custom:mushroom-template-card
primary: Next holiday
secondary: {{ state_attr('sensor.next_holidays', 'holidays') }} 
icon: mdi:home
```

**Comment by Protoncek** [comment]
Aha... ok, thanks. I'll play a bit with templates and see what i'll come up with.

**Comment by cyrilphoenix71** [comment]
@piitaya may be your exemple could be have a nice place in the mushroom documentation ?
