### ISSUE TITLE
[Feature]: Add Use Entity Picture to Template card

### ISSUE THREAD

**Issue by smarthomejunkie** [piitaya/lovelace-mushroom#457]
### Is your feature request related to a problem?

Not a real problem, but would be nice!

### Describe the solution you'd like

I would like to have an option for the template card to either:
1. Have a toggle for "Use entity picture?" just like in the entity card 

OR

2. Have a template field to show an entity picture

**Comment by EolianPipes** [comment]
I would love to see this feature! Especially the second option where it's a template field.

My particular use case would be to template an entity picture for a person with the current status and/or zone. I like using various Bitmoji images to map to whatever we're doing.

**Comment by werra11** [comment]
I would also love to see this! For the exact same reason as above.

**Comment by GitHubGoody** [comment]
Fourth!

**Comment by rodh** [comment]
+1

**Comment by janpgu** [comment]
+1 :)
