### ISSUE TITLE
[Bug]: collapsible_controls parameter not working in HA android app

### ISSUE THREAD

**Issue by pingus-x** [piitaya/lovelace-mushroom#461]
### Current Behavior

When parameter collapsible_controls is set to true in light card, collapsing when off is working only in Firefox and Chromium, but not working in HomeAssistant android app. Also not working in Vivaldi browser. Using mushroom version 1.8.0, on previous versions 1.7.x I had same behaviors.
If it helps, bellow is code for my light card

![mushroom1](https://user-images.githubusercontent.com/105239805/167478562-355f2444-8f5d-4d94-a047-081f829d221f.png)

Thank you!

### Environment

```markdown
Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.0
Home Assistant OS 7.6
Mushroom version: 1.8.0
```

**Comment by piitaya** [comment]
Probably a cache issue. Try to remove mushroom.js from your ressources and re-add it 🙂

**Comment by pingus-x** [comment]
I didn't think of cache, sorry.
Re-adding resources didn't help, but clearing HA android app cache did :)
Thank you!

Also I would like to thank you for your great work and effort
