### ISSUE TITLE
[Bug]: sensor and binary_sensor opposite

### ISSUE THREAD

**Issue by MechEng70** [piitaya/lovelace-mushroom#467]
### Current Behavior

When the sensor is closed the icon is highlighted

binary_sensor is open it is highlight

### Expected Behavior

They both act the same way.  Preferable highlight/colored when in the open position.

Can there be a switch to invert the state for the icon?

### Steps To Reproduce

![2022-05-10_10-40-44](https://user-images.githubusercontent.com/11697710/167691174-415c28e0-dc1f-4bf9-b470-b8ce6696fd2d.png)

### Environment

```markdown
- OS: Ubuntu 20.04
- Home Assistant Core 2022.5.3
- Home Assistant Supervisor 2022.05.1
- Docker Version 20.10.15
```

**Comment by piitaya** [comment]
I think it's more an issue with the ish hub than a mushroom issue.

**Comment by MechEng70** [comment]
Interesting.  I will look at creating a binary_sensor from the sensor.

**Comment by MechEng70** [comment]
I will close this as I was able to create binary sensors from the sensors to allow them to act as needed.  Thank you!
