### ISSUE TITLE
[Request] Hide Icon

### ISSUE THREAD

**Issue by ahmadtawakol** [piitaya/lovelace-mushroom#47]
Can we have an option to hide the icons for all cards? Thanks, I'm loving these cards!

**Comment by pierrecle** [comment]
Sorry but I can’t see the usecase..
It’s not planned, maybe in themes introduced by @piitaya you will be able to create one that hide the icons.

**Comment by ahmadtawakol** [comment]
There are some entities that I wanted to display their state as text only, like the Thermal Comfort integration. I don't need an icon to be displayed, it just adds more clutter.

**Comment by pierrecle** [comment]
Okay got it, I'll take it later ;)

**Comment by pierrecle** [comment]
Fixed by #64
