### ISSUE TITLE
[Bug]: media player card - volume_buttons not showing for Sonos devices

### ISSUE THREAD

**Issue by bugzke** [piitaya/lovelace-mushroom#471]
### Current Behavior

When using the mushroom-media-player-card for a Sonos device the setting "volume_buttons" doesn't seem to do anything. Volume can only be shown as a slider (using volume_set), or is invisible when only using volume_buttons.

![image](https://user-images.githubusercontent.com/84719694/167842763-6a999111-21cc-42d3-beef-50c2f594055c.png)

When using the custom:mini-media-player it is possible to use volume buttons instead of a slider for the same devices, using volume_stateless: true. So it seems to be related to the mushroom-media-player-card and not to the Sonos integration not allowing this.

Tested with Sonos One and Sonos Play:1

### Expected Behavior

When using the card on another device (e.g. Samsung TV) the volume buttons do work as expected.

![image](https://user-images.githubusercontent.com/84719694/167842604-9cdf4591-9e5d-4231-b9be-e269ba051b4c.png)

### Steps To Reproduce

Create a mushroom-media-player-card for a Sonos device.
Tick "volume buttons" in the UI config (or use volume_controls:  - volume_buttons in YAML).

### Environment

```markdown
- OS: Home Assistant OS 7.6
- Version: 1.8.0
- Hassio: 2022.5.3
```

**Comment by piitaya** [comment]
Hi 🙂 Sonos integration doesn't support `VOLUME_STEP` feature. That's why the controls are not displayed : https://github.com/home-assistant/core/blob/dev/homeassistant/components/sonos/media_player.py#L225-L241
