### ISSUE TITLE
[Bug]: Buttons wider on v8.4.1 - unnecessary scrolling, mobile phone only

### ISSUE THREAD

**Issue by bremor** [piitaya/lovelace-mushroom#476]
### Current Behavior

The vacuum card and media player card buttons have become very wide in 8.4.1, rather than being nice and compact like they were in 8.4.0.

### Expected Behavior

I preferred the old size buttons and behaviour of 8.4.0

### Steps To Reproduce

1. Open dashboard on Safari on iPhone.
2. Observe that the buttons have changed size and introduced scrolling.

### Environment

```markdown
- OS: iOS 15.4.1
- Browser: Safari
- Version:
- Hassio: 2022.5.2
```

### Anything else?

![thumbnail_Image](https://user-images.githubusercontent.com/34525505/168006560-553a9d47-0e68-4ba5-82d7-e845ce227afe.jpg)
![thumbnail_Image](https://user-images.githubusercontent.com/34525505/168006575-35771b07-7786-47a0-a269-49fe9538389a.jpg)

**Comment by piitaya** [comment]
Hi 🙂 I didn't see it when I tested on Safari desktop. I unpublished the 1.8.1 and will push 1.8.2 to fix this 🙂

**Comment by bremor** [comment]
Thanks for that, sorry I totally messed up the versioning in the bug report

**Comment by pedolsky** [comment]
With `mush-control-button-ratio: 2 ` you can see the whole control button again (at least on light and media card).

**Comment by tm24fan8** [comment]
I have this issue with the light cards as well. The buttons are wider than the card, causing a scroll bar to appear even though there is plenty of room.

![image](https://user-images.githubusercontent.com/14335374/168147965-7dd98d95-f2ee-4c39-9495-20031c8b4790.jpeg)

**Comment by piitaya** [comment]
Update is coming 😅 https://github.com/piitaya/lovelace-mushroom/commit/691ca86c909e95c0d6a623354bc4cb14b7257f2f

**Comment by piitaya** [comment]
Fixed with https://github.com/piitaya/lovelace-mushroom/releases/tag/v1.8.3
