### ISSUE TITLE
[Bug]: Icon color template not being working

### ISSUE THREAD

**Issue by mbarclay95** [piitaya/lovelace-mushroom#479]
### Current Behavior

I am trying to set the icon color for an entity card based on a template. When I put the template in and view the style on that icon the template is being used as the variable. Not sure if I'm doing something wrong here or not. Here is what I have in my yaml:

```
- type: custom:mushroom-entity-card
  icon_color: |
    {% if is_state("input_select.basement_fireplace_mode", 'off') %}
    orange
    {% else %}
    green
    {% endif %}
```
And here is what shows up for that icon's style:
![ha-icon-style](https://user-images.githubusercontent.com/11918454/168187695-7d456172-7b2d-4c88-8f43-84ebf9cd599f.png)

### Environment

```markdown
- Version: 1.8.3
- Hassio: 2022.4.4
```

**Comment by piitaya** [comment]
Template are not supported on entity card. You must use template card for this.

**Comment by mbarclay95** [comment]
That worked perfectly, thank you!
