### ISSUE TITLE
[Bug]: Cover visual bug on HA IOS app (horizontal layout)

### ISSUE THREAD

**Issue by timvdsm** [piitaya/lovelace-mushroom#480]
### Current Behavior

Since a couple of days, the mushroom cover in horizontal  layout has a bug in the visuals (buttons up/down/pauze). 
On the website it seems to be ok. 

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

### Anything else?

![IMG_5878](https://user-images.githubusercontent.com/14946020/168255860-822ea5fa-45b5-46ac-9785-a78d67a51631.jpeg)

**Comment by timvdsm** [comment]
Resetting the ios companion app frontend cache, fixed it. Strange, as yesterday I tried to do that multiple times without success. But good that it’s fixed now ;-)

**Comment by piitaya** [comment]
There was an issue with 1.8.1 version but it's fixed with 1.8.3 🙂

**Comment by timvdsm** [comment]
Oh ok thanks. I did the upgrade in meanwhile and did za reset of the cache of the IOS companion app. 

Thanks for your support!
