### ISSUE TITLE
[Bug]: Layout/Padding regression on climate card?

### ISSUE THREAD

**Issue by wishie** [piitaya/lovelace-mushroom#485]
### Current Behavior

All padding seems to have been removed from the buttons on the climate card. It looks horrible now.

### Expected Behavior

In previous versions the layout was far more consistent and pleasing to the eye.

### Steps To Reproduce

Look at a mushroom climate card in latest release.

### Environment

```markdown
- OS: HA Container on unRAID
- Browser: HA Companion App, Safari, Chrome
- Version: 1.8.3
- Hassio: 2022.5.4
```

### Anything else?

![Screen Shot 2022-05-15 at 8 31 26 pm](https://user-images.githubusercontent.com/635844/168468513-d960f64a-80ac-4e1a-8588-afab5a71afa2.png)
![Screen Shot 2022-05-15 at 8 31 21 pm](https://user-images.githubusercontent.com/635844/168468518-adfce504-9cec-4bc6-a555-57e6219c2d4c.png)

**Comment by piitaya** [comment]
The thermostat card is not released yet. https://github.com/piitaya/lovelace-mushroom/pull/258

**Comment by wishie** [comment]
It might indeed be a custom one from someone else, sorry.
