### ISSUE TITLE
[Feature]: Entities Card as well as Entity Card

### ISSUE THREAD

**Issue by aptonline** [piitaya/lovelace-mushroom#486]
### Is your feature request related to a problem?

N/A

### Describe the solution you'd like

I would like to display multiple entities as well as a single entity, similar to how the default HA entities works.
For examples using the mushroom entity as it stands I get the following:
![Screenshot 2022-05-15 at 14 03 10](https://user-images.githubusercontent.com/190136/168474271-af078a3a-76f0-40fb-9ae3-04a9592a6f47.png)

Each entity is listed separately (appears to be in separate cards) where as the default entities card in HA lists them all together (more coherent one card) in the example below:
![Screenshot 2022-05-15 at 14 05 55](https://user-images.githubusercontent.com/190136/168474374-e17f3e85-5439-4002-8543-f4152d60dd40.png)

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by acesyde** [comment]
Hi @aptonline 

You can do this behavior with [Vertical Stack in card](https://github.com/ofekashery/vertical-stack-in-card) or [Stack in card](https://github.com/custom-cards/stack-in-card)

**Comment by aptonline** [comment]
True but why add the complexity of using another custom card when you can just list the entities needed in the mushroom card?

**Comment by piitaya** [comment]
Because people will want all the options to customize entity by entity 😅

**Comment by aptonline** [comment]
Still think there’s scope for an entities card for those that don’t want/need the customisation options 🤷‍♂️.

**Comment by piitaya** [comment]
No customization means no custom icon, no custom action, no custom color, etc... Just an entity field. I'm not sure people want this.

**Comment by aptonline** [comment]
Well I’m people so… 

I’ll close the issue and hope to see something In the future.

**Comment by smartypantsuk** [comment]
I would like this also
