### ISSUE TITLE
[Bug]:  Alignment in horizontal stack with conditionnal card

### ISSUE THREAD

**Issue by Strangehadron** [piitaya/lovelace-mushroom#489]
### Current Behavior

Hi,
I've a problem with the alignment (padding or margin i'm not a css guy) of my horizontal stack with mushroom entity card (i've not test other mushroom card with this config) when i set a conditionnal card in the first or last position (4 cards in this example). When the conditionnal card isn't displayed, it create a misalignment with other card.
If i change the position of the conditionnal card for 2 o 3 alignment is perfect as expected

Left misalignment (next to pause where the conditionnal card is and not displayed)

<img width="513" alt="Capture d’écran 2022-05-15 à 20 10 54" src="https://user-images.githubusercontent.com/38626456/168487753-dec9596b-9c14-4d51-8a59-99b06d9b5a37.png">

--

Right misalignment (next to stop where the conditionnal card is and not displayed)

<img width="550" alt="Capture d’écran 2022-05-15 à 20 11 15" src="https://user-images.githubusercontent.com/38626456/168487758-e64b4816-13db-4c09-80fa-86fb9e346995.png">
.

### Expected Behavior

If i change the position of the conditionnal card for 2 o 3 alignment is perfect as expected (same when the conditional card is true and displayed)

<img width="576" alt="Capture d’écran 2022-05-15 à 20 16 52" src="https://user-images.githubusercontent.com/38626456/168487803-dba6c05f-6312-4279-a1cb-239dc40a4ce0.png">
-------
<img width="585" alt="Capture d’écran 2022-05-15 à 20 10 41" src="https://user-images.githubusercontent.com/38626456/168487983-7458b680-8024-45ce-9491-762f637d3b1a.png">

### Steps To Reproduce

- Make an horizontal stack (In this exemple i've 4 mushroom entity cards)
- Make one of the card a conditional at the first or last position and not displayed
- Observe the misalignment

### Environment

```markdown
- OS: MacOS 
- Version: Monterey 12.3.1
- Hassio: 2022.5.4 / OS 8.0
- Browser : Firefox 100, tested with ios app on iphone, and mac app too
```

### Anything else?

Thanks !

**Comment by piitaya** [comment]
Should be fixed in latest version as I can not reproduce it. Don't hesitate to re-open it if you still have the issue.
