### ISSUE TITLE
[Feature]: Add support for fire-dom-event action on tap/double-tap/etc

### ISSUE THREAD

**Issue by bfayers** [piitaya/lovelace-mushroom#490]
### Is your feature request related to a problem?

It's currently impossible to use browser mod popups in tap/double/hold actions without affecting every device currently viewing home assistant.

### Describe the solution you'd like

Add the ability to use fire-dom-event so that popups can only display on the current device.

**Comment by piitaya** [comment]
It think it's already possible with the yaml mode but there is no editor for this because it's custom. I didn't use browser mod popups so I couldn't test it 😞

```yaml
action: "fire-dom-event"
```

**Comment by bfayers** [comment]
Confirmed that works; I should have just tried it earlier -- I assumed it wouldn't as it wasn't mentioned anywhere.
