### ISSUE TITLE
[Bug]: <Where is the mushroom.js file (for manual instalation)>

### ISSUE THREAD

**Issue by spirk91** [piitaya/lovelace-mushroom#491]
### Current Behavior

Hello ! 

I would like to do a manual instalation but i don't find the mushroom.js. 
Where is this file ? Or how to do a manual instalation without this file ? 

Thank you !

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by piitaya** [comment]
It's in the release assets : https://github.com/piitaya/lovelace-mushroom/releases
