### ISSUE TITLE
[Bug]: <title>mushroom cover card Crushed by the entity next to it

### ISSUE THREAD

**Issue by yanirel** [piitaya/lovelace-mushroom#492]
### Current Behavior

It does not work so well as usual, because the click space is reduced and does not always work 

### Expected Behavior

Fix mushroom card size Add more margins so that they are crushed and not a button on the card 

### Environment

```markdown
- OS: home assistant
- Node: no 
- Version: 22.5.3
- Hassio: 8
```

**Comment by piitaya** [comment]
I don't see the bug. We can't do anything with this level of detail 😅

**Comment by piitaya** [comment]
You can use larger card or change the padding or control size using themes. It's not planned to change the default size of buttons.
