### ISSUE TITLE
[Bug]: HACS - Cant install 

### ISSUE THREAD

**Issue by ari-za** [piitaya/lovelace-mushroom#497]
### Current Behavior

<img width="640" alt="Screenshot 2022-05-17 at 12 22 59" src="https://user-images.githubusercontent.com/8730066/168790710-de6371f6-5870-4961-ad58-8f3260c735b5.png">

### Environment

```markdown
- OS: HassOS
- Version: 2022.4.0
```

**Comment by acesyde** [comment]
Can you try to update your homeassistant version to 2022.5.4 (latest) and try to install it again?

**Comment by ari-za** [comment]
> Can you try to update your homeassistant version to 2022.5.4 (latest) and try to install it again?

I can but I don't really want to upgrade at this time since things are stable. Will manually install if you're not able to push a fix

**Comment by acesyde** [comment]
2022.5.4 is stable you can use it ,👍

**Comment by ari-za** [comment]
Thanks guys!

Restarted HA and can't seem to install it still in HACS.  Any ideas on how to pull the new version/change? 

I deleted browser cache but no change.

Thanks

**Comment by ari-za** [comment]
That context menu only shows for a pre-installed repo. 

As you can see, no context menu. 

I read up on HACS documentation, supposed to refresh every 25 hours or a system reboot. However the restart didn't work for me. Will try a power cycle later

<img width="508" alt="Screenshot 2022-05-17 at 16 11 22" src="https://user-images.githubusercontent.com/8730066/168831569-443eabac-1540-400a-b713-b47b16e58052.png">

**Comment by ari-za** [comment]
Fixed as release v1.8.7 was pushed.

Thanks
