### ISSUE TITLE
[Bug]: Cover card position control slider not working when cover is fully closed

### ISSUE THREAD

**Issue by nofoxgit** [piitaya/lovelace-mushroom#513]
### Current Behavior

When covers are closed, position control slider is grey and there is no way to set position to desired amount of %. 

### Expected Behavior

It will be nice if we can set position from slider either cover are fully closed or opened

### Steps To Reproduce

1. Use Mushroom Cover card
2. Close cover
3. Try to set position from slider

### Environment

```markdown
- OS: Debian
- Node:
- Version:
- Hassio: 2022.2.4
```

**Comment by piitaya** [comment]
What's your Mushroom version? I don't think you have the latest because your 2022.4 HA version is required for the latest Mushroom version.

**Comment by nofoxgit** [comment]
Ok, sorry! Thought I've updated everything to latest version but I'm stil on mushroom 1.4.0..  I was searching everywhere for this issue, found nothing so I decide to open Issue here. So, forget about it and close.
