### ISSUE TITLE
[Feature]: Improve fan slider

### ISSUE THREAD

**Issue by redphx** [piitaya/lovelace-mushroom#517]
### Is your feature request related to a problem?

My fan only has 3 speeds: 33%, 66% and 100%. Currently it's difficult to select the correct speed, as you can see in this GIF:  

![fan](https://user-images.githubusercontent.com/96280/169736833-92cfaff1-7534-42c9-96d2-b7988a75fcf5.gif)

### Describe the solution you'd like

Instead of having 1% as threshold, it should be 33% instead (for my case). I found a similar example written in Vue: https://jsfiddle.net/qkuLdjt9/ (not the best example but you get the idea).  
  
![slide](https://user-images.githubusercontent.com/96280/169737540-fe44ef9f-0673-4b1e-b306-37573a43dc05.gif)
  
I think we can achieve this with Hammer.js too (not tested yet)

**Comment by piitaya** [comment]
Hello 🙂 What's your fan integration? 🙂

**Comment by redphx** [comment]
I'm using a Xiaomi Fan 1C with https://github.com/syssi/xiaomi_airpurifier.  
Here are some attributes of the fan
```
preset_modes: off, Level 1, Level 2, Level 3
oscillating: true
percentage: 66
percentage_step: 33.333333333333336
preset_mode: Level 2
model: dmaker.fan.p8
```

**Comment by piitaya** [comment]
What's the behavior of the `more-info` slider ? 🙂

**Comment by redphx** [comment]
Did you mean this?

![image](https://user-images.githubusercontent.com/96280/169770294-b1b8775b-6238-4e57-a875-964317ea32c5.png)

I tried to change it to "No Action" and it's still the same as before.

**Comment by piitaya** [comment]
![image](https://user-images.githubusercontent.com/5878303/169771724-a93a4abb-15fe-41e8-b462-0f8cec8ecedd.png)
 Does this slider work for all speed of your fan ?

**Comment by redphx** [comment]
Yes it does. The slider works exactly like I wanted to.  
![slide](https://user-images.githubusercontent.com/96280/169777127-31a387d6-5623-4524-aa21-d7398c8b5d5d.gif)
