### ISSUE TITLE
[Feature]: invert percentage in cover card

### ISSUE THREAD

**Issue by LudoARN** [piitaya/lovelace-mushroom#525]
### Is your feature request related to a problem?

I have tuya modules, but it report the wrong information in home assistant.
If i use motor reverse option, vocal action reverse too :-( 

100% = close
0% = open

Is it possble to add an option like invert_percentage: true, to solve the problem ?

Thanks

![image](https://user-images.githubusercontent.com/81586322/170448931-b18bee79-7672-4972-8d6d-3cb30e025663.png)

### Describe the solution you'd like

add an option like invert_percentage: true

**Comment by piitaya** [comment]
In HA, open is 100% and close is 0%. We will not propose an option to invert this to keep the HA logic.

**Comment by LudoARN** [comment]
Ok, however it could be very useful for many people who are using https://github.com/Deejayfool/hass-shutter-card with the invert_percentage.

Or did you have a solution to invert the value, using events or something else?

**Comment by piitaya** [comment]
It's an issue with tuya issue, not a interface issue. In my opinion, cards must not be used to fix integration issue.
