### ISSUE TITLE
[Feature]: Add hide_name configuration variable to fan card

### ISSUE THREAD

**Issue by GitHubGoody** [piitaya/lovelace-mushroom#529]
### Is your feature request related to a problem?

Sort of. The only way to hide the name is to set it to a space (' '), but that appears to take up space resulting in alignment issues.

### Describe the solution you'd like

Add a configuration variable to fan card (and maybe the other cards that don't have it) that would provide a way to completely remove the name field.

### Describe alternatives you've considered

Set name to a space (' '), but that appears to take up space resulting in alignment issues.

**Comment by piitaya** [comment]
Hello 🙂
It will be possible with https://github.com/piitaya/lovelace-mushroom/pull/528
