### ISSUE TITLE
[Bug]: Mushroom Fan Card UI Delay

### ISSUE THREAD

**Issue by claytonium13** [piitaya/lovelace-mushroom#539]
### Current Behavior

The state in the UI of the Mushroom Fan Card is delayed 5-10 seconds.  When pushed, the fan entity turns on however, the UI does not show that the fan turned on for a good 5-10 seconds.  It will update on its own after a long delay but will also update on its own by performing another action on the same entity.  For example, I have a button that turns the fan on to 25%.  If I tap the mushroom card THEN tap the button, the mushroom card UI updates and says that the fan is now on to 25%.    

### Expected Behavior

I would expect the UI to update and notify that the fan is on shortly after the button is pushed. 

### Steps To Reproduce

While running HA on a virtual Linux machine via VirtualBox on Windows 10, create mushroom fan card and attach to entity.  Attempt to turn on fan.  

### Environment

```markdown
Version	core-2022.5.5
Installation Type	Home Assistant OS
Development	false
Supervisor	true
Docker	true
User	root
Virtual Environment	false
Python Version	3.9.9
Operating System Family	Linux
Operating System Version	5.15.41
CPU Architecture	x86_64
Timezone	America/Chicago

Home Assistant Community Store
GitHub API	ok
GitHub Content	ok
GitHub Web	ok
GitHub API Calls Remaining	4954
Installed Version	1.24.5
Stage	running
Available Repositories	1045
Downloaded Repositories	7

Home Assistant Supervisor
Host Operating System	Home Assistant OS 8.1
Update Channel	stable
Supervisor Version	supervisor-2022.05.3
Docker Version	20.10.14
Disk Total	30.8 GB
Disk Used	6.5 GB
Healthy	true
Supported	true
Board	ova
Supervisor API	ok
Version API	ok
```

**Comment by piitaya** [comment]
What is the behavior with the other cards (official cards for example) ?

**Comment by claytonium13** [comment]
The official button cards call the service at a fan % and the UI works instantly.

**Comment by piitaya** [comment]
Which integration do you use for fan? It can be good to have the state of your entity too (available on developer page in HA).

**Comment by claytonium13** [comment]
I guess the integration would be Zwave JS.  The fan switches are Leviton ZW4SF controllers. I created button cards that call services to turn off, 25% on, 50% on, etc.  When I click the button card it turns yellow and the mushroom card actually displays the % and turns green (like it should). However, when I click the mushroom card the fan turns on and the standard buttons turn yellow instantly however, the mushroom card does not display the % nor turn green for a long time unless another action is performed (like clicking the 50% on button).  I've pasted some yaml for my "standard button" cards if that helps at all.  

type: vertical-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: fan.turn_off
      service_data: {}
      target:
        device_id: d841b2f8df45069fcedd44df95ad2727
    entity: fan.west_bedroom_fan
    name: Fan Off
    icon: mdi:fan-off
  - type: grid
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: fan.set_percentage
          service_data:
            percentage: 25
          target:
            device_id: d841b2f8df45069fcedd44df95ad

**Comment by claytonium13** [comment]
After playing around with this a bit more I think the problem is actually not with the mushroom card.  When I create a button that toggles the fan instead of calling a fan speed %, the change in state is delayed.  I'm not sure what the real cause is now.

**Comment by claytonium13** [comment]
> 

My final solution was to create scripts that would toggle the fan then refresh the value.  I did it in the visual editor but the yaml is as follows:

alias: Living Room Fan Script
sequence:
  - type: toggle
    device_id: d546c24d1a84e8ab1fbe9651c4745307
    entity_id: fan.living_room_fan
    domain: fan
  - device_id: d546c24d1a84e8ab1fbe9651c4745307
    domain: zwave_js
    entity_id: fan.living_room_fan
    type: refresh_value
mode: single
icon: mdi:fan
