### ISSUE TITLE
Idea: Allow colored icons/sliders corresponding to theme color

### ISSUE THREAD

**Issue by almostserious** [piitaya/lovelace-mushroom#54]
Im not sure if this is even possible, but would be awesome if the colors could take their value from the themes defined color scheme. 
i.e.: Currently the Fan Card is Green, while the Light Card is Orange.

Possibly the primary-color?

Example from Google light theme:
```
  # Main Interface Colors
  primary-color: rgb(26, 115, 232)
```

**Comment by piitaya** [comment]
It will be possible when themes will be released (next release of mushroom) : https://github.com/piitaya/lovelace-mushroom-themes
