### ISSUE TITLE
Binary Sensor Off Adds Disabled Tag/Changes Color

### ISSUE THREAD

**Issue by codeinstitution** [piitaya/lovelace-mushroom#543]
### Current Behavior

Hi,

I've attached a screenshot of what my binary door sensor looks like when the door is closed. I've attached the default lovelace card for reference:

![image](https://user-images.githubusercontent.com/106209587/172066199-dac87d24-f10c-4734-a4f6-103453a3de20.png)

This is what it looks like when opened:
![image](https://user-images.githubusercontent.com/106209587/172066210-fabf930e-ed21-49ab-8786-152b131b9c19.png)

As you can see it adds a disabled tag and changes the color from blue filled to gray filled. Is it possible to remove/disable the disable tag? I've attached a screenshot of how it looks when I manually use inspect editor to remove the tag:

![image](https://user-images.githubusercontent.com/106209587/172066244-46567603-59d1-4cc2-8ec7-c12c0a685827.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/106209587/172066244-46567603-59d1-4cc2-8ec7-c12c0a685827.png)

### Steps To Reproduce

`code
type: custom:mushroom-entity-card

    entity: binary_sensor.aqara_front_door_sensor

    secondary_info: state

    fill_container: false

    hide_icon: false

    use_entity_picture: true

    primary_info: name`

### Environment

```markdown
- Hassio: 2022.6.2
```

### Anything else?

Thanks! I just want it to look the same as the default Home Assistant while I get used to it.

**Comment by piitaya** [comment]
Hello 🙂 it's not a bug, it's by design. 
You can use template card if you need custom color rules.

**Comment by codeinstitution** [comment]
Oh ok. 

I was able to fix it with a custom template card, here's the code for anyone else:

```type: custom:mushroom-template-card
    primary: '{{ device_attr("binary_sensor.aqara_front_door_sensor", "name_by_user") }}'
    secondary: >
      {% if is_state("binary_sensor.aqara_front_door_sensor", "on") -%} Opened
      {%- else -%} Closed {%- endif %}
    icon: >
      {% if is_state("binary_sensor.aqara_front_door_sensor", "on") -%}
      mdi:square-outline {%- else -%} mdi:square {%- endif %}
    entity: binary_sensor.aqara_front_door_sensor
    icon_color: >
      {% if is_state("binary_sensor.aqara_front_door_sensor", "on") -%} red {%-
      else -%} blue {%- endif %}```
