### ISSUE TITLE
[Feature]: use_entity_picture in Template card

### ISSUE THREAD

**Issue by golles** [piitaya/lovelace-mushroom#547]
### Is your feature request related to a problem?

For a few cards I like to have a bit more control over the output, in those cases I use a Template card instead of an Entity card. This works usually great, however now I ran into an entity that has an `entity_picture` attribute.
In the Template card I can only set an icon and not a picture,

### Describe the solution you'd like

Have `use_entity_picture` as an option in the Template card. Or maybe an URL of an image?

### Describe alternatives you've considered

I'm using `custom:button-card` now

**Comment by piitaya** [comment]
Duplicate #457
There is already an feature request for this
