### ISSUE TITLE
[Bug]: template card not rendering icon and icon_color

### ISSUE THREAD

**Issue by 123dev** [piitaya/lovelace-mushroom#548]
### Current Behavior

Template is not rendering for 

- icon
- icon_color

However it renders properly for

- primary
- secondary

### Expected Behavior

We expect it to render properly.

### Steps To Reproduce

We have a presence integration that creates a sensor as follow
<img width="306" alt="image" src="https://user-images.githubusercontent.com/13109154/172723377-7e613a1b-3730-4773-9fda-c6125f2f0e06.png">

We're using Template card like this
```
type: custom:mushroom-template-card
primary: '{{ states(''sensor.presence_REDACTED'') }}'
secondary: '{{ states[''sensor.presence_REDACTED''].attributes.availability }}'
icon: '{{ states[''sensor.presence_REDACTED''].attributes.icon }}'
icon_color: '{{ states[''sensor.presence_REDACTED''].attributes.color }}'
tap_action:
	action: more-info
entity: sensor.presence_REDACTED
fill_container: false
```

As seen, `availability` is an attribute similar to `icon` and `color`.
Code renders properly for secondary, but not for `icon` or `icon_color`

In fact it break the rest of the rendering, and even primary / secondary don't get displayed if icon and icon_color have the above code.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/13109154/172723231-4308ac51-4928-462f-83a7-8fd93e4275bd.png">

### Environment

```markdown
- OS: Ubuntu
- Browser: Chrome
- Version: 1.9.0
- Hassio: Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
```

**Comment by 123dev** [comment]
Thanks for getting back.
I changed it to this, but it is still not rendering, am I misusing?

```
icon: '{{ state_attr(''sensor.presence_REDACTED'', ''icon'' }}'
icon_color: '{{ state_attr(''sensor.presence_REDACTED'', ''color'' }}'
```

**Comment by piitaya** [comment]
Try to remove the quotes outside the brackets {{}} 🙂

**Comment by 123dev** [comment]
> 

What I pasted is the YAML version, in Visual Editor is without quotes, and the two single quotes are one single quote.
If I remove the quotes outside the brackets in YAML, then it totally breaks and nothing renders.

**Comment by 123dev** [comment]
Apologies, it might be working, I think the attributes were not properly updated and it was throwing me off.
I will do some troubleshooting and report back, I believe state_attr is good to use.

**Comment by 123dev** [comment]
Thank you @piitaya it's working all good now, and by the way, wonderful project.
This issue can be resolved as None Issue
