### ISSUE TITLE
[Bug]: Oscillate button can't be clicked/tapped, doesn't do anything

### ISSUE THREAD

**Issue by user897943** [piitaya/lovelace-mushroom#549]
### Current Behavior

My AC has oscillation, and tapping the oscillate button on the mushroom fan card (the fan is a separate entity on the fan domain, not in the climate domain) does not turn it on or off. The button has a prohibited icon on it when the cursor is over it, and can't be clicked or tapped.

### Expected Behavior

Button turns oscillation on or off.

### Environment

```markdown
- OS: Debian 11
- Hassio: Docker 2022.6.3
```

**Comment by piitaya** [comment]
Hello. Can you provide the state of your entity available in the developer tools ? 🙂

**Comment by user897943** [comment]
> Hello. Can you provide the state of your entity available in the developer tools ? 🙂

Howdy. Sure, here it is:
```
preset_modes: null
oscillating: true
percentage: 33
percentage_step: 33.333333333333336
preset_mode: null
friendly_name: AC - Front room (Fan)
supported_features: 3
```
