### ISSUE TITLE
[Switch button]: Add Switch button to the controls same as light button

### ISSUE THREAD

**Issue by roshanabady** [piitaya/lovelace-mushroom#552]
### Is your feature request related to a problem?

I always use light cards to modify the yaml to add a light-switch.
It would be great to have a dedicated card for light-switches as well.

### Describe the solution you'd like

It seems the light function is very similar to the light-switch.
therefore the light function could be duplicated and tweaked to get the light-switch added to the mushroom cards.

### Describe alternatives you've considered

As mentioned earlier I have used light and/or entity cards instead and modified the yaml files to get my switch cards.

**Comment by piitaya** [comment]
I don't really understand what you call light switch. If you want switch card, you can use the entity card with toggle tap_action.

**Comment by roshanabady** [comment]
No worries, mate.
Cheers for the excellent work.
