### ISSUE TITLE
[Feature]: Use attribute of element on Entity card

### ISSUE THREAD

**Issue by Xaldimo** [piitaya/lovelace-mushroom#558]
### Is your feature request related to a problem?

When adding a Mushroom Entity Card only the main state will be shown.

### Describe the solution you'd like

When creating a Mushroom Entity Card have the possibility to selection optional attribute to show.

**Comment by Xaldimo** [comment]
Ah OK. Let me have a play with that. Thanks for the pointer :smile:

**Comment by jamesmyatt** [comment]
Is there an example of this in the docs?
