### ISSUE TITLE
Any way to remove the gap between two horizontally stacked cards?

### ISSUE THREAD

**Issue by 123dev** [piitaya/lovelace-mushroom#559]
### Is your feature request related to a problem?

We have horizontally stacked two cards that we need to unite and show as single card.
The left card is a mushroom-entity-card with secondary information
The right card is a mushroom-template-card again with primary and secondary information.
We want to have a card that presents all of the information above as a single unit, but because there is no such card we are using horizontally stacked cards.

### Describe the solution you'd like

Is it possible to eliminate the gap between the two cards hence the two appearing as a single card?

Ideally one card offering more than primary / secondary information would work as well

**Comment by piitaya** [comment]
Hi 🙂 You can use https://github.com/ofekashery/vertical-stack-in-card or https://github.com/custom-cards/stack-in-card for this.

**Comment by 123dev** [comment]
@piitaya You're awesome, thanks.
Worked beautifully.
For the record in case anyone else stumbles on this, I used the veritical-stack-in-card
All I had to do is replace
```
  - type: horizontal-stack
```
with
```
  - type: 'custom:vertical-stack-in-card'
    horizontal: true
```
