### ISSUE TITLE
[Bug]: Haptics?

### ISSUE THREAD

**Issue by roflcoopter** [piitaya/lovelace-mushroom#560]
### Current Behavior

None of my `mushroom-cards` provide haptic feedback when interacting with them.

It is working fine on `custom:button-card` and other UI elements, but not the `mushroom-cards`
Running on iOS.

Is there anything that needs to be done in order to get Haptics to work?

### Expected Behavior

I expect to get haptic feedback when clicking on a chip for example

### Steps To Reproduce

Create any card, no haptics provided

### Environment

```markdown
- OS: Ubuntu 20.04, Docker
- Version: 1.10.0
```

**Comment by roflcoopter** [comment]
On iOS that setting does not appear, it respects the [system settings](https://companion.home-assistant.io/docs/integrations/haptics/#disabling-haptics), and there it is enabled

**Comment by piitaya** [comment]
It works out of the box. No configuration needed.
How long have you had the problem?

**Comment by roflcoopter** [comment]
It has never worked for me, started using mushroom cards (which are great btw) at around version 1.6, dont remember exactly

**Comment by roflcoopter** [comment]
Just tried clearing cache and reloading but it did not help

**Comment by roflcoopter** [comment]
Iphone X, iOS 15.5.
Wife has iPhone 13, iOS 15.5 as well, same issue occurs for her

**Comment by piitaya** [comment]
Strange, may be you have another card that interfer with haptic. I don't known why you have this issue 😟

**Comment by roflcoopter** [comment]
> 

Strange indeed, i will investigate by disabling all other resources and see if i can find another card thats breaking it
