### ISSUE TITLE
[Bug]: After upgrade to v2 mushroom cards started failing

### ISSUE THREAD

**Issue by LeeTaylorX12** [piitaya/lovelace-mushroom#574]
### Current Behavior

Did theupdate to v2 and on my andriod phone pretty much every mush card I had started failing.  

big red mushroom card xxxxx does not exist

Desktop browser seemd fine.

Reverted back to 1.10 and everything worked again

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by piitaya** [comment]
Hello. Could you provide the logs from your browser console ? 🙂

**Comment by LeeTaylorX12** [comment]
> 

Its the HA app.  custom element does not exist.  that goes for every mushroom element i am using, chip,entity, lights, etc  On the firefox browser i have on my note10  it seems fine.

there is nothing in the system logs which is talking to any issues with mushroom.  is there anything on the phone app I can provide?

**Comment by KTibow** [comment]
Try closing the app (from the activities view, don't just go to the home screen) and re-opening it again. If that doesn't work, try clearing the cache in the HA app settings. If that doesn't work, try clearing the data (warning: you will be signed out).
