### ISSUE TITLE
[Bug]: Slider doesn't "snap" to step values.

### ISSUE THREAD

**Issue by acshef** [piitaya/lovelace-mushroom#576]
### Current Behavior

Example, given a fan with step size 33.3333:

1. Fan is initially off
2. User drags or tap position ~40%
3. Slider "snaps" to position 33% (fan is set to 33%, aka low) - *this is expected, existing behavior in mushroom*
4. User again drags or taps again to position ~40%, slider settles at 40% position instead of moving to nearest step

### Expected Behavior

Upon selecting a different *value* that ultimately resolves to the same *step position*, the slider should "snap back" to the original step position.

### Steps To Reproduce

See example above (use a fan entity with step 33.3333)

### Environment

```markdown
- OS:Ubuntu 20.04
- Browser: chrome
- Version: 1.10.0
- Hassio: 2022.6.7
```

### Anything else?

I have a PR ready to address this 😁 https://github.com/piitaya/lovelace-mushroom/pull/582

**Comment by acshef** [comment]
Holy cow, congrats on v2.0.0! I upgraded to mushroom 2, and confirmed the issue is still present. (I'll rebase/revise my PR in the future, once this ticket is deemed worthy)

**Comment by KTibow** [comment]
@acshef if #582 fixed this issue, can it be closed?

**Comment by acshef** [comment]
Not sure of the preferences of this project; should issues be closed when a bugfix/feature PR is merged, or wait until there's a tagged release that contains the bugfix/feature?

**Comment by piitaya** [comment]
"Fixes ###" auto close this issues. But only the issue number was present in the PR.
I close it manually 🙂
