### ISSUE TITLE
[Bug]: Alarm icons and colors are different from HA

### ISSUE THREAD

**Issue by FaBRiK74** [piitaya/lovelace-mushroom#579]
### Current Behavior

Currently the colors and icons are different from the original HA alarm panel. E.g. the icon is green when it is armed, which should be red.

### Expected Behavior

Disarmed: green with a tick in a shield (mdi:shield-check)
Pending: flashing orange with an empty shield (mdi:shield-outline)
Armed home: red with a house in a shield (mdi:shield-home)
Armed away: red with a padlock (mdi:shield-lock)
Triggered: red with a bell (mdi:bell-ring)

See the animated GIF at HA's official site: https://www.home-assistant.io/dashboards/alarm-panel/

**Comment by piitaya** [comment]
It's not a bug. The idea is to keep red color for alert. Green means you can house is protected with the alarm.

You can override all these colors using mushroom theme to revert to the official ones 🙂

**Comment by FaBRiK74** [comment]
Maybe an option would be useful to choose between Mushroom coloring (as you described, with the theme) and HA style

**Comment by piitaya** [comment]
You can add these mushroom variables in your themes to redefine them :
```
mush-rgb-state-alarm-disarmed: var(--mush-rgb-info)
    mush-rgb-state-alarm-armed: var(--mush-rgb-success)
    mush-rgb-state-alarm-triggered: var(--mush-rgb-danger)
```

Replace the values by the color you want 😊
