### ISSUE TITLE
Add iframe card

### ISSUE THREAD

**Issue by cyrilphoenix71** [piitaya/lovelace-mushroom#58]
It would be nice to have the possibility to add a simple iframe card to have a card like :
https://www.reddit.com/r/homeassistant/comments/9yk21k/lovelace_embed_darksky_map/
but with mushroom theme

**Comment by piitaya** [comment]
A built-in card already exist for that : https://www.home-assistant.io/lovelace/iframe/

**Comment by pierrecle** [comment]
> It would be nice to have the possibility to add a simple iframe card to have a card like : https://www.reddit.com/r/homeassistant/comments/9yk21k/lovelace_embed_darksky_map/ but with mushroom theme

Actually there is no theme embedded in mushroom, it works without theme. Mushroom cards are HASS cards, only what's inside is changed, not the container. As @piitaya said, use the default iframe card will have exactly the same result.
