### ISSUE TITLE
[Feature]: Entity picture in template chip?

### ISSUE THREAD

**Issue by chertvl** [piitaya/lovelace-mushroom#583]
### Is your feature request related to a problem?

Hey!
Is it possible with using last update to make entity picture in template chip? Annotation says "entity pictures added in all cards", but I can't understand how. For me in chips works only old format "use entity picture: true" (entity chip).
If answer is not, can we add this?
Thanks!

### Describe the solution you'd like

Use entity pictures in template chip

**Comment by chertvl** [comment]
> Hey 🙂 I missed the template chip 🤦‍♂️
> Feel free to create a PR for this. Otherwise, I will do it. 🙂

Thanks for the answer
I just don't know how :D Ill wait your solution, take your time.
Many thanks, appreciate it!

**Comment by piitaya** [comment]
It's already supported for all cards 🙂

**Comment by alexreddy78** [comment]
Dear Paul,

Any chances to see this feature in chip template card in the nearest future? :)

Regards

**Comment by piitaya** [comment]
Hi. A pull request is linked to this issue. It will be included in the next version 😉
