### ISSUE TITLE
[Bug]: wrong colour brightness slider at bluest color temperature for light card

### ISSUE THREAD

**Issue by woytekbode** [piitaya/lovelace-mushroom#589]
### Current Behavior

The color of the brightness slider for the light card shows grey when the light is set to the coldest color temperature. 

### Expected Behavior

Brightness slider should be white

### Steps To Reproduce

Add light card
Set color temperature to coldest
Observe brightness slider color

### Environment

```markdown
HA OS 8.2
HA 22.7.02b
Mushroom cards v2.0.0
```

**Comment by piitaya** [comment]
Hi 🙂 It's grey for contrast. If it was white, we will see nothing.

**Comment by woytekbode** [comment]
> Hi 🙂 It's grey for contrast. If it was white, we will see nothing add we can not control anything.
I'll try to show you what I mean with some screen captures:
![mushroom_card_light_warm](https://user-images.githubusercontent.com/67194886/176973464-ad019093-9674-4ffe-920e-a4a6a07178cc.png)
![mushroom_card_light_cool](https://user-images.githubusercontent.com/67194886/176973466-e7d02b2a-7e73-4a0d-abdc-542ae698be13.png)
![mushroom_card_light_coolest](https://user-images.githubusercontent.com/67194886/176973465-7a7eb665-22d3-4068-adc5-13b250646741.png)

**Comment by KTibow** [comment]
With the normal light theme, this would be a problem.

**Comment by woytekbode** [comment]
> With the normal light theme, this would be a problem.

I can imagine but with a dark theme it looks off. Maybe add this as an option?

**Comment by KTibow** [comment]
Either that or somehow calculate the background color of the card and see how white it is.

**Comment by piitaya** [comment]
If you found a way to improve the color without impacting the readability, feel free to do a PR 🙂

**Comment by woytekbode** [comment]
> If you found a way to improve the color without impacting the readability, feel free to do a PR 🙂

It's a difficult one! I have thought a bit about this but haven't been able to come up with a solution. For now I think I'll live with the current implementation or go back to the version without the light color in the brightness slider.

**Comment by piitaya** [comment]
Mine with the coldest temperature color (I use the Mushroom theme but it works for default theme too):

Light theme :
<img width="239" alt="Capture d’écran 2022-07-03 à 23 11 47" src="https://user-images.githubusercontent.com/5878303/177057410-957cfb93-73b4-4063-a144-77be94fe37d4.png">

Dark theme :
<img width="237" alt="image" src="https://user-images.githubusercontent.com/5878303/177057419-528bf635-2841-4f26-8ebf-480d904106f5.png">
