### ISSUE TITLE
[Bug]: Curtain group

### ISSUE THREAD

**Issue by fantnhu** [piitaya/lovelace-mushroom#590]
### Current Behavior

Hi!
Shutter and curtain cards work well with 1-1 devices.
There are 2 Switchbot ROD2 that move on the same curtain cornice (one to the right, the other to the left).
It appears well separately on the card, but then you need 2 cards.
I put them in a group, they work well that way. The group domain is also "cover" here.
But the group doesn't show well on the card: open and close icon and the default entity icon.
Do you have an idea for this?
Thank you very much :)

![image](https://user-images.githubusercontent.com/73642352/176989684-07553a42-7dc7-4ada-9082-8f2f4783b774.png)

### Environment

```markdown
- OS: Virtualbox
- Node: Chrome, + Nest HUB2 cast
- Version: 2.0
- Hassio: 2022.6.6
```

**Comment by piitaya** [comment]
Hello, you need to change the device class of your group 🙂

**Comment by fantnhu** [comment]
wonderful! :) thanks for the quick reply and the solution!
