### ISSUE TITLE
[Bug]: Back button chip card on HA iOS Companion app 2022.358

### ISSUE THREAD

**Issue by ZoltrixGFC** [piitaya/lovelace-mushroom#592]
### Current Behavior

If the official HA app is forced closed, when reopened, the "Back" chip card no longer works.

Unlike Android, if you force close, the HA app goes back to the default screen. The iOS app continues where it left off, and if that page has a chip card with the "Back" option, it no longer functions.

### Expected Behavior

A way for the "Back" button to work, or a way to program it to go back to a default location?

### Steps To Reproduce

- Open the iOS Companion app, goto a page with a "Back" chip card
- Force close the app
- Open the app
- Try and use the "Back" chip card

### Environment

```markdown
- OS: iOS 15.5
- App: iOS Companion app 2022.358
- Hassio: 2022.6.7
```

**Comment by piitaya** [comment]
You can use an action chip with a navigate tap-action and choose your default page.

The back action use the browser history and the history is not saved when reloading the app.

**Comment by ZoltrixGFC** [comment]
ahh, didn't think of that... thank you for clearing that up, and sorry for wasting your time 😳

**Comment by piitaya** [comment]
No problem 🙂
