### ISSUE TITLE
[Feature]: Add Picture Path Support to Entity and Light Cards

### ISSUE THREAD

**Issue by Daniel-dev22** [piitaya/lovelace-mushroom#600]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

It would be helpful to specify a path for a picture in an entity or light card. 

Just as the template card allows. 

![Screenshot_20220708-104717_Home Assistant](https://user-images.githubusercontent.com/47092714/178020666-92059876-6499-4ca4-81c0-8ffa38e5a324.jpg)

### Describe alternatives you've considered

Hardcoding using customize entities.

**Comment by piitaya** [comment]
The proper way to do this is using the `customize.yaml` as you describe as considered alternative.

Only template cards will have advanced options like this.
