### ISSUE TITLE
[Bug]: Gracefully handle unknown (unavailable) entities - when state object is missing in hass.states

### ISSUE THREAD

**Issue by kulmegil** [piitaya/lovelace-mushroom#602]
### Current Behavior

When entity state is not available in hass.states lot's of JS errors are spammed.
This can happen when e.g. 
- "legacy" integration fails to setup entity without uniqueId (read-only entity).
- user changed entity_id without performing changes to lovelace config.

Card is not rendered.

### Expected Behavior

Gracefully handle situation without throwing JS errors.

Render empty "unavailable" card (e.g. using entity_id as primary text). 
Or display "error card".

### Steps To Reproduce

1. Create any mushroom card related to an entity
2. Set entity_id to non existing entity (or change entity_ids after creating card)

### Environment

```markdown
- OS: Windows / Android
- Browser: Chrome / Firefox / native app
- Version: any
- Hassio: 2022.7
```

### Anything else?

![js_error](https://user-images.githubusercontent.com/570575/178161251-100cdd12-88ff-4a5f-accb-a8c906676855.png)

**Comment by areyoufserious** [comment]
This issue significantly affects frontend performance

**Comment by KTibow** [comment]
I'm working on a fix. How should this be handled?
1. Make the card be nothing
2. Pretend the entity has an unknown state
3. Make a custom error card to show in place of it

**Comment by piitaya** [comment]
It think just render `null` is enough for now.

**Comment by KTibow** [comment]
https://github.com/piitaya/lovelace-mushroom/blob/588a9ea5c74ae527c35dadde4d4e474fb24e6d02/src/cards/entity-card/entity-card.ts#L81-L84
If the entity doesn't exist, it tries to get attributes, which is null, so it does `null.friendly_name`.

**Comment by shbatm** [comment]
Any update on this, just recently came across what looks to be the same issue; happy to test or support if needed.

![image](https://user-images.githubusercontent.com/18057952/233416890-5f4c8e71-1db1-4095-b100-1d0dc072ee77.png)
