### ISSUE TITLE
[Bug]: Error in install instructions: No section called "frontend"

### ISSUE THREAD

**Issue by OZ1SEJ** [piitaya/lovelace-mushroom#606]
### Current Behavior

The current installation instructions read:

> **Installation
> HACS**
> 
> Mushroom is available in [HACS](https://hacs.xyz/) (Home Assistant Community Store).
> 
> 1. Open HACS
> 2. Go to "Frontend" section

There is no section on hacs.xyz called "Frontend". Thus the installation instructions fail in step two.

### Expected Behavior

I would expect the installation instructions to be able to tell me how to install mushroom.

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by piitaya** [comment]
Hi 🙂
HACS is an integration for Home Assistant. You need to install it on your instance. Then, you can add community cards or integration like Mushroom. You must follow these steps before installing Mushroom : https://hacs.xyz/docs/setup/prerequisites

If you don't want to install hacs, you can follow the manual steps : https://hacs.xyz/docs/setup/prerequisites
