### ISSUE TITLE
[Feature]: Make the size of "chips" variable

### ISSUE THREAD

**Issue by tannisroot** [piitaya/lovelace-mushroom#608]
### Is your feature request related to a problem?

I am not sure if this is specific to my phone (Galaxy S10e, fairly small one), but the buttons in "chips" entity appear fairly small on mine, which is especially an issue for the hamburger menu and back "chips". I really have to aim at the buttons to hit them, which is quite annoying.
For comparison, here's a screenshot where you can see how much smaller the hamburger menu button is than Home Assistant's own:
![image](https://user-images.githubusercontent.com/10602045/178701603-4a871f83-7a22-4f89-906c-d34b2e979d18.png)

### Describe the solution you'd like

It would be nice if there was an option that would allow the user to scale chips in %, so 100% being the default, below that smaller, and above that larger.

**Comment by piitaya** [comment]
Hi 😊
You can customize chip size using theme variables if you want : https://github.com/piitaya/lovelace-mushroom-themes

**Comment by tannisroot** [comment]
Yeah I am aware of that, but tbh I don't quite understand how to use it, there's no documentation in Readme nor did I find any guides that would help me understand how to resize the chips entity card using that.

**Comment by ulic75** [comment]
You wouldn't put it into your dashboard, you add to a theme file.  There are two minimal sample theme files in the theme directory at the link piitaya provided.  The readme in that repo shows all the possible items that can be configured via theming.

**Comment by tannisroot** [comment]
oh i see! didn't know that's where it's supposed to go. all works now, ty
