### ISSUE TITLE
Display picture in person entity chip

### ISSUE THREAD

**Issue by cyrilphoenix71** [piitaya/lovelace-mushroom#61]
Add option to show person picture in chips person card would be better

**Comment by pierrecle** [comment]
You can add a badge for this ;)

**Comment by cyrilphoenix71** [comment]
I'm not sur to understand, can you explain a bit more ?

**Comment by pierrecle** [comment]
Sorry I was wrong on a point, you cannot hide name etc on person badge. We discussed with @piitaya about the ability to use card without background, border, padding and shadow (ie. what makes a card, a card). We have no plane for this at all, I'll explain why in one of your other issue.

**Comment by cyrilphoenix71** [comment]
No problem don't worry :) may be my issue is not clear. What I suggest it's just a little things
Actualy in chips card, by defaut a person chips is add, we can custom it with a icon.
My suggest is to have the possibility to use the profil picture instead icon like the person card option

**Comment by pierrecle** [comment]
@piitaya ?

**Comment by piitaya** [comment]
There is person-chip for now. Maybe we can add it in the future but I don't think we must add a picture option in entity chip

**Comment by pierrecle** [comment]
> There is no person-chip for now. Maybe we can add it in the future but I don't think we must add a picture option in entity chip

You can add a entity chip with the person entity. That's also my opinion for the picture.

**Comment by pierrecle** [comment]
I'll create a person chip.
