### ISSUE TITLE
[Feature]: make a room card

### ISSUE THREAD

**Issue by jorishaverkort** [piitaya/lovelace-mushroom#612]
### Is your feature request related to a problem?

Holds me back from switching to UI fully

### Describe the solution you'd like

One of the cards I miss the most still to have a full UI dashboard is the room custom card from Lovelace minimalist. Would be awesome to have something similar with option for square or rectangular shape and multiple entities to change

**Comment by piitaya** [comment]
Duplicate https://github.com/piitaya/lovelace-mushroom/issues/55
