### ISSUE TITLE
[Bug]: Can’t find Climate Card

### ISSUE THREAD

**Issue by wwalcher** [piitaya/lovelace-mushroom#621]
### Current Behavior

I have upgraded to the latest version, but when I go to the HA dashboard and try to add the climate card, I cannot find it. What am I missing?

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by Athlon646464** [comment]
I have the same issue.
(I will admit to being a n00b to HA.)
Could I have omitted a step after updating? I've been using Mushroom for about a week - love it.

**Comment by Athlon646464** [comment]
Perhaps I should have included the fact I updated Mushroom twice this morning (was prompted to each time). Not sure if this might be relevant.

**Comment by AndrzejOlender** [comment]
I have the same issue.

**Comment by piitaya** [comment]
Hi, try these steps : 
- uninstall Mushroom
- remove Mushroom ressources (if present)
- reinstall Mushroom

**Comment by wwalcher** [comment]
FYI, I have the latest version of the HA software on an Intel machine.

**Comment by Athlon646464** [comment]
Reinstalling worked.....
You are a God! Thank you!! :)

**Comment by piitaya** [comment]
It is often a cache issue 😅

**Comment by milandzuris** [comment]
every update i have same issue wtf

**Comment by wwalcher** [comment]
Well, I checked it again from a different device and now it is showing up.
I did not remove it or anything.  I guess is was a cache or timing issue.

**Comment by Volkoks** [comment]
Hello, 
I deleted the HACS mushroom, deleted the cache from www, restarted the HA, but the mushroom maps are still displayed and the climate did not appear.

**Comment by piitaya** [comment]
> Hello, 
> I deleted from the HACS mushroom, deleted the cache from www, restarted the HA, but the mushroom maps are still displayed and the climate did not appear.

Did you remove mushroom from your ressources ?

**Comment by milandzuris** [comment]
reinstall help me

**Comment by Volkoks** [comment]
> > Здравствуйте, 
> > удалил с HACS гриб, удалил кеш с www, перезапустил HA, но карты грибов все равно отображаются и климат не появился.
> 
> Вы удалили гриб из ваших ресурсов?

 yes, HA tupanul)))) everything is ok

**Comment by wenjiavv** [comment]
In my case, try the ctrl+shift+n in chrome, solved~
and clear cache in home assistant ios app setting.
good luck

**Comment by alex85us** [comment]
I have the same issue where it works fine on the browser but got error on the APP (iPhone and Fire HD).
Error:
Custom element doesn't exist: mushroom-climate-card.
Already tried your recomendation about removing it from resources, deleting the files and then installing it again with no luck.

Thank you for the effort and work on this beautiful card.
