### ISSUE TITLE
[Feature]: Allow to specify code from UI Setup

### ISSUE THREAD

**Issue by briis** [piitaya/lovelace-mushroom#626]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

When the Alarm System requires a code to arm or disarm, the only way to supply this code is to open the number panel. 
I would request the feature, that the code can be set when adding the card, and then added to the service call when pressing the Arm or Disarm buttons in the UI. 
This is to avoid having the Number panel displayed, but still being able to call the service.

### Describe alternatives you've considered

I was thinking about calling an automation from the `tap_action`, and then supplying the code in that automation. But the `tap_action` does not seem to called from the buttons, but rather clicking outside the buttons.
So the other alternative would be to be able to supply a `tap_action` to each button, but this seems much more complicated than just sending the code.

**Comment by piitaya** [comment]
Hi 🙂
Why not just disable the code on your alarm entity?

**Comment by briis** [comment]
Hi Paul,
Good suggestion, however this is not possible on my alarm system (Verisure). There has to be a code for each user, or the system will not work. 
So I still hope this would be doable?

**Comment by KTibow** [comment]
This sounds insecure. Anyone who could view your dashboard could disable your alarm.

**Comment by briis** [comment]
> This sounds insecure. Anyone who could view your dashboard could disable your alarm.

Fair point. Until now I have a customized Button Card, where I trigger a Switch in Node-Red, and supply the name of the button that has been pressed. Then all the Magic happens in Node-Red. The same could be done by an HA Automation with the code in the Secret file. But I need to know what button is pressed to build the Service Call

**Comment by piitaya** [comment]
You can disable your code using https://www.home-assistant.io/integrations/alarm_control_panel.template/ if you want. I don't think it's the role of frontend card to solve this kind of problem 😅

**Comment by briis** [comment]
I was not aware of alarm panel template. I think that should do the trick, thanks. Closing this.
