### ISSUE TITLE
[Feature]: Climate Card - Support for KNX operational modes

### ISSUE THREAD

**Issue by nuggie** [piitaya/lovelace-mushroom#627]
### Is your feature request related to a problem?

First: Thanks for the climate card!!!
Having additional support for KNX operational modes would be awesome!

### Describe the solution you'd like

List of buttons like the HVAC buttons.

For operational modes see: https://www.home-assistant.io/integrations/knx/#climate

Operation modes most of KNX actuators support:

Auto 
Comfort 
Standby 
Night
Frost

**Comment by piitaya** [comment]
Duplicate #615 because knx operations are preset modes.
