### ISSUE TITLE
[Feature]: <title>

### ISSUE THREAD

**Issue by RASBR** [piitaya/lovelace-mushroom#631]
### Is your feature request related to a problem?

Hi,
for my AC I use cool/heat modes. Currently in the summer it is always on cool mode. but whenever it is switched on it starts with heat mode. 

### Describe the solution you'd like

I think it should remember the last state

**Comment by piitaya** [comment]
What you A/C ? How do you turn it on from the mushroom card ?

**Comment by RASBR** [comment]
Hi, AC is DAIKIN connected via Zennio KNX and defined in HA as follows:
`climate:
    - name: "GF Office AC"
      on_off_address: "1/5/1" # AC On/Off
      on_off_state_address: "1/5/2" # AC On/Off Status
      temperature_address: "1/4/48" # ROOM TEMPERATURE
      target_temperature_address: "1/4/45" # Setpoint
      target_temperature_state_address: "1/4/46" # Setpoint Status
      heat_cool_address: "1/5/5" # AC Simplified Mode
      heat_cool_state_address: "1/5/6" # AC Simplified Mode Status
      min_temp: 16
      max_temp: 28`

And the card code:
  `type: custom:mushroom-climate-card
  entity: climate.gf_office_ac
  fill_container: false
  show_temperature_control: true
  hvac_modes:
    - heat
    - cool
  hold_action:
    action: more-info
  name: AC
  icon: mdi:sun-snowflake`

I hope this answers your inquiries.
RS

**Comment by piitaya** [comment]
It's not a mushroom issue : https://community.home-assistant.io/t/is-there-a-way-to-establish-cool-as-default-turn-on-mode-on-climate/132754
As a workaround you can create a script and call it when using tap action.
