### ISSUE TITLE
Climate card not working on mobile app

### ISSUE THREAD

**Issue by Toinieboy** [piitaya/lovelace-mushroom#633]
### Current Behavior

Shows a custom element does not exist error. It works on web though

### Environment

```markdown
- OS: IOS
- Node:
- Version:
- Hassio:
```

**Comment by piitaya** [comment]
Duplicate https://github.com/piitaya/lovelace-mushroom/issues/621

**Comment by alex85us** [comment]
I have the same issue where it works fine on the browser but got error on the APP (iPhone and Fire HD).
Error:
Custom element doesn't exist: mushroom-climate-card.
Already tried your recomendation about removing it from resources, deleting the files and then installing it again with no luck.

**Comment by adamcodemaker** [comment]
I also have this issue on android.
