### ISSUE TITLE
[Feature]: Climate default mode when powered on

### ISSUE THREAD

**Issue by jncanches** [piitaya/lovelace-mushroom#634]
### Current Behavior

When you click on the icon to turn on the climate device, it defaults to heat ( I have heat and cool activated ).
This is great on winter but not so "cool" in summer.

### Expected Behavior

It will be great if we can select the default mode when the device is powered on.

It could be easy using template for tap_action 
if off then 
    set_hvac_mode to cool 
else 
    turn off

### Environment

```markdown
- Version: 2.1.1
- Hassio: 2022.7.3
```

**Comment by piitaya** [comment]
It's not a mushroom issue : https://community.home-assistant.io/t/is-there-a-way-to-establish-cool-as-default-turn-on-mode-on-climate/132754
As a workaround you can create a script and call it when using tap action.
