### ISSUE TITLE
[Feature]: Skip decimal in temperature selector

### ISSUE THREAD

**Issue by jncanches** [piitaya/lovelace-mushroom#635]
### Is your feature request related to a problem?

My thermostat support only degrees selection with no decimal.
Using the temperature selctor of the climate card, I have to click 10 times on - or + to change one degree.

### Describe the solution you'd like

It would be great to have an option ( a boolean checkbox) to skip decimals in temperature selector.

**Comment by piitaya** [comment]
Can you provide your entity state?

**Comment by jncanches** [comment]
Ok my bad, it is a known problem from KNX Climate described [here](https://github.com/home-assistant/core/issues/32180).
With the workaround, the UI works flawlessly.
