### ISSUE TITLE
Different Card for Thermostats

### ISSUE THREAD

**Issue by Jmjm80** [piitaya/lovelace-mushroom#637]
### Current Behavior

I have 2 thermostats with different cards, why is that?

The first one is a ZWave Thermostat.
The second one is a Tuya Thermostat.
The third one is a Sensibo Thermostat.

The issue is apparently only affecting the Z-Wave thermostat.

![image](https://user-images.githubusercontent.com/65945284/180085008-d1a112e4-7fd3-4a6a-a5bb-4e22b1243170.png)

### Expected Behavior

Same Card for all Thermostats.

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by piitaya** [comment]
Looks like your first thermostat don't support temperature control

**Comment by Jmjm80** [comment]
It does support temperature control. See pictures below.

First pictures shows when I turn the AC ON. The second one, when I select temperature control.

![85F46AA4-EA15-4C08-B352-C8C2C6409338](https://user-images.githubusercontent.com/65945284/180096622-55ccb1fe-6da8-49d2-8b24-d6e47012e340.png)

![61BEE20E-768F-4A88-8CEE-0C1BE1821C37](https://user-images.githubusercontent.com/65945284/180096635-aa443241-01c1-45c3-b8fa-1d6baa720464.png)

**Comment by piitaya** [comment]
So what's the problem? Your screenshot looks good.

**Comment by Jmjm80** [comment]
I just imagine that is a bug that this happen:

When all thermostats are off, why the Z-Wave is different from the others? Is more about having a uniform look. The functionality is OK.

**Comment by Jmjm80** [comment]
I find that the Z-Wave look is better when off, because it hides the temperature control and shows it as soon as I turn it ON.

**Comment by piitaya** [comment]
Can you provide the complete state of your entity when cool and when off ? 🙂 Looks like the supported features change when you turn on the climate.

**Comment by Jmjm80** [comment]
Do you mean this?

![image](https://user-images.githubusercontent.com/65945284/180102314-9fcb19a9-9e47-4d44-bf39-605303efbb66.jpg)

**Comment by piitaya** [comment]
Yes and when you turn on the entity?

**Comment by Jmjm80** [comment]
Is pretty much the same.

Just the card changes as I show you above.

![image](https://user-images.githubusercontent.com/65945284/180298796-805a65fe-07d5-420f-b604-a63eca6b412d.jpg)

**Comment by piitaya** [comment]
`temperature` is `null` when state is off for your zwave integration. That why the input number is not displayed for this thermostat when off.

**Comment by Jmjm80** [comment]
Oh i get it, thanks man. Well, a recommendation would be to first show the HVAC modes, because thats where you turn on the AC.

Thanks again for the great communication.

**Comment by piitaya** [comment]
There is already an issue about default control https://github.com/piitaya/lovelace-mushroom/issues/640 🙂 It should be good to allow user to choose it for light, media_player, climate, etc...

**Comment by niekniek89** [comment]
> It does support temperature control. See pictures below.
> 
> First pictures shows when I turn the AC ON. The second one, when I select temperature control.
> 
> ![85F46AA4-EA15-4C08-B352-C8C2C6409338](https://user-images.githubusercontent.com/65945284/180096622-55ccb1fe-6da8-49d2-8b24-d6e47012e340.png)
> 
> ![61BEE20E-768F-4A88-8CEE-0C1BE1821C37](https://user-images.githubusercontent.com/65945284/180096635-aa443241-01c1-45c3-b8fa-1d6baa720464.png)

I have been looking for this for a long time (air conditioner options).
can you share your code for this?
