### ISSUE TITLE
[Bug]: compatible con "Home Assistant Core version 2022.7.5"

### ISSUE THREAD

**Issue by Vicente-Ch** [piitaya/lovelace-mushroom#641]
### Current Behavior

Hello, is it compatible with the new version of HA?
"Home Assistant Core
installed version
2022.7.5"
The cards don't come out pretty, they're too dark

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by piitaya** [comment]
Yes it's compatible. It's certainly an issue with your theme.
