### ISSUE TITLE
[Feature]: Option to change Default mode colors -fan_only color (blue-grey) is too similar to disabled color (disabled)

### ISSUE THREAD

**Issue by Majumafoo** [piitaya/lovelace-mushroom#642]
### Is your feature request related to a problem?

Below is an image of 2 climate cards where one entity is off, and the other is using fan only.
At a glance, especially if there are several entities on one card, these are difficult to distringuish, and I think a different colour for fan_only would make sense.

![image](https://user-images.githubusercontent.com/45857221/180289721-b29b2486-28f9-448b-b86a-6abbd0782e7b.png)

### Describe the solution you'd like

I can think of two reasonable solutions:
1.  Change the default color to something more visually different.
2. Offer users the option to select their own colours for each mode.

### Describe alternatives you've considered

- Perhaps I've selected a theme that just happens to be a poor combination with this card.
- I'm at least a little colourblind, so that could be contributing to my difficulty

### Additional context

These cards are so great and I love the work you've been doing.
Thank you for making something awesome.

**Comment by piitaya** [comment]
Yep fan-only color can be changed 🙂
It's already possible de change the colors using themes : https://github.com/piitaya/lovelace-mushroom-themes#build-your-own.
But I agree with you, default color can be better 🙂 What color do you suggest ? Purple ? Yellow ? Teal ?

**Comment by Majumafoo** [comment]
> It's already possible de change the colors using themes : https://github.com/piitaya/lovelace-mushroom-themes#build-your-own.

I wasn't aware of this. Very cool.
The idea of creating my own palette to have available globally is awesome.

> default color can be better 🙂 What color do you suggest ? Purple ? Yellow ? Teal ?

By making adjustments to the fan_only colour, it felt necessary to adjust the others to keep them all different, so I've gone a bit beyond to scope of the original question.
My objectively correct (jokes) colour choices would be:
- heat_cool -**Purple** (mixing hot and cold makes purple. Green feels strange, though seems to be widely used)
- cool 	  -**Blue**
- heat 	  -**Deep-Orange** (Red feels like too much here, so I like this decision)
- dry 	  -**Lime** (the current Orange feel too similar to deep-orange)
- fan 	  -**Teal**

**Comment by piitaya** [comment]
All the colors are HA climate colors to avoid confusion with other card. But I agree for the fan color. I will update it to teal by default.
