### ISSUE TITLE
Climate card tap_action call-service error

### ISSUE THREAD

**Issue by superwangmeng** [piitaya/lovelace-mushroom#657]
### Current Behavior

in the HA develop tools ,call-service  works well:

service: climate.set_hvac_mode
data: >
    {% if is_state('climate.zhonghong_ciwo', 'off') %}
         {"hvac_mode": "cool"}
    {% else %}
        {"hvac_mode": "off"}
    {% endif %}
target:
  entity_id: climate.zhonghong_ciwo

but,in the card yaml, error, the yaml below：

  - type: custom:mushroom-climate-card
     entity: climate.zhonghong_ciwo
     hvac_modes:
         - 'off'
         - cool
         - heat
     show_temperature_control: true
     fill_container: true
     collapsible_controls: true
     tap_action:
        action: call-service
        service: climate.set_hvac_mode
        data: >-
            {% if is_state('climate.zhonghong_ciwo', 'off') %}
                {"hvac_mode": "cool"}
            {% else %}
                {"hvac_mode": "off"}
            {% endif %}
         target:
         entity_id: climate.zhonghong_ciwo

The issue log：

调用服务(call-service) climate/set_hvac_mode 失败(failed)。 expected dict for dictionary value @ data['service_data']. Got '{% if is_state(\'climate.zhonghong_ciwo\', \'off\') %}\n {"hvac_mode": "cool"}\n{% else %}\n {"hvac_mode": "off"}\n{% endif %}\n'

### Environment

```markdown
- OS: ds218+ docker
- Node:
- Version: 20220707.0 - latest
- Hassio:
```

**Comment by piitaya** [comment]
Hi 🙂
Templates are not supported for tap action for cards. You can write a script and call it from your tap action 🙂

**Comment by superwangmeng** [comment]
ok,thanks for your suggestion.
