### ISSUE TITLE
[Feature]: Colorization of dual control Climate temperature

### ISSUE THREAD

**Issue by ulic75** [piitaya/lovelace-mushroom#662]
### Is your feature request related to a problem?

No, just brings a little visual clarity to what is being adjusted by applying color using the --rgb-state-climate-heat/cool css variables.

### Describe the solution you'd like

Three possible solutions, text only, buttons only, both buttons and text.
![Text Only](https://user-images.githubusercontent.com/5641964/181037613-9cf2c61c-6275-49a3-bac7-bd181152cb62.png)
![Buttons Only](https://user-images.githubusercontent.com/5641964/181037683-ece55ab9-d0fe-49e5-9111-d2a5e176b4a5.png)
![Buttons and Text](https://user-images.githubusercontent.com/5641964/181037543-566fc481-3b11-4a80-a23e-6aa165d22f52.png)

### Additional context

I'd be happy to submit a PR, but wanted to open it up for some feedback first.

**Comment by ulic75** [comment]
I think my personal preference would be for text only or buttons and text.

**Comment by ulic75** [comment]
Here is a 4th option that I'm quite fond off with a tinted background.

![All and BG](https://user-images.githubusercontent.com/5641964/181097655-a87c2843-fc4f-41bb-bb01-f02a9217e237.png)

**Comment by piitaya** [comment]
I think I prefer to last one. It strange to mix the text/icon color and the grey background.
How does it looks in dark mode ?

**Comment by ulic75** [comment]
Obviously all theming depends on color choices (and I forgot I had changed the heat state from dark-orange to orange as that's my preference).  Below are HA & Mushroom default colors in dark and light.

![Screen Shot 2022-07-26 at 5 06 43 PM](https://user-images.githubusercontent.com/5641964/181127394-2dd5e759-2803-47d6-8533-813cf50e3b6f.png)

![Screen Shot 2022-07-26 at 5 06 58 PM](https://user-images.githubusercontent.com/5641964/181127395-fd061860-9559-43a0-a119-093781f60765.png)

**Comment by ulic75** [comment]
Any feels on giving the same treatment to single control mode based on mode?
