### ISSUE TITLE
[Bug]: Can't find Cliamte card in Lovelace editor.

### ISSUE THREAD

**Issue by firstdominator** [piitaya/lovelace-mushroom#666]
### Current Behavior

Can't find climate card in the Lovelace editor.

### Expected Behavior

Climate card shows-up in the lovelace editor

### Steps To Reproduce

1. edit dashboard
2. search climate card, not there.

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

### Anything else?

Yes I did server restart, and even a host restart. I,ve had this issue for now 2 weeks jsut didn't had the time to write here.
![image](https://user-images.githubusercontent.com/166283/181625863-ee101bb4-8e06-4fa5-9440-b137606aebdc.png)

Thanks!

**Comment by piitaya** [comment]
Please look at other issues. There is other issues like this and the solution de fix it.
