### ISSUE TITLE
[Bug]: Dashboard Resource Path incorrect - no Mushroom cards available

### ISSUE THREAD

**Issue by bflick81** [piitaya/lovelace-mushroom#671]
### Current Behavior

Just installed Mushroom on fairly new Hassio setup.  Could not add Mushroom cards to dashboard - no cards found.

### Expected Behavior

Expected Mushroom cards to be available under Dashboard > Edit > Add Card.

### Steps To Reproduce

1. Hassio 2022.7.7 with Mushroom 2.1.3 and Mushroom Themes 0.0.2.  Mushroom and Mushroom themes installed via HACS frontend repositories.
2. Reloaded browser, restarted Hassio.  No change.
3. Create new dashboard, edit, add card.
4. Mushroom cards not found.

### Environment

```markdown
- OS: HAOSS 8.4
- Version: HACS 1.26.2, Mushroom 2.1.3
- Hassio: 2022.7.7
```

### Anything else?

Checked Settings > Dashboards > Resources.

Path inserted by installation is /hacsfiles/lovelace-mushroom/mushroom.js

Correct installation path is /local/community/lovelace-mushroom/mushroom.js

Adding the correct installation path resolves the bug.  Once correct path is in place, Mushroom cards became available.

**Comment by piitaya** [comment]
The path is not inserted by Mushroom but by HACS, we can not change it.
Otherwise, it works for me with `/hacsfiles/lovelace-mushroom/mushroom.js`

**Comment by bflick81** [comment]
Sure enough that is the path that was originally in place.  It did not work at first, even after a restart of Hassio.  After seeing your comment, I tried again to access this path and it is now working.

Looks like there was something within HACS that needed to run through its routine before the resource became available.  I'll mark this as closed!
