### ISSUE TITLE
[Feature]: Add name to Action button

### ISSUE THREAD

**Issue by woempiej** [piitaya/lovelace-mushroom#672]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Add a name to a "action" button

![afbeelding](https://user-images.githubusercontent.com/62903344/182043654-d11db638-5c7d-40db-8cb8-901be0595d39.png)

### Describe alternatives you've considered

Make boolean for all the action buttons

**Comment by piitaya** [comment]
You can use template chip for that 😊

**Comment by woempiej** [comment]
Too many great options! I looked over it.
Thanks for the tip and reply.
