### ISSUE TITLE
[Bug]: cards not showing in lovelace

### ISSUE THREAD

**Issue by dongilles** [piitaya/lovelace-mushroom#677]
### Current Behavior

I have installed Mushroom but the cards are not comming up when edditing the dashboard

### Expected Behavior

Cards showing

### Steps To Reproduce

I just installed it from HACS

### Environment

```markdown
- OS: Home assistant OS
- Node: iphone app
- Version: ?
- Hassio: 2022.7.7
```

### Anything else?

I have tried:
Restart of the system multible times
Installed Mushroom themes
Changed themes
Made a new dashboard

**Comment by piitaya** [comment]
Please look at other issues. It's always a cache or a ressources issue.

**Comment by dongilles** [comment]
Sorry, you are correct! restarted the app itself and it works.

**Comment by hearttheart** [comment]
Sorry, I can't get it to work. What I've tried:

- Multiple reinstalls via HACS, with restarts in between
- Opening/closing iOS app
- Hard reload via Developer Tools
- Manual install with restarts

A few cards show up, but that's it. Kind of stuck here, would appreciate some input.

Home Assistant 2022.9.6

**Comment by piitaya** [comment]
Did you clean your resources ?

**Comment by hearttheart** [comment]
Don't know what I did, but it's working now. Sorry for the hassle.
