### ISSUE TITLE
[Feature]: Preset modes in Climate card

### ISSUE THREAD

**Issue by alphasixtyfive** [piitaya/lovelace-mushroom#679]
Would it be possible to add support for preset modes to climate card? I have KNX thermostats and instead of `hvac_modes` it uses `preset_modes`.

![Screenshot 2022-08-03 at 13 48 04](https://user-images.githubusercontent.com/55880648/182601489-f3d7c291-f20c-40f8-822d-a51e15b6e359.png)
![Screenshot 2022-08-03 at 13 48 38](https://user-images.githubusercontent.com/55880648/182601500-2e675a8a-783c-4cf6-b05d-650894b40f8a.png)
 

### Describe the solution you'd like

In order to save space on the card, perhaps there could be a switch allowing user to either use have or preset modes.

**Comment by piitaya** [comment]
Duplicate #615
