### ISSUE TITLE
No mushroom.js in downloaded repo

### ISSUE THREAD

**Issue by randomhammer** [piitaya/lovelace-mushroom#687]
### Current Behavior

I am trying to use the manual installation method, which says I should download `mushroom.js` from the latest version and store in `config/www`. I cloned the repo, and there is no `mushroom.js` anywhere in the files I downloaded. There is a `mushroom.ts` but no `mushroom.js`.

I'm sure I am missing something obvious, but I don't know what it is. 

### Expected Behavior

I expect there to be a file named `mushroom.js` somewhere

### Steps To Reproduce

Clone repository

```sh
hass$ git clone https://github.com/piitaya/lovelace-mushroom.git
hass$ find . -type f -name 'mushroom.*'
./src/mushroom.ts
```

There is no `mushroom.js`

### Environment

```markdown
- OS: Debian Bullseye
- Node: 
- Version:
- Hassio: core-2022.8.2
```

**Comment by piitaya** [comment]
Hi 🙂
You should download the `mushroom.js` file in the [release page](https://github.com/piitaya/lovelace-mushroom/releases)

**Comment by randomhammer** [comment]
Ah, thanks! I think there was supposed to be a link on the install page but it did not work.
