### ISSUE TITLE
📝 Input card

### ISSUE THREAD

**Issue by lacalamine64** [piitaya/lovelace-mushroom#688]
### Is your feature request related to a problem?

No, not really.

### Describe the solution you'd like

A card to edit helpers like input_number., input_datetime. etc.

### Describe alternatives you've considered

For now I use the standard Entities Card, but that doesn't fit into the design of mushroom.

### Additional context

I have a dashboard where users can edit some of those helpers that are used as variables within automations.

**Comment by freeDom-** [comment]
An input-time component would be awesome!

**Comment by lacalamine64** [comment]
> An input-time component would be awesome!

It's available since v2.6.0 as number card.

**Comment by freeDom-** [comment]
The number card can only be used to set input_number, but there is no component to set input_datetime...

**Comment by piitaya** [comment]
For `input_datetime`, a date picker should be developed. Unfortunately, date picker are complex and it takes a lot of time to have a good UX. Also, `input_datetime` includes date, time and date-time support.

It's a lot of work compared to other domains so it's not a priority for now.
