### ISSUE TITLE
Chips Icon Color

### ISSUE THREAD

**Issue by rfnovo** [piitaya/lovelace-mushroom#69]
This is more a feature request. I'd like to be able to change icon color based on state on Chips card:
chips:
  - type: entity
    entity: group.teste11
    icon: mdi:lightbulb-group
    tap_action:
      action: toggle
    icon_color: |
      if (state === 'off') return 'rgb(0, 255, 0');

**Comment by piitaya** [comment]
I think I can be a good idea to have the same behaviour on entity chip and entity card : only colored icon when entity is considered on (on, open, playing, etc...)
@pierrecle ?

**Comment by pierrecle** [comment]
Yes, absolutely.
