### ISSUE TITLE
Display status different icons

### ISSUE THREAD

**Issue by Nesterovich2797** [piitaya/lovelace-mushroom#70]
Can add a change of icons and color for different statuses? For example, 
- the door is open (icon mdi:door-open; red color)
- the door is closed (icon mdi:door; green color)

**Comment by piitaya** [comment]
The rules for entity card are : 
- colored when active (open)
- grey when inactive (closed)

If you want custom rules. You can use the template card and define your own rules with template 🙂

**Comment by KameDomotics** [comment]
> The rules for entity card are :
> 
> * colored when active (open)
> * grey when inactive (closed)
> 
> If you want custom rules. You can use the template card and define your own rules with template 🙂

Could you give me an example of a template with icons that change according to the state?
Thanks
