### ISSUE TITLE
Templating in Media Car

### ISSUE THREAD

**Issue by posreg** [piitaya/lovelace-mushroom#700]
### Is your feature request related to a problem?

not being able to use templates withing Media Card secondary_info and primary_info

ie. based on my  input.select I would like to the show what station is currently being played as secondary_info

Templates works very well in Dev Tools, cannot be applied in the card itself

`  {%- if states('input_select.mediaplayer_source') == 'RMF' -%}
    RMF FM
  {%- elif  states('input_select.mediaplayer_source') == 'RMF MAXXX' -%} 
    RMF MAXXX
  {%- elif  states('input_select.mediaplayer_source') == 'VOX' -%} 
    VOX
  {%- elif  states('input_select.mediaplayer_source') == 'Supernova' -%} 
    Supernova
  {%- elif  states('input_select.mediaplayer_source') == 'ESKA' -%} 
    ESKA
  {%- elif  states('input_select.mediaplayer_source') == 'MUZO' -%} 
    MUZO
  {%- elif  states('input_select.mediaplayer_source') == 'RADIO ZET' -%} 
    Radio Zet
  {%- elif  states('input_select.mediaplayer_source') == 'Radio Krakow' -%}
    Radio Krakow
  {%- endif -%}`

### Describe the solution you'd like

Similarly to the Template card, ability to use templates within primary_info and secondary_info

Forgive me this statement, but I believe and hope it is easy as it works for other cards.

### Describe alternatives you've considered

As a work around I have a Chips presenting what is playing-  it is positioned with card_mod which is not the most efficent way.
![image](https://user-images.githubusercontent.com/80816020/186664009-7ddc906e-7d62-4751-a031-b95e9f0eb1e0.png)

**Comment by posreg** [comment]
Don't bother, I will use Template Card - I've realized about this when I was finishing this post..

**Comment by posreg** [comment]
Closed

**Comment by sagilo** [comment]
@posreg I did you duplicate the media player buttons into a template card?
