### ISSUE TITLE
[Bug]: Cards not available

### ISSUE THREAD

**Issue by DK-MGO** [piitaya/lovelace-mushroom#702]
### Current Behavior

Hi,

Kinda new to Home Assistant and love the look of these cards to make a dashboard which even I can figure out ;o)

However, once I have added Mushroom through HACS I do not see the cards when designing a dashboard. I have tried to reload, refreash, restart HA, restart server with no luck. I have also added a resource entry as describe using the UI.

Please advice.

Thank you!

### Environment

```markdown
Raspberry Pi 4
Home Assistant 2022.8.7
Supervisor 2022.08.3
Operating System 8.5
Frontend 20220802.0 - latest
```

**Comment by piitaya** [comment]
You can try remove all the mushroom ressources, uninstall mushroom from HACS et re-install mushroom.

**Comment by Shin2D** [comment]
Same problem, reinstalling didn't work
