### ISSUE TITLE
[Bug]: Cover Card doesn't work on grouped Covers

### ISSUE THREAD

**Issue by geeForceOne** [piitaya/lovelace-mushroom#708]
### Current Behavior

I created a Group, and added 4 Covers into it, then used the group  as an entity for the Cover Card. The Controls (up, down, etc) are then just working on one Cover instead of the group.

### Expected Behavior

All Covers in the Group should be controllable.

### Steps To Reproduce

- Create a Group and add 2 or more Covers
- use the group entity in the Mushroom Cover Card
- play around with the controls

### Environment

```markdown
Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0
```

**Comment by piitaya** [comment]
How do you define your group? Using the UI? With yaml config ? 

I use mushroom with my cover group and I never had issue.
Mushroom just don't support the [old style groups](https://www.home-assistant.io/integrations/group/#old-style-groups).

**Comment by geeForceOne** [comment]
I used the UI to do the grouping. I don't know what was wrong yesterday, but today it worked as expected.
