### ISSUE TITLE
Show entity name in chips entity and color the icon if the state is on , playing....

### ISSUE THREAD

**Issue by Nemesis24** [piitaya/lovelace-mushroom#71]
Show entity name in chips entity and color the icon if the state is on , playing.... I think it would be fine !!
Thanks for this good job.

**Comment by Roflcopterer** [comment]
You can do this by using the "Template" chip, here is an example:

icon color:
{% set robot = states('vacuum.robot') %}{% if robot == 'cleaning' %}amber{% else %}grey{% endif %}

**Comment by Nemesis24** [comment]
ok thanks this is a way but it would be fine directly.

**Comment by Roflcopterer** [comment]
I think the plan is to keep Mushroom basic and easy to work with. The template options are for users that want to customize and spend a little more time on the cards. This gives you way more control, you can specify colors, icons and titles  for all the entity state.

**Comment by Nemesis24** [comment]
![Sans titre](https://user-images.githubusercontent.com/25956796/153161663-87fc64de-5556-458c-9922-d6ecc82b0011.png)
Ok an example for me it's not "easy" in this case to know what switch it is. So the name in place off on or off state will be more friendly, and showing the state with colour will be more Chips I think.

**Comment by piitaya** [comment]
I think we can have the same options than entity card :
- content : `state` | `name` | `none`
- colored icon based on entity state
- possibility to customize name
