### ISSUE TITLE
Card title for chips

### ISSUE THREAD

**Issue by Nemesis24** [piitaya/lovelace-mushroom#72]
I think it would be fine to give the possibility to define a title for a card Chips.
Thanks for this good job.

**Comment by Roflcopterer** [comment]
I'm not sure what you want to build, are you trying to place a title (like the Title card) above your Chips or use a title next to a chip icon?

**Comment by Nemesis24** [comment]
Yes like the title card above the Chips.

**Comment by Roflcopterer** [comment]
In that case I would just use a separate Title card, gives you more options to customize and less clutter in other existing cards

**Comment by Nemesis24** [comment]
Yes but this way you've got a big card... for me Chips is the way to have minimalist things.
It could be optional.

**Comment by pierrecle** [comment]
Agree with @Roflcopterer, what would be the difference between a title of the chips card vs a title card above a chips card?
The title card hasn't "card" style. Could you draft something with paint/preview that shows what you can do with the title card + chips card vs what you want?

**Comment by Nemesis24** [comment]
![Sans titre](https://user-images.githubusercontent.com/25956796/153172278-102b8a77-25c3-419c-b730-57fffbf69a83.png)
![Sans titre 2](https://user-images.githubusercontent.com/25956796/153172293-87ccf30b-18ea-41f7-bb01-5d291f0328eb.png)

**Comment by pierrecle** [comment]
Thanks, as said before, the title should be handled using title card.
For the entity name in the chip, it's not in my opinion, the aim of chips, what do you think @piitaya ?
I was wondering if we should create an entities card, and what would be the differences with the HASS one.

**Comment by piitaya** [comment]
I already answer on another issue #71 

I think we can have the same options than entity card :
- content : state | name | none
- colored icon based on entity state
- possibility to customize name
- possibility to customize icon (already possible)

I think chip must stay like this : icon + content

**Comment by piitaya** [comment]
@Nemesis24 Just use title card for this : https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/title.md
