### ISSUE TITLE
Remove alarm panel group

### ISSUE THREAD

**Issue by pierrecle** [piitaya/lovelace-mushroom#75]
Alarm group should be handled using alarm template. To handle when panels have different state and display it in the card, we should handle partial states: `partially_armed`, `partially_disarmed` etc.

**Comment by piitaya** [comment]
I think we can add a list : "warning_states" to allow custom to add custom warning states (because `partially` states are not official)

**Comment by pierrecle** [comment]
Problem `value_template` can only return one of those states: `armed_away`, `armed_home`, `armed_night`, `arming`, `disarmed`, `pending`, `triggered` and `unavailable` [(the doc)](https://www.home-assistant.io/integrations/alarm_control_panel.template/#value_template).

Every other state such as `partially_armed` will set state to `unknown`. And there is no way to add custom attributes to the entity. I'm stuck for now.

**Comment by pierrecle** [comment]
Another way to do it, and I think that's the best, is to allow user to add alarm panels in a list in the panels configuration and use this list to check if all panels have the same state. This is way cleaner, it won't use any unofficial state or any other tweak.

What do you think about this solution @piitaya ?

**Comment by piitaya** [comment]
Do you have any desync issue with alarm templates ? May be you can just add a badge or a chip to show that there is a problem ?
