### ISSUE TITLE
[Feature]: Allow templates on the color of chips

### ISSUE THREAD

**Issue by lapo-gh** [piitaya/lovelace-mushroom#752]
### Is your feature request related to a problem?

It would be nice to have the ability to have chip icon colored in various colors based on the value of the chip.
For instance if the temperature on a sensor drops below 4 degrees Celsius, then the icon will be blue - otherwise, red.
    icon_color: >-
      {% if states('sensor.house_corner_motion_sensor_temperature') | int >= 4
      %} red {% elif states('sensor.house_corner_motion_sensor_temperature') |
      int < 4 %} red {% endif %}

### Describe the solution you'd like

Accept templates as input

**Comment by Mask3007** [comment]
You can use a chip of Kind template. I used it several times.

E. G. Having the Updates icon Green when everything is up to date

![IMG_20221006_081340.jpg](https://user-images.githubusercontent.com/31553023/194227951-5142c683-8929-4b57-a7de-3dd7868391f8.jpg)

**Comment by piitaya** [comment]
It's possible with the template chip.
