### ISSUE TITLE
[Feature]: Climate Card add Pre-Set Mode

### ISSUE THREAD

**Issue by DaveTiff** [piitaya/lovelace-mushroom#753]
### Is your feature request related to a problem?

Don't know pre-set mode

### Describe the solution you'd like

If the house is un-occupied I want to set my thermostats to away mode Pre-set = away or none

I would like to be able to Show "Away" on the card

**Comment by piitaya** [comment]
Duplicate https://github.com/piitaya/lovelace-mushroom/issues/615
