### ISSUE TITLE
[Bug]: Unable to install via HACS

### ISSUE THREAD

**Issue by malaki86** [piitaya/lovelace-mushroom#760]
### Current Behavior

I installed HACS and it appears that it's working fine because I have installed other HACS items.

When I select Download for Mushroom, however, all I get is the running spinner in the bottom right. I let it go for 30 minutes or so before it timed out (I guess) and just showed the same Mushroom download information. There are no log entries for anything related to the download failing.

I can manually install it if you can point me to the correct URL.

### Expected Behavior

I expected it to download and install. 

### Steps To Reproduce

Open HACS
Select "Front ends"
Hit "+"
Find "Mushroom"
Click the download icon
Click "Download"

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by piitaya** [comment]
Looks like a have issue with your installation. Custom cards don't control the way they are installed.
