### ISSUE TITLE
[Bug]: Version not available under update card

### ISSUE THREAD

**Issue by pbathuk** [piitaya/lovelace-mushroom#763]
### Current Behavior

When I try to use the mushroom update card it does not allow me to select the binary sensor for the `binary_sensor.docker_hub_update_available` 
This is based of the inbuilt Version Integration : https://www.home-assistant.io/integrations/version/#:~:text=From%20the%20configuration%20menu%20select,to%20complete%20the%20set%20up.

### Expected Behavior

Home assistant version to appear

### Steps To Reproduce

Within home assistant (docker)
On latest mushroom via hacs (v2.1.3)
Have Version Integration setup on docker

### Environment

```markdown
- OS: Ubuntu 22.04 lts
- Node: docker
- Version: 2.1.3
- Hassio: no - via HACS
```

**Comment by piitaya** [comment]
The update card is for update entity. Your entity is a binary sensor. You should use entity card.

**Comment by pbathuk** [comment]
Oh, brilliant.. sorry I had missed that.. could have sworn I looked at the ones it was seeing and they were binary sensors as well.

Thanks.
