### ISSUE TITLE
Lock Card not picking up status on locks after auto lock feature engages

### ISSUE THREAD

**Issue by thorrrr** [piitaya/lovelace-mushroom#775]
### Current Behavior

Mushroom lockcard looks great but it is not picking up the status when my lock auto locks?
Is shows unlocked all the time unless i manually set it back to locked?

### Expected Behavior

I would expect when i hit unlock it unlocks and show unlocked and when the lock autolocks itself after it shows locked again

### Environment

```markdown
Home Assistant 2022.10.4
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest
```

**Comment by piitaya** [comment]
What's the state of your entity when the lock auto-lock?

**Comment by thorrrr** [comment]
Hi it turns out it is a zwave issue
