### ISSUE TITLE
[Bug]: Dashboard resource URL is set incorrectly during HACS installation

### ISSUE THREAD

**Issue by thomaszlow** [piitaya/lovelace-mushroom#776]
### Current Behavior

After adding the repository via HACS > Frontend the dashboard resource **URL** is set incorrectly to:

`/hacsfiles/lovelace-mushroom/mushroom.js?hacstag=444350375213`

As a result the mushroom cards are not available in the dashboard.

### Expected Behavior

After adding the repository via HACS > Frontend the dashboard resource **URL** is automatically set to:

`/local/community/lovelace-mushroom/mushroom.js`

The mushroom cards are available in the dashboard to be added.

### Steps To Reproduce

1. Go to HACS
2. Go to Frontend
3. Search and add repository
4. Go to Settings > Dashboard
5. Open the resources

### Environment

```markdown
- OS: VM, Home Assistant Operating System 9.2
- HACS: 1.28.2
- Hassio: 2022.10.4
```

### Anything else?

Deleting the resource entry `/hacsfiles/lovelace-mushroom/mushroom.js?hacstag=444350375213` leads to the following error message.

![Bildschirmfoto 2022-10-18 um 17 45 03](https://user-images.githubusercontent.com/79666256/196479297-b9a4f02a-4713-4bf1-8436-fe18a63dc70c.png)

**Comment by piitaya** [comment]
Hello,
It's the normal behavior. Custom cards have no control over it. You can find more info here : https://hacs.xyz/docs/categories/plugins/
