### ISSUE TITLE
[Feature]: <title>

### ISSUE THREAD

**Issue by BristolBEAT** [piitaya/lovelace-mushroom#778]
### Is your feature request related to a problem?

Switches are set in the top summary banner alongside people.

### Describe the solution you'd like

How do you remover the switches in the top summary panel?

![Screenshot 2022-10-20 at 11 47 41](https://user-images.githubusercontent.com/109667579/196928719-0aa58160-c309-4a41-b8c0-834cf8b267c2.png)

**Comment by piitaya** [comment]
What's the issue ? How are you using mushroom card to get this ?

**Comment by BristolBEAT** [comment]
This is using Dwains Dashboards. I think that's just how it is.

**Comment by piitaya** [comment]
I think you should close the issue and look at Dwains Dashboards community/issues for this.
