### ISSUE TITLE
[Bug]: <title> Show Code Editor disappears

### ISSUE THREAD

**Issue by BristolBEAT** [piitaya/lovelace-mushroom#779]
### Current Behavior

When I type in YAML to create a media player from blank card, the card generates correctly. But when I go back to amend the YAML code the option isn't there?

![Screenshot 2022-10-20 at 12 00 38](https://user-images.githubusercontent.com/109667579/196931387-d0fd6112-cfc2-4bb2-9758-c0b4ef39c8e0.png)

### Environment

```markdown
- OS: Mac OS
- Node: Chrome
- Version: 
- Hassio: 2022.10.0
```

**Comment by piitaya** [comment]
Your screenshot is not the mushroom editor.

**Comment by piitaya** [comment]
It depends what you want. You use another custom card on your screenshot, not mushroom one. This GitHub repository is only for Mushroom cards.

**Comment by BristolBEAT** [comment]
My gripe is you can use a non-mushroom card, edit the code first time around but once the card is created in Dwain's Dashboard you can't amend code after.

**Comment by piitaya** [comment]
I close it as it's not a mushroom issue but a dwain dashboard question/issue.
