### ISSUE TITLE
[Feature]: show keypad only for disarming in alarm card

### ISSUE THREAD

**Issue by rogelio-o** [piitaya/lovelace-mushroom#787]
### Is your feature request related to a problem?

My alarm only requires the code for disarming.

### Describe the solution you'd like

Provide a configuration property to show the keypad in the alarm card only for disarming.

**Comment by jmcollin78** [comment]
I would prefer that keypad displays only if needed to keep the component small. When we click the main button (top left), there is popup that opens with a keypad. It should be possible to do the same for buttons (arm / disarm).
