### ISSUE TITLE
Hide entire Chip on specific state

### ISSUE THREAD

**Issue by Roflcopterer** [piitaya/lovelace-mushroom#79]
It would be nice to have an option to hide/show entire chips depending on an entity state.

Example:
I'm using a Chip for the dishwasher, when idle the icon is grey and there is no text, when washing the icon is blue and there is a text showing the progress percentage.
It would be useful to hide the Chip when idle and only show up when washing. 

This way Chips will become more of a status bar showing current active parts of your system. 

The config could be like:
"show/hide" when "trigger-entity" state "is/isnot" equal to "condition-state"

**Comment by piitaya** [comment]
I think we should create a conditional chip for that like the [conditional card](https://www.home-assistant.io/lovelace/conditional/).

**Comment by Roflcopterer** [comment]
Great, this could be useful for many things (counting people, lights etc, showing active machines and media etc)

**Comment by piitaya** [comment]
Thank's @vhartmann for the example ! 🙂
Maybe there are already custom cards that do this, so we don't need to add this in mushroom.
