### ISSUE TITLE
State named Unknown for Cover Card

### ISSUE THREAD

**Issue by cataseven** [piitaya/lovelace-mushroom#794]
### Current Behavior

If the cover is partially open state is shown as Unknown xx%. Actually it is open xx%. Is it possible to change expression "unknown" to "open" for Cover card?

### Expected Behavior

Shown partially open cover as Open

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by piitaya** [comment]
Hello? What's are entity state and attributes ? I think your entity has an unknown state.

**Comment by cataseven** [comment]
Good Morning,

Yes It has "unknown" as state, but I am asking for if there is a way to override the state unknown. I don't want to use Template Card. Is that possible, on user side, within Cover Card? Or Can you override it on the code side for Cover Card? I think nobody wants to see unknown so can you add something like; if cover card and if the state is unknown show it as Open?

**Comment by piitaya** [comment]
What integration do you use ? The fix for that should be at the integration level, not on dashboard side. 
There is nothing we can do in mushroom because, if we do this, people with covers with real unknown state will have open and will not see the issue.

**Comment by cataseven** [comment]
Hi,

I am using Local Tuya

**Comment by piitaya** [comment]
The unknown state must be fixed inside local tuya.

**Comment by cataseven** [comment]
Thank you. I think I find the solution after your help. For those who need this, just change lines 111 and 117 in Cover.py file of Local Tuya Integration to "False". 

Please see the screenshot. I wiil also open topic in Local Tuya Integration page.

![2022-10-29 23_25_40-Studio Code Server – Home Assistant](https://user-images.githubusercontent.com/52464808/198851244-12b9268a-46b7-4815-8e29-d19b2bd01abe.png)

Thanks Piitaya. Closed!
