### ISSUE TITLE
[Question]: Chips border

### ISSUE THREAD

**Issue by pedolsky** [piitaya/lovelace-mushroom#795]
### Current Behavior

Since core-2022.11.0b0, chips are displayed with a container border, regardless of whether a theme is selected or not.

Using `ha-card-border-color: rgba(0,0,0,0)` in a theme does the job, but after `chip-box-shadow:` was removed as a theme variable, there seems to be only either-or. Before, I could use the theme variable to show the chips without border, while the other cards were shown with border.

![A9A41E90-E56D-455E-ABAC-68988D229A8D](https://user-images.githubusercontent.com/71203830/198207814-d9ef12b9-414b-40ca-8501-9f2d11c74415.jpeg)

![8481B997-F24E-44F1-8846-95A6F657DA9B](https://user-images.githubusercontent.com/71203830/198207859-dac330eb-985d-4a8c-937d-d1a216983059.jpeg)

### Expected Behavior

At least a correctly displayed container.

Optional: Bring back border control for chips 

### Environment

```markdown
- OS: iPadOS 16.1
- Browser: Chrome, Safari
- Version Mushroom: i2.2.0
- Hassio: 2022.11.0b0 Supervised on Debian Bullseye
```

**Comment by piitaya** [comment]
Hello 🙂
Are you running the last Mushroom version?
![image](https://user-images.githubusercontent.com/5878303/198216658-246fd5bf-c967-4514-8099-469e9d6a05c3.png)
And you have a custom theme. Can you share it ? 🙂

**Comment by tobpet** [comment]
Same issue for me when update Mushroom to 2.2.0. Downgrade to 2.1.3 solved it.
HA 2022.10.5

**Comment by pedolsky** [comment]
Three times yes 😁
…
…

Super-awkward rookie mistake: forgot to clear cache. The container boxes are gone. Shouldn’t have updated at 2 AM.
Ok... may I change the premise? I'd love to have both again in one view, borders for cards and no borders for chips.

This was my theme before 2022.11.0b0:

```
Mushroom Lampen:

  ## Home Assistant
  masonry-view-card-margin: 20px 30px
  grid-card-gap: 18px
  stack-card-margin: 8px
  horizontal-stack-card-margin: 8px

  ha-card-box-shadow: inset 0 0 0 1px rgba(255, 191, 0, 0.8)
  # ha-card-border-color: rgba(255, 191, 0, 0.8) # rgba(0,0,0,0)
  ha-card-border-radius: 6px

  primary-background-color: rgb(255, 255, 255)
  primary-text-color: rgb(96, 125, 139) # blue-grey
  secondary-text-color: rgb(96, 125, 139) # blue-grey

  ## Mush Card
  mush-spacing: 8px
  mush-card-primary-font-size: 14px
  mush-card-secondary-font-size: 12px
  mush-card-primary-font-weight: bold
  mush-card-secondary-font-weight: bolder
  mush-card-primary-line-height: 1.5
  mush-card-secondary-line-height: 1.5

  ## Mush Chip
  mush-chip-box-shadow: none
  mush-chip-background: transparent 
```

Now changed into:

```
Mushroom Lampen:

  ## Home Assistant
  …
  # ha-card-box-shadow: inset 0 0 0 1px rgba(255, 191, 0, 0.8)
  ha-card-border-color: rgba(255, 191, 0, 0.8) # rgba(0,0,0,0)
  ha-card-border-radius: 6px

  …

  ## Mush Card
  …

  ## Mush Chip
  # mush-chip-box-shadow: none
  mush-chip-background: transparent 
```

**Comment by piitaya** [comment]
Should be good with that : https://github.com/piitaya/lovelace-mushroom/pull/799

**Comment by pedolsky** [comment]
WAAAH! You're my hero, a huge fat thankyou!!
