### ISSUE TITLE
[Bug]: 0.0.5 dont apply on hass 2022.10.5

### ISSUE THREAD

**Issue by Reubertt** [piitaya/lovelace-mushroom#798]
### Current Behavior

I don't have much to say, the borders are not being applied and it seems to me that the whole theme is not working. I'm installing it for the first time today so I don't know if any other issues are happening, but version 0.0.2 seems to be working fine.

### Environment

```markdown
VMware
Brower: Chrome

Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend: 20221010.0 - latest
```

**Comment by piitaya** [comment]
Is it related to Mushroom or Mushroom themes ? Looks like you're speaking about Mushroom themes.

**Comment by Reubertt** [comment]
Oh, I'm sorry, I had both tabs open and posted in the wrong place. My mistake. I will post on Mushroom Themes.
