### ISSUE TITLE
[Feature]: Custom Off States for Entities

### ISSUE THREAD

**Issue by murkumurdok** [piitaya/lovelace-mushroom#800]
### Is your feature request related to a problem?

Some media player devices have more "off" states instead of on/off.  For example, my AppleTV has the state of "standby" when it is actually off or sleeping.  Because of this, the mushroom card still colors the icon for the AppleTV as if the device was still on.

### Describe the solution you'd like

Include a configuration option for entity/media mushroom cards that allow you to set custom "off" states per entity so that the card will properly appear on or off.

**Comment by piitaya** [comment]
I think it's better to consider standby as inactive for every media player.

**Comment by murkumurdok** [comment]
> I think it's better to consider standby as inactive for every media player.

Sure, that works too

**Comment by murkumurdok** [comment]
Thank you

**Comment by murkumurdok** [comment]
Hello, my AppleTV device is still showing as turned on when in standby on the mushroom media card.

**Comment by murkumurdok** [comment]
No worries, it happens, thank you!
