### ISSUE TITLE
[Bug - Visual]: Climate card with dual HVAC action doesn't fit

### ISSUE THREAD

**Issue by backslashV** [piitaya/lovelace-mushroom#821]
### Current Behavior

When the thermostat is set to heat+cool, the climate card isn't able to correctly show the card elements:
![Screenshot_20221103-142640](https://user-images.githubusercontent.com/8752221/199838013-8a9abb06-1bbc-4385-90ed-09c1867daee0.png)

### Expected Behavior

Buttons should not be squished.

### Environment

```markdown
- Hassio: 2022.10.5
- Mushroom: 2.3.2
```

**Comment by piitaya** [comment]
Hello 🙂
You can use the full width on mobile. We can not display lot of information in a small space.

**Comment by backslashV** [comment]
> Hello 🙂 You can use the full width on mobile. We can not display lot of information in a small space.

Thanks. Even on desktop it is squished. I can see everything is a bit right shifted. Please let me know if it's normal so I can close the bug.
![image](https://user-images.githubusercontent.com/8752221/199849284-ebda366d-03b0-41ad-be04-dcc76babc28c.png)

**Comment by piitaya** [comment]
You use it in a grid. Just use it as a full width card to have larger card.
