### ISSUE TITLE
Entities are not populating

### ISSUE THREAD

**Issue by mikey6283** [piitaya/lovelace-mushroom#823]
### Current Behavior

When I try to edit an entity i constantly have a blue circle whirling.  Also In normal mode if i click the card , i receive a error message FAILED TO CALL SERVICE BINARY_SENSOR/TURN_ON SERVICE NOT FOUND. All works fine in  lovelace dashboard.

![Screenshot 2022-11-04 at 07 31 14](https://user-images.githubusercontent.com/88946206/199918690-f334e2a1-6f21-4dba-923e-3bcf9ca01adf.png)

### Expected Behavior

Unable to create cards correctly

### Steps To Reproduce

Error message on activation card

![IMG_0039](https://user-images.githubusercontent.com/88946206/199920890-24903892-6bc5-472e-8b0f-422186534aa3.JPG)

### Environment

```markdown
- OS: Unraid VM
- Node:
- Version:
- Hassio: version 2022.11.1

dwains dashboard version:v2.3.2
```

### Anything else?

Any advice would be help.

**Comment by piitaya** [comment]
Hello 🙂 You're using dwains dashboard but this repository is for Mushroom cards.

**Comment by mikey6283** [comment]
Yes I am using Dwains Dashboard with the Mushroom Cards . apologise if it is not the Mushroom cards are not working . I will create an issue with Dwains.

**Comment by piitaya** [comment]
Thanks, no problem ! 🙂
