### ISSUE TITLE
[Feature]: Support ha-alert in title card

### ISSUE THREAD

**Issue by TheFes** [piitaya/lovelace-mushroom#824]
### Is your feature request related to a problem?

I just noticed the Markdown card supports the ha-alert component for nice formatting of alerts in the card. 
The markdown card only supports templates in the content part, and I also use templates in the title, so for me the markdown card doesn't work

### Describe the solution you'd like

It would be nice if the title card would also support this
https://www.home-assistant.io/dashboards/markdown/#ha-alert

**Comment by piitaya** [comment]
Hello ! It's not planned to add markdown support or custom html in title card. Just plain text for now.
