### ISSUE TITLE
[Bug]: Person card doesn't show entity picture properly

### ISSUE THREAD

**Issue by tomasjuchelka** [piitaya/lovelace-mushroom#830]
### Current Behavior

The person and entity card doesn't show the entity picture.
The picture is elsewhere normaly visible and for example Tile card can show it without any issues.

![Person_muschroom_card](https://user-images.githubusercontent.com/1104087/200366568-6ffd3b39-0c1a-45e6-b77c-62e1313ec1d0.jpg)

Are they any requirements for the picture, like format, resolution, ...?
Thank you!

### Environment

```markdown
- OS:Raspbian
- Mushroom Version: 2.3.3
- Hass:2022.11.0 (docker)
- Brower: Chrome (107.0.5304.88)
```

**Comment by piitaya** [comment]
Hello !
Can you provide your entity state ?

**Comment by tomasjuchelka** [comment]
Hello!

editable: true 
id: tomas_juchelka 
source: device_tracker.galaxy_s22 
user_id: f1a0d51bfxxxxxxxxxxxxxxxxxxxxxf3496 
entity_picture: /api/image/serve/c85c4f3d53295f3ccf51fe05e12879a1/512x512 
friendly_name: Tomáš

If I remember it, I uploaded the picture over the HASS dialogs.

**Comment by piitaya** [comment]
It must be good in the latest version `2.3.4`

**Comment by tomasjuchelka** [comment]
Manually tested and working like a charm :)
Thanks you!
