### ISSUE TITLE
[Bug]: Cards not showing in "Add Card" Menu

### ISSUE THREAD

**Issue by Roycinger** [piitaya/lovelace-mushroom#834]
### Current Behavior

Currently, no mushroom card option is shown when trying to add a card
![image](https://user-images.githubusercontent.com/7791335/200686638-cd7fa816-8e03-4211-bdf7-a5b1e97ed899.png)
I followed the instruction by placing the mushroom.js in the config/www directory:
![image](https://user-images.githubusercontent.com/7791335/200686796-52c55321-0c02-480b-9ad8-1f3fef90d41c.png)

and referencing in the dashboard ressources:
![image](https://user-images.githubusercontent.com/7791335/200686871-1c2769d1-5b5b-457e-98d9-6eb19c40d7a8.png)

### Expected Behavior

Mushroom cards showing up in "Add Card" dialogue

### Steps To Reproduce

Following the installation manual as in the mushroom documentation

### Environment

```markdown
- OS: HAOS
- Browser: Chrome
- Version: 107.0.5304.87
- Hassio: 2022.11.2
```

### Anything else?

Note:
I'm quite new to Home Assistant, doing my first steps.
Highly possible that I overlooked something important

**Comment by piitaya** [comment]
Do you use HACS ? You don't need to follow the manual steps if you install it with HACS.

**Comment by Roycinger** [comment]
> Do you use HACS ? You don't need to follow the manual steps if you install it with HACS.

Hey,
thanks for the reply!
Yes, I used HACS to install but the cards didnt show up anyways

**Comment by piitaya** [comment]
Try removing all the ressources, uninstall mushroom and reinstall it from HACS

**Comment by Roycinger** [comment]
Removed all ressources and installations and cleanly reinstalled the mushroom package.
For some reason the cards do actually show up now.
Thanks a lot!

**Comment by piitaya** [comment]
There are similar closed problems. I can't say more than clear your cache, reboot, reinstall. It's mostly a caching issue.

**Comment by colder1989** [comment]
it doesn't work for me either ... I tried everything: reboot, using incognito mode browser, etc .... I installed home assistant container on docker raspberry

**Comment by jalejandro0211** [comment]
> Removed all ressources and installations and cleanly reinstalled the mushroom package. For some reason the cards do actually show up now. Thanks a lot!

Yes it was the same for me, thanks!

**Comment by STUKguy** [comment]
@colder1989 just in case you haven't found a fix, try using a different browser. Did the whole reboot, remove and read through allot of jargin before i thought instead of using Chrome why don't i use Edge and surprisingly it worked
