### ISSUE TITLE
[Bug]: Vacuum card doesn’t show start button

### ISSUE THREAD

**Issue by broyuken** [piitaya/lovelace-mushroom#835]
### Current Behavior

Start button doesn’t show up for my deebot n79s

### Expected Behavior

Button to show up

### Steps To Reproduce

Enable the button
Button doesn’t appear

### Environment

```markdown
- OS: HA OS
- Node:
- Version: 2.3.4
- Hassio: 2022.11.2
```

### Anything else?

The turn on button shows when I go into more info, but the card itself doesn’t show it.

**Comment by piitaya** [comment]
We will need more information : the complete state of your entity and the yaml of your card.

**Comment by broyuken** [comment]
Of course,

the state is currently 'off' and here is the rest of it. 
'''
fan_speed_list:
  - normal
  - high
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: normal
status: charging
error: null
friendly_name: Consuela
supported_features: 2043
'''
And the yaml

`type: custom:mushroom-vacuum-card
entity: vacuum.consuela
commands:
  - start_pause
  - stop
  - locate
  - return_home `

**Comment by piitaya** [comment]
According to `supported_features` attributes, your vacuum doesn't support start/pause so it's hidden.
The rules to display the icons are the same as `more-info`dialog in Home Assistant. Here's mine with start/pause support

![image](https://user-images.githubusercontent.com/5878303/200883285-b165a9a2-3b4e-4dcb-bec0-15bcb2b671a5.png)

I think you should not have these icons

**Comment by broyuken** [comment]
I have the start cleaning button that you have in your screenshot. So how could I start my vacuum from this card?

**Comment by broyuken** [comment]
![CD92A343-79EF-45F4-9902-21ABD525DC6C](https://user-images.githubusercontent.com/1593391/200975672-341c0d4c-b932-401b-b9af-29a0953e3797.jpeg)

I see you have the actual button that I don’t, but can you make it function like the xiaomi card does where i can turn it on from the card? Also battery status would be awesome as well.

**Comment by broyuken** [comment]
Looking at the code, it looks like most vacuums use the service vacuum.start, mine uses vacuum.turn_on

start: {service: 'vacuum.turn_on'},
pause: {service: 'vacuum.stop'},
stop: {service: 'vacuum.turn_off'},

**Comment by piitaya** [comment]
You can already turn_on turn_off by using the toggle tap_action on the card.

**Comment by broyuken** [comment]
Yes but not by a button which is not intuitive. If this isn’t something you’re looking to accommodate that’s fine, I’ll just need to use a different card for my vacuum because this one isn’t flexible enough.

**Comment by broyuken** [comment]
This was great, but 2.4.1 undid the changes. I don’t think they were rolled up correctly.
