### ISSUE TITLE
Entity card dynamic icon on scripts

### ISSUE THREAD

**Issue by shirou93** [piitaya/lovelace-mushroom#840]
### Is your feature request related to a problem?

Dynamic icon based on state in scripts.

### Describe the solution you'd like

When script is disabled icon looks gray and colored when enabled. This feature actually working on switches.

**Comment by shirou93** [comment]
> Hello. What do you mean by disabled script ?

When script is not executing currently.
Example i have scripts when takes 1 hour after execute.   Primary info showing state of scripts but icon is always colored.![Screenshot_2022-11-09-19-23-38-41_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/59237288/200910911-09d36926-2696-49ee-a8f0-e5040423b8d1.jpg) wył= not currenty working

**Comment by piitaya** [comment]
I didn't know what the best for scripts : always colored or not. Looks like I have the answer 😅

**Comment by drewancil** [comment]
I was using it for visual confirmation a script was running.  Behavior indeed changed.  I would be eager to see it reverted :)
