### ISSUE TITLE
[Feature]: New update breaks media players that are 'idle' when actually on

### ISSUE THREAD

**Issue by c-kick** [piitaya/lovelace-mushroom#842]
### Is your feature request related to a problem?

Since the last update (2.3.5) my media player cards for my Yamaha (YNCA) receivers are broken. These receivers are 'idle' when they are actually on, and are on inputs that don't trigger/indicate a 'playing' state (such as an analog input).

As the 'idle' state is now considered an 'off' state, the media player card is unavailable while the receiver is in fact on.

### Describe the solution you'd like

It would be great to have an optional configurable attribute for the media player card, something along the lines of `off_state` override, which you could set to `off` or `standby`, depending on your device.

### Additional context

Solution for now was to remove the affected line in [the JS](https://github.com/piitaya/lovelace-mushroom/commit/99d47f85df9d6f5a765433f7db04972e3abed6da)
from `return state !== "idle" && state !== "standby";` to `return state !== "standby"; `

But ofcourse that's only a temporary solution.

**Comment by piitaya** [comment]
What do you mean by "media player card is unavailable" ? The icon is just grey.

Providing override option is not a solution because if we add an option for each use-case the card will be complicated to use. Some people will want override icon rules, override state, etc... You're better to use template card if you want custom thing.

`idle` mean inactive, so that's why the icon is grey.

**Comment by c-kick** [comment]
Yes, I meant 'unavailable' as in: in an off-state.

I understand your point regarding complicated use, but what I'm suggesting is an _optional_ override. Something an advanced user with YAML-knowledge can apply, leaving the default settings exactly as they are now.

A template card is the only alternative, but you'd lose the (collapsing) controls, which is the big advantage of the media card.

I think the optional override would be a great addition.

**Comment by piitaya** [comment]
I don't want people to fix thing with advanced option. I prefer to try to understand why the current UX is not the right one.
What's the use-case to have controls and colored icon when `idle` ?

**Comment by c-kick** [comment]
Use case: The [YNCA](https://github.com/mvdwetering/yamaha_ynca) integration (which is the best one for Yamaha Receivers) assumes an 'idle' state when input is set to an analog input (or other inputs that don't provide 'playing' states). For example it assume this state when HDMI ARC input, Audio In, AUX, etc. are selected.

An interesting issue from the YNCA repository regarding the 'idle' state: https://github.com/mvdwetering/yamaha_ynca/pull/64

**Comment by JGKarlin** [comment]
I have the same use case with a video projector that goes "idle" after a certain period of time running an app. As a result, the icon darkens, making it appear as if it is no longer on.

**Comment by c-kick** [comment]
One could consider the similarities with (petrol) engines; when they’re idling, they’re not off.
