### ISSUE TITLE
[Feature]: Chips should have possibility to define tap actions

### ISSUE THREAD

**Issue by daha76** [piitaya/lovelace-mushroom#843]
### Is your feature request related to a problem?

I use chips for quick status overview, but for some of the chips I would like to have an option to define tap action or at least to have a possibility to disable tap action for a specific chip. I have created a template chip which show the status of my car alarm. Entity is a type of lock. If I click on that template chip it arm/disarm my car alarm without any other confirmation or popup dialog. This is quite dangerous for such type of entity. For example alarm chip shows info pop up.

### Describe the solution you'd like

It would be nice to have possibility to define tap action for chips, or at least to have a possibility enable/disable tap action for chips. Or maybe a new chip for the lock type entity could be introduced, if possible.

**Comment by piitaya** [comment]
You can already define the `tap_action`, `hold_action` and `double_tap_action` for every chip.

**Comment by daha76** [comment]
I have no options like that when I open a chip for editing. I have only this options: icon, icon color, picture, content. It looks like this:
![image](https://user-images.githubusercontent.com/16493975/201071387-805c7b71-b6a8-4af3-ac93-ba1f1617ec99.png)

**Comment by piitaya** [comment]
What's your Mushroom version? Update it, it should be ok.

**Comment by daha76** [comment]
In HACS I see that I have version 2.3.5 but when I open dev console in Chrome I see version 2.1.3. Something is wrong...

**Comment by daha76** [comment]
Redownloading Mushroom solved that issue, thanks.
