### ISSUE TITLE
[Feature]: Vacuum animation for cleaning and docking

### ISSUE THREAD

**Issue by marcgeurts** [piitaya/lovelace-mushroom#846]
### Is your feature request related to a problem?

I have created an animation for the the vacuum card, the icon of the vacuum and mob gently moves like it's cleaning, or docking.

![image](https://user-images.githubusercontent.com/11457346/201351287-8cf31df4-f10c-4654-be9e-9a0fbbc8fff1.png)

### Describe the solution you'd like

Can I open a pull request for this?

**Comment by piitaya** [comment]
Yes it can be nice 🙂

**Comment by marcgeurts** [comment]
I'm not allowed to push a new branch?

**Comment by piitaya** [comment]
You have to fork the project, commit on your repository and create a PR 🙂
