### ISSUE TITLE
[Bug]: Fan card displays 0% when off

### ISSUE THREAD

**Issue by mattsheffiel** [piitaya/lovelace-mushroom#851]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue.

### Current Behavior

When a fan is off it displays “0%” instead of “Off.” This is inconsistent with the behavior of the light card.

![6A2C0140-708A-47B6-8A73-F9305E96798E](https://user-images.githubusercontent.com/29007028/201716109-cf543e6b-e7ec-4ce9-86c5-4bc79ba369f6.jpeg)

### Expected Behavior

The fan card should display “Off” instead of “0%” when the fan is off. 

### Steps To Reproduce

Add a fan card and turn off the fan.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Firefox/Mobile App
- HA Version:2022.11.2
- Mushroom: 2.3.6
```

**Comment by bieniu** [comment]
Same problem here. HA 2023.7, Mushroom 3.0.5, browser Firefox 115.

This issue occurs when the fan entity reports `0` as `percentage` when the fan is `off`. This is the default behavior for template fan with `percentage_template`.

![obraz](https://github.com/piitaya/lovelace-mushroom/assets/478555/09e6f74e-9e5b-45dd-91be-04842688ad2f)
![obraz](https://github.com/piitaya/lovelace-mushroom/assets/478555/8bff7eb9-d9d1-45c3-9bd1-4e1d836aafc2)

If the fan entity returns `null` as `percentage` then there is no problem.

![obraz](https://github.com/piitaya/lovelace-mushroom/assets/478555/6c040778-3604-4de0-a0fa-fe54ffdb61f2)
