### ISSUE TITLE
[Bug]: state_attr, the icon circle has disappeared

### ISSUE THREAD

**Issue by BixZod** [piitaya/lovelace-mushroom#860]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue.

### Current Behavior

The main problem is that if I put:
`{{ state_attr("light.accendi_spegni_luci", "rgb_color")[0] }}  {{ state_attr("light.accendi_spegni_luci", "rgb_color")[1] }}  {{ state_attr("light.accendi_spegni_luci", "rgb_color")[2] }}`
**on "icon_color:"** it's as if I simply put a color code like this eg: "255, 255, 255", so why does the circle disappear?

### Expected Behavior

It all works, it takes the color of my light's current state, but I don't understand why the circle has to disappear.

![image](https://user-images.githubusercontent.com/73430541/202828697-075c5b70-738f-4a09-8a6e-c58c9e6e35bd.png)

### Context

YAML state
```
type: custom:mushroom-template-card
primary: ILLUMINAZIONE
secondary: '{{ states(''sensor.lights_luci_della_casa_accese'')}} in funzione'
icon: mdi:lightbulb
icon_color: >-
  {{ state_attr("light.accendi_spegni_luci", "rgb_color")[0] }}  {{
  state_attr("light.accendi_spegni_luci", "rgb_color")[1] }}  {{
  state_attr("light.accendi_spegni_luci", "rgb_color")[2] }}
layout: vertical
tap_action:
  action: navigate
  navigation_path: luci_casa
hold_action:
  action: toggle
entity: light.accendi_spegni_luci
fill_container: true
double_tap_action:
  action: more-info

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by piitaya** [comment]
Try with comma between number 🙂

**Comment by BixZod** [comment]
> 

I already tried, but still the circle around the icon does not appear

**Comment by pedolsky** [comment]
The following is still working:

`{{ '#%02x%02x%02x' % state_attr(entity, 'rgb_color') }} `
