### ISSUE TITLE
[Bug]: 2.4.1 doesn’t include 2.4.0 changes

### ISSUE THREAD

**Issue by broyuken** [piitaya/lovelace-mushroom#864]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue.

### Current Behavior

Turn on/off buttons and animations are gone

### Expected Behavior

2.4.1 should include changes from 2.4.0

### Steps To Reproduce

Install 2.4.0
Turn on animations or turn on/off button on vacuum card
Install 2.4.1
See errors in card forcing you to use yaml mode
Animations don’t work
Turn on/off buttons are gone 

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by piitaya** [comment]
Hello.
Try reinstall it. I don't have issues with the 2.4.1

**Comment by broyuken** [comment]
Weird, seems to be fine after a reinstall
