### ISSUE TITLE
[Feature]: Number card to control number and input_number entities

### ISSUE THREAD

**Issue by PaoloTK** [piitaya/lovelace-mushroom#872]
### Is your feature request related to a problem?

Mushroom cannot control number or input_number entities at the moment.

### Describe the solution you'd like

Either a new "Number Card" or the ability to show slider control for entity card when a number or input_number entity is selected.

**Comment by piitaya** [comment]
A pul request is already open for that https://github.com/piitaya/lovelace-mushroom/pull/676

**Comment by PaoloTK** [comment]
> A pul request is already open for that #676

Missed it, thank you.
