### ISSUE TITLE
[Bug]: console flooded by "unhandled promise rejection"

### ISSUE THREAD

**Issue by Stooovie** [piitaya/lovelace-mushroom#880]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

My HA in browser is kinda slow, and upon opening the Developer console, I see neverending barrage of "Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'i.attributes')" errors from Mushroom.js:350.

How can I investigate further? I am not a developer.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome, Edge, Safari
- HA Version: 2022.11.4 as of now, have noticed this before
- Mushroom:2.4.1
```

**Comment by freeDom-** [comment]
Same problem here. Lots of TypeErrors popping up.
Browser Firefox 110.0 (64 bit)
HA Version 2023.2.5

Here is a stack trace:

`Uncaught (in promise) TypeError: i is undefined
    render mushroom.js:2663
    update mushroom.js:37
    performUpdate mushroom.js:25
    scheduleUpdate mushroom.js:25
    _$Ej mushroom.js:25
    requestUpdate mushroom.js:25
    set mushroom.js:25
    value hui-masonry-view.ts:357
    value hui-masonry-view.ts:357
    performUpdate app.98f1a6e8.js:1513
    scheduleUpdate app.98f1a6e8.js:1513
    _$Ej app.98f1a6e8.js:1513
    requestUpdate app.98f1a6e8.js:1513
    set app.98f1a6e8.js:1513
    value hui-root.ts:548
    _$AE app.98f1a6e8.js:1513
    performUpdate app.98f1a6e8.js:1513
    scheduleUpdate app.98f1a6e8.js:1513
    _$Ej app.98f1a6e8.js:1513
    requestUpdate app.98f1a6e8.js:1513
    set app.98f1a6e8.js:1513
    j app.98f1a6e8.js:1513
    _$AI app.98f1a6e8.js:1513
    p app.98f1a6e8.js:1513
    $ app.98f1a6e8.js:1513
    _$AI app.98f1a6e8.js:1513
    j app.98f1a6e8.js:1513
    update app.98f1a6e8.js:1513
    performUpdate app.98f1a6e8.js:1513
    scheduleUpdate app.98f1a6e8.js:1513
    _$Ej app.98f1a6e8.js:1513
    requestUpdate app.98f1a6e8.js:1513
    set app.98f1a6e8.js:1513
    value app-drawer-layout.js:189
    value hass-loading-screen.ts:84
    performUpdate app.98f1a6e8.js:1513
    scheduleUpdate app.98f1a6e8.js:1513
    _$Ej app.98f1a6e8.js:1513
    requestUpdate app.98f1a6e8.js:1513`
