### ISSUE TITLE
[Feature]: Add tap action to Title card 

### ISSUE THREAD

**Issue by hfalk** [piitaya/lovelace-mushroom#882]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I have multiple views, and would love to navigate to another view by pressing the title card

**Comment by piitaya** [comment]
Duplicate https://github.com/piitaya/lovelace-mushroom/issues/665
