### ISSUE TITLE
[Bug]: Template Card - Icon Color RGB template does not work

### ISSUE THREAD

**Issue by morotsgurka** [piitaya/lovelace-mushroom#884]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Using the Template card to make a room-card I'd like the icon color to be the color of a specific light inside that room, similar to the mushroom light entity card "Use Light Color".

Using something like this...
```
{% set numlights = states('sensor.office_lights_on') | int %}
{% set numswitches = states('sensor.office_switches_on') | int %}
{% set numtotal = numlights + numswitches | int %}

{% if numtotal == 0 %}
{% else %}
  light-green
{% endif %}
```
...works. But it is limited to a single color.

`rgb({{ state_attr('light.hue_lightstrip_02', 'rgb_color') | join(',') }})`
Which returns ex: rgb(255,255,255) for white. Or
{{ state_attr('light.hue_lightstrip_02', 'rgb_color') | join(',') }}
Which returns 255,255,255 for white. Neither works. In fact sometimes the secondary info disappears when doing this, sometimes the circle behind the icon disappears.

### Expected Behavior

The icon color should take the template'ed rgb color, similar to just writing a rgb color in that field manually. Writing 255,255,255 works. But having a template that returns that, does not. 

### Steps To Reproduce

1. Create Template Card
2. Add some icon
3. Add some secondary info, ex `{{ states('sensor.temp') | float | round(0) }}°C` for a temperature reading
4. Add this in the icon color: `{{ state_attr('light.your-light', 'rgb_color') | join(',') }}`
5. Make sure the light you use is on and has an RGB color
6. Try the same template in the Developer tools - template section

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:Firefox 107.0.1
- HA Version: 2022.11.5
- Mushroom: 2.4.1
```

### Anything else?

Normal card, no icon template
![image](https://user-images.githubusercontent.com/110823841/205602250-ff5963a4-f089-4c0e-8ea4-fd64dc421322.png)
Added template code for icon color, secondary info is gone. Icon is not colored (template returning a yellow color in dev tools)
![image](https://user-images.githubusercontent.com/110823841/205602581-3896df97-b04c-4caa-95e8-440e3187ade7.png)

This might be a feature request in a way. A simpler way would be to have the same option to "use light color" as the light card has. But templating should still work for specific cases.

**Comment by piitaya** [comment]
It's not easy to add comma to jinja templates because it's interpreted as list
Here's a sample that should fix your problem :
```jinja2
{% set rgb_color = state_attr('light.test_bulb_color', 'rgb_color') %}
{{ rgb_color[0] }},
{{ rgb_color[1] }},
{{ rgb_color[2] }}
```

**Comment by morotsgurka** [comment]
Yes, those work. Thank you!
I had a feeling the list was the issue but could not find a way to format it as a string and still work.
