### ISSUE TITLE
[Bug]: The secondary_info "state" shows a wrong information

### ISSUE THREAD

**Issue by ati-g** [piitaya/lovelace-mushroom#902]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

The secondary_info "state" shows a wrong information.
The status "heating" (Heizen) is displayed although the temperature has already been reached. The standard control shows "idle" (Leerlauf).

![image](https://user-images.githubusercontent.com/100496773/208294844-8d4b25a3-0c41-4fc9-8f82-4e7513b754e3.png)

### Expected Behavior

If the temperature has already been reached the state sould be "idle", like in the standard control

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by piitaya** [comment]
It display the state, not the action.
