### ISSUE TITLE
Climate Card, ability to change Step Size when Adjusting Temperature

### ISSUE THREAD

**Issue by DaveTiff** [piitaya/lovelace-mushroom#903]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Would like the ability to change Step Size when Adjusting Temperature

### Describe the solution you'd like

Variable the same as the Thermostat card. step_size: 0.5

**Comment by piitaya** [comment]
Hello. There is already an discussion for this: https://github.com/piitaya/lovelace-mushroom/issues/664
