### ISSUE TITLE
[Bug]: Wrong colors for Climate Card temperature controls

### ISSUE THREAD

**Issue by LaserPew** [piitaya/lovelace-mushroom#912]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

In my climate entity I can set both the low (cool mode) and high (heat mode) temperatures.
In the Mushroom Climate Card the background color for the low/cool control is red and for the high/heat control its blue, see screenshot:

![Screen Shot 2022-12-24 at 16 09 29 PM](https://user-images.githubusercontent.com/222357/209441943-06d2943b-12fd-402e-b066-3dab09177dfa.png)

### Expected Behavior

The colours should actually be the other way around, so high/heat control should have a red background and low/cool control should have a blue background.

### Environment

```markdown
- Browser: Safari 16.2
- HA Version: 2022.12.8
- Mushroom: 2.4.1
```

### Anything else?

Issue seems to be at these two lines in the code:

https://github.com/piitaya/lovelace-mushroom/blob/main/src/cards/climate-card/controls/climate-temperature-control.ts#L95
https://github.com/piitaya/lovelace-mushroom/blob/main/src/cards/climate-card/controls/climate-temperature-control.ts#L106

**Comment by piitaya** [comment]
The high temp is used for cooling and the low temp for heating.

**Comment by LaserPew** [comment]
Ah okay, then I’m using the climate entity wrong. Thank you for clarifying and sorry for the bug ticket.
