### ISSUE TITLE
[Bug]: Unable to use card_mod for Custom: Mushroom Title Card

### ISSUE THREAD

**Issue by clowncracker** [piitaya/lovelace-mushroom#946]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I am unable to use card_mod on the Custom: Mushroom Title Card.  Any changes added to the YAML result in no change to the card.

### Expected Behavior

I expect card_mod customization to work for this card.  They work for other Mushroom cards.  The desired outcome to to make the card smaller since the margins are so large on the title.

### Steps To Reproduce

This is YAML for the card:

type: custom:mushroom-title-card
title: ''
subtitle: Rooms
card_mod:
  style: |
    ha-card {
      margin-top: -7px;
      margin-bottom: -7px;
    }

### Environment

```markdown
- Browser: Firefox 
- HA Version: 2023.1.4
- Mushroom: 2.4.1
```

**Comment by myhades** [comment]
·position: sticky· doesn't work too, exclusively on this card.
But I ran into this [https://github.com/thomasloven/lovelace-card-mod/issues/227](url), where some do apply.
Looking for substitute in the meantime, any advice?

**Comment by LeiChat** [comment]
Am I correct in thinking the mushroom-title-card does not implement ha-card?
And that card_mod requires that container/class to be present?
