### ISSUE TITLE
Cards do not display properly via Google Cast

### ISSUE THREAD

**Issue by malcolmturnbull** [piitaya/lovelace-mushroom#95]
Some lovelace-mushroom cards work partially when Cast to a display - my use case is I Cast to a Google Home display. I love these cards and would love to use them on my touch display!

This issue occurs with either a HACS-based or regular install.  

Cards:
Chips-card: Works partially - reports icon states, responds to colours, but label titles do not change (e.g., content_info: name will still display the state of the entity). 
Light-card: Works partially - reports icon states, controls brightness, but label colours do not change and colour / temperature selection buttons are not shown. 
Entity-card: As above
Title-card: Does not display - shows 'Custom component doesn't exist' error. 

I have not tested the other cards.

**To Reproduce**
1. Create a lovelace config with mushroom-cards
2. Use https://cast.home-assistant.io/ or [this template](https://community.home-assistant.io/t/cast-and-re-cast-a-lovelace-view-to-a-google-hub/259631)
3. Compare lovelace view on desktop / mobile to cast view - cast will not display consistently

**Additional context**
Cast feature introduction: [Home Assistant Cast](https://www.home-assistant.io/blog/2019/08/06/home-assistant-cast/)

```
http:
  cors_allowed_origins:
    - https://cast.home-assistant.io
```
Is included in my configuration.yaml.

**Comment by piitaya** [comment]
Looks like you are not on the latest version due to a cache issue because the feature you describe are introduced in new Mushroom versions.

Can you look at the mushroom version ?
I didn't have cast device but I think you can do this with chrome :
1. go to `chrome://inspect/#devices`
2. inspect your devices
3. open the web console
4. mushroom version should be displayed :
![image](https://user-images.githubusercontent.com/5878303/153582821-a90f45fb-827d-496b-b75a-12c495e8c74d.png)

**Comment by malcolmturnbull** [comment]
Hi There, 

Will do - I installed Mushroom today via Hacs, then tried a manual install of 1.0.3: 

Screenshot from HACS: 
![image](https://user-images.githubusercontent.com/8454281/153583464-f153e460-a394-478f-aaf4-387d4c75cd1f.png)

I will need to work out how to connect to my Nest Hub / Google Home Display using the web console - I could not get it to appear. When I look at my local connection it looks like this: 

![image](https://user-images.githubusercontent.com/8454281/153584469-063c169b-460a-40b6-8462-359c2d61cf31.png)

but the cards do load on desktop - it is only using the Cast functionality that causes issues:

![image](https://user-images.githubusercontent.com/8454281/153584527-5c8451a1-1818-4e5f-a9fa-aa1f145aaed0.png)

**Comment by malcolmturnbull** [comment]
I have reinstalled via HACS and removed the duplicate manual installation that I had, my local console now displays: 

![image](https://user-images.githubusercontent.com/8454281/153585190-04f6acee-96ad-4951-9617-fe5a9b2e9b6c.png)


but sadly the issue is still present when casting.

**Comment by malcolmturnbull** [comment]
Good News! 

I was able to resolve this by clearing my cache, then reauthenticating via https://cast.home-assistant.io/ - There were some changes between 2022.2.0 and 2022.2.5 that seem to have caused this and other issues. 

Thank you for your help!
