### ISSUE TITLE
Wrap Text

### ISSUE THREAD

**Issue by RanAkiva** [piitaya/lovelace-mushroom#954]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

In my mushroom card view in my android mobile text is cut.
How can I do wrap text?
I searched for similar issues, but unfortunately I don't have programing experience.
Can you please help me with the right syntax and where to add it?

Thank you very much,
Ran Akiva
![text cut](https://user-images.githubusercontent.com/98401321/213466101-6f50b178-837c-4433-95ba-c40d06e6259c.jpeg)

### Expected Behavior

![text cut](https://user-images.githubusercontent.com/98401321/213466357-cea91cbf-db42-4479-a672-aefa115defc3.jpeg)

### Context

type: custom:mushroom-light-card
entity: light.yeelight_ceiling1_0x7c57c60
name: חדר ארונות
icon: ''
use_light_color: true
show_brightness_control: false
show_color_temp_control: false
show_color_control: false
tap_action:
  action: toggle
fill_container: true
secondary_info: none
layout: vertical

### Environment

```markdown
Home Assistant 2022.12.9
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

Mushroom  v2.4.1
```

**Comment by piitaya** [comment]
It's not possible to wrap text. Having multiline text will break the design.

**Comment by RanAkiva** [comment]
Is there a solution for text that is cut and can't see the full text?
Best,
Ran Akiva

**Comment by piitaya** [comment]
You can use a 3 columns grid instead of a 4 columns grid.

**Comment by RanAkiva** [comment]
Thank you, this is a good solution.
By the way, is there a way to control the size of the card? Height and width.

**Comment by piitaya** [comment]
You can modify the style of the card using themes variables : https://github.com/piitaya/lovelace-mushroom-themes#build-your-own and https://www.home-assistant.io/integrations/frontend/#defining-themes. You can not define the size of the card because it depends of the content. But you can change the font size if you want.
