### ISSUE TITLE
[Bug]: <Unexpected Token> causing Custom Element doesn't exist

### ISSUE THREAD

**Issue by continuousnet** [piitaya/lovelace-mushroom#969]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

When using the musthroom card on an Android tablet i get the following errors no matter what browser I use.    Google webview is the latest version

Logger: frontend.js.latest.202301100
Source: components/system_log/__init__.py:256
First occurred: 10:24:09 AM (86 occurrences)
Last logged: 3:04:44 PM

http://192.168.1.105:8123/lovelace-test/mushroom:0:0 Uncaught
http://192.168.1.105:8123/hacsfiles/hass-bha-icons/hass-bha-icons.js?hacstag=17980857689288:165:37 Uncaught SyntaxError: Unexpected token .
http://192.168.1.105:8123/lovelace-test/clock?kiosk:0:0 Uncaught
http://192.168.1.105:8123/local/community/lovelace-mushroom/mushroom.js:73:7113 Uncaught SyntaxError: Unexpected token ?
http://192.168.1.105:8123/hacsfiles/lovelace-mushroom/mushroom.js?hacstag=444350375251:73:7113 Uncaught SyntaxError: Unexpected token ?

### Expected Behavior

Should wokr like it does on desktop

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: All Mobile Browsers
- HA Version: 2023.1.6
- Mushroom: 2.5.1
```

**Comment by piitaya** [comment]
Duplicate https://github.com/piitaya/lovelace-mushroom/issues/963
