### ISSUE TITLE
[Bug]: mushroom cover card error in Android APP

### ISSUE THREAD

**Issue by sezlony** [piitaya/lovelace-mushroom#970]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

`Custom element doesn't exist: mushroom-cover-card`

I rarely use android app, but when I have to it's important. Today I wanted to control shutters without the automation, but all I get is this error message and cards dissapeared. :sad:

### Expected Behavior

work as usual, custom mushroom cover cards are alive and useable

### Steps To Reproduce

Home Assistant app v2022.12.0-full
HACS v1.29.1
Mushroom v2.5.1

### Context

YAML state
```yaml

```

### Environment

```markdown
- App: v2022.12.0-full
- HA Version: 2023.1.4
- Mushroom: v2.5.1
```

**Comment by piitaya** [comment]
Duplicate #963

**Comment by sezlony** [comment]
other topic is about iOS and not ANDROID, but you decide...

**Comment by piitaya** [comment]
Some people complains about on Android in this thread too. I prefer to have all the feedbacks in the same thread for better debugging.

**Comment by sezlony** [comment]
sorry, I don't know how to downgrade to a previous version

my phone is a Meizu 15, android 7
