### ISSUE TITLE
No slider/color on light card

### ISSUE THREAD

**Issue by spanzetta** [piitaya/lovelace-mushroom#976]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I can't see the brightness slider and/or color settings even if those options are enabled in the card..
I am using Tuya lamps
Am I doing something wrong?
See picture attached 

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2023.1.7
- Mushroom: 2.5.2
```

### Anything else?

![Screenshot_20230128_201920_Home Assistant](https://user-images.githubusercontent.com/49818743/215286953-e41c6d36-aaf8-46bf-bde5-30cfdab1eb65.jpg)

**Comment by piitaya** [comment]
Can you provide the yaml state of your entity? Looks like your light doesn't support brightness and color so the slider is not displayed.

**Comment by spanzetta** [comment]
You are completely right..

Apparently my lamps doesn't expose to HA brightness/color settings even if they support them (with the native Smartlife app and with Google Home/Alexa)... 

I think I have to play/manage the Tuya (localTuya)  integration settings to understand if I can enable those settings..

Thanks and sorry..  the issue can be closed

I am HA user from about a month.. still a lot to learn..

Regards

**Comment by spanzetta** [comment]
I was able to enable brightness/color in localTuya integration and now I can see and manage them with Mushroom cards!
Very very nice!
