### ISSUE TITLE
Mushroom Card blocking full screen video on Android.

### ISSUE THREAD

**Issue by Daniel-dev22** [piitaya/lovelace-mushroom#977]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Out of the blue I was suddenly on both an s21 and s22 unable to full screen videos. Between the time it was working and when it stopped I made 0 code changes to the frontend. I'm on the latest version of card mod and mushroom. If I remove card mod from hacs it works. If I add it back and remove mushroom and leave cardmod it also works. One of the 2 is messing this up.

For more detail I started this issue in the android repo as I thought it was a companion app issue because it works if I use Google chrome on both devices just not the companion app.

https://github.com/home-assistant/android/issues/3268

Also important to note it works in Google chrome just not android companion app.  It stopped working on a Samsung s21 a few weeks before my s22. I provided a bunch of videos recreating the issue and WebView logs of the companion app and Google chrome in the android issue link above.

### Environment

```markdown
- Browser: Chrome/2023.1.1-full
- HA Version: 2023.2b3
- Mushroom: 2.5.2
```

**Comment by piitaya** [comment]
Do you have the issue if you use another template card than Mushroom (e.g : Markdown card) ?
Mushroom did not officially support `card_mod` and will never. I cannot guarantee that there are no side effects.

**Comment by piitaya** [comment]
You will not have response but you're using 3 custom cards (frigate, card_mod and mushroom)

`card_mod` modify the dom to add custom style. 

you can try these 2 configurations to find the issue :
1. Use card_mod + markdown card instead of mushroom card
2. Use title card without card

Do not uninstall card_mod and mushroom for your tests, just modify your yaml to use/not use it.
