### ISSUE TITLE
Milky (frosted) blur effect in the background when more-Info is showed

### ISSUE THREAD

**Issue by fastender** [piitaya/lovelace-mushroom#99]
A Milky blur effect would improve focus if the background was darkened when more information is displayed, it is possible?

**Comment by pierrecle** [comment]
Nope, mushroom is just a set of cards, this feature would be more an override of the HASS modal background in a theme if cleanly possible.

**Comment by fastender** [comment]
Something like this: https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/1064 ?
